__d("LSMessageReplySourceType", [], (function(t, n, r, o, a, i) {
	var e = Object.freeze({
		NONE: 0,
		MESSAGE: 1,
		STORY: 2,
		FORWARD: 3,
		FB_STORY_SHARE: 4,
		IG_STORY_SHARE: 5,
		LIGHTWEIGHT_STATUS: 6,
		LIGHTWEIGHT_STATUS_REACTION: 7,
		FB_FEED_POST: 13,
		HIGHLIGHTS_TAB_POST_REPLY: 14,
		HIGHLIGHTS_TAB_LOCAL_EVENT_REPLY: 15,
		SHARED_ALBUM: 16,
		AVATAR_DETAIL: 17,
		NOTE_REPLY_ARMADILLO: 18,
		HIGHLIGHTS_TAB_CARDS_FOR_MOM: 19,
		HIGHLIGHTS_TAB_CARDS_FOR_BIRTHDAY: 20,
		NOTE_MENTION: 21,
		AI_PERSONA_NOTE_REPLY: 26,
		AI_PERSONA_NOTE_REACTION: 27,
		FB_MSGR_NOTE: 28
	});
	i.default = e;
}), 66);
