__d("MAWAdminMsgNormalized", ["MAWLocalizationType"], (function(t, n, r, o, a, i, l) {
	"use strict";
	function e(e, t) {
		switch (e) {
			case o("MAWLocalizationType").LOCALIZATION_TYPE.PARTICIPANT_ADDED_YOU:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.PARTICIPANT_ADDED_YOU_AND_ONE_USER:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.CURRENT_USER_ADDED_ONE_PARTICIPANT:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.CURRENT_USER_ADDED_TWO_PARTICIPANTS:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.PARTICIPANT_ADDED_ONE_USER:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.PARTICIPANT_ADDED_TWO_USER:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.PARTICIPANT_REMOVED_YOU:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.PARTICIPANT_REMOVED_YOU_AND_ONE_USER:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.CURRENT_USER_REMOVED_ONE_PARTICIPANT:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.PARTICIPANT_LEFT_GROUP:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.PARTICIPANT_REMOVED_ONE_USER:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.UNKNOWN_USER_ADDED_YOU_AND_ONE_USER:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.UNKNOWN_USER_ADDED_ONE_USER:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.UNKNOWN_USER_ADDED_TWO_USER:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.UNKNOWN_USER_REMOVED_ONE_USER:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.CURRENT_USER_PROMOTED_PARTICIPANT:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.CURRENT_USER_DEMOTED_PARTICIPANT:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.PARTICIPANT_CUSTOMIZE_PHOTO:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.PARTICIPANT_PINNED_MESSAGE:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.PARTICIPANT_UNPINNED_MESSAGE:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.E2EE_THREAD_UK_OSA_ADMIN_MESSAGE:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.PARTICIPANT_GOT_PROMOTED:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.PARTICIPANT_GOT_DEMOTED:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.PARTICIPANT_PROMOTED_YOU:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.PARTICIPANT_DEMOTED_YOU:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.PARTICIPANT_PROMOTED_PARTICIPANT:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.PARTICIPANT_SELF_DEMOTED:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.PARTICIPANT_DEMOTED_PARTICIPANT:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.PARTICIPANT_ADDED_DEVICE:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.PARTICIPANT_REMOVED_DEVICE:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.PARTICIPANT_UPDATED_DEVICE:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.CURRENT_USER_CLEAR_PARTICIPANT_NICKNAME:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.PARTICIPANT_CLEAR_OWN_NICKNAME:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.PARTICIPANT_CLEAR_CURRENT_USER_NICKNAME:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.PARTICIPANT_EPHEMERAL_TAKE_SCREENSHOT:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.PARTICIPANT_EPHEMERAL_RECORD_SCREEN:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.PARTICIPANT_SET_ADD_MODE_ADMIN_ONLY:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.PARTICIPANT_SET_ADD_MODE_ALL_MEMBERS:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.CURRENT_USER_BUMPED_MESSAGE:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.PARTICIPANT_BUMPED_CURRENT_USER_MESSAGE:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.PARTICIPANT_BUMPED_OWN_MESSAGE:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.PARTICIPANT_BUMPED_PARTICIPANT_MESSAGE:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.PARTICIPANT_LIMIT_SHARING_DISABLED:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.PARTICIPANT_LIMIT_SHARING_ENABLED:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.DUAL_THREAD_CUTOVER_ADMIN_MESSAGE_WITH_OTHER_USER_NAME: return {
				contactIds: t,
				contents: []
			};
			case o("MAWLocalizationType").LOCALIZATION_TYPE.PARTICIPANT_CREATED_POLL:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.PARTICIPANT_MIXED_POLL_UPDATE:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.PARTICIPANT_ADDED_YOU_AND_MORE_THAN_ONE_USERS:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.CURRENT_USER_ADDED_MORE_THAN_TWO_PARTICIPANTS:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.PARTICIPANT_REMOVED_YOU_AND_MORE_THAN_ONE_USERS:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.UNKNOWN_USER_ADDED_MORE_THAN_TWO_USER:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.PARTICIPANT_NAMED_GROUP:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.PARTICIPANT_CUSTOMIZE_HOTLIKE:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.CURRENT_USER_CUSTOMIZE_NICKNAME:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.PARTICIPANT_CUSTOMIZE_CURRENT_USER_NICKNAME:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.PARTICIPANT_SET_OWN_NICKNAME:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.PARTICIPANT_EPHEMERAL_SETTING_TURNED_ON_MINUTES:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.PARTICIPANT_EPHEMERAL_SETTING_CHANGE_MINUTES:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.PARTICIPANT_EPHEMERAL_SETTING_TURNED_ON_HOURS:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.PARTICIPANT_EPHEMERAL_SETTING_CHANGE_HOURS:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.PARTICIPANT_EPHEMERAL_SETTING_TURNED_ON_DAYS:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.PARTICIPANT_EPHEMERAL_SETTING_CHANGE_DAYS:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.PARTICIPANT_EPHEMERAL_SETTING_TURNED_OFF:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.PARTICIPANT_EPHEMERAL_SETTING_TURNED_ON_SECONDS:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.PARTICIPANT_EPHEMERAL_SETTING_CHANGE_SECONDS: {
				var n = t[0], r = t[1];
				return {
					contactIds: [n],
					contents: [r]
				};
			}
			case o("MAWLocalizationType").LOCALIZATION_TYPE.PARTICIPANT_ADDED_MORE_THAN_TWO_USER:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.PARTICIPANT_CUSTOMIZE_PARTICIPANT_NICKNAME:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.PARTICIPANT_CLEAR_PARTICIPANT_NICKNAME: {
				var a = t[0], i = t[1], l = t[2];
				return {
					contactIds: [a, i],
					contents: [l]
				};
			}
			case o("MAWLocalizationType").LOCALIZATION_TYPE.PARTICIPANT_CUSTOMIZE_AI_THEME:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.PARTICIPANT_CUSTOMIZE_THEME: {
				var s = t[0], u = t[1], c = t[2];
				return {
					contactIds: [s],
					contents: [u, c]
				};
			}
			case o("MAWLocalizationType").LOCALIZATION_TYPE.PARTICIPANT_CHANGED_POLL_VOTE:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.PARTICIPANT_REMOVED_POLL_VOTE:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.PARTICIPANT_ADDED_POLL_VOTE:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.PARTICIPANT_ADDED_POLL_OPTION: {
				var d = t[0], m = t[1], p = t[2];
				return {
					contactIds: [d],
					contents: [m]
				};
			}
			case o("MAWLocalizationType").LOCALIZATION_TYPE.PARTICIPANT_CHANGED_MULTIPLE_POLL_VOTES:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.PARTICIPANT_REMOVED_MULTIPLE_POLL_VOTES:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.PARTICIPANT_ADDED_MULTIPLE_POLL_VOTES:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.PARTICIPANT_ADDED_MULTIPLE_POLL_OPTIONS: {
				var _ = t[0], f = t[1], g = t[2], h = t[3];
				return {
					contactIds: [_],
					contents: [f, g]
				};
			}
			case o("MAWLocalizationType").LOCALIZATION_TYPE.CURRENT_USER_CHANGED_MULTIPLE_POLL_VOTES:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.CURRENT_USER_REMOVED_MULTIPLE_POLL_VOTES:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.CURRENT_USER_REMOVED_POLL_VOTE:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.CURRENT_USER_ADDED_MULTIPLE_POLL_VOTES:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.CURRENT_USER_ADDED_POLL_VOTE:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.CURRENT_USER_NAMED_GROUP:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.UNKNOWN_USER_NAMED_GROUP:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.UNKNOWN_USER_ADDED_YOU_AND_MORE_THAN_ONE_USER:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.CURRENT_USER_CUSTOMIZE_AI_THEME:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.CURRENT_USER_CUSTOMIZE_THEME:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.CURRENT_USER_CUSTOMIZE_HOTLIKE:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.CURRENT_USER_SET_OWN_NICKNAME:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.CURRENT_USER_CREATED_POLL:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.CURRENT_USER_ADDED_POLL_OPTION:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.CURRENT_USER_ADDED_MULTIPLE_POLL_OPTIONS:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.CURRENT_USER_MIXED_POLL_UPDATE:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.CURRENT_USER_CHANGED_POLL_VOTE:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.POLL_UNSENT_UPDATE:
			default: return {
				contactIds: [],
				contents: t
			};
		}
	}
	l.deconstructContactIdsFromAdminContent = e;
}), 98);
