__d("MAWConvertExtendedContentTypeToLSXmaContentType", [
	"LSXmaContentType",
	"WAArmadilloXMA.pb",
	"gkx"
], (function(t, n, r, o, a, i, l) {
	"use strict";
	function e(e) {
		if (e == null) return null;
		switch (e) {
			case o("WAArmadilloXMA.pb").EXTENDED_CONTENT_MESSAGE_EXTENDED_CONTENT_TYPE.FB_FEED_SHARE: return r("LSXmaContentType").FB_FEED_SHARE;
			case o("WAArmadilloXMA.pb").EXTENDED_CONTENT_MESSAGE_EXTENDED_CONTENT_TYPE.FB_STORY_REPLY: return r("LSXmaContentType").FB_STORY_REPLY;
			case o("WAArmadilloXMA.pb").EXTENDED_CONTENT_MESSAGE_EXTENDED_CONTENT_TYPE.FB_STORY_SHARE: return r("LSXmaContentType").FB_STORY_SHARE;
			case o("WAArmadilloXMA.pb").EXTENDED_CONTENT_MESSAGE_EXTENDED_CONTENT_TYPE.FB_STORY_MENTION: return r("LSXmaContentType").FB_STORY_MENTION;
			case o("WAArmadilloXMA.pb").EXTENDED_CONTENT_MESSAGE_EXTENDED_CONTENT_TYPE.FB_FEED_VIDEO_SHARE: return r("LSXmaContentType").FB_FEED_VIDEO_SHARE;
			case o("WAArmadilloXMA.pb").EXTENDED_CONTENT_MESSAGE_EXTENDED_CONTENT_TYPE.FB_GAMING_CUSTOM_UPDATE: return r("LSXmaContentType").FB_GAMING_CUSTOM_UPDATE;
			case o("WAArmadilloXMA.pb").EXTENDED_CONTENT_MESSAGE_EXTENDED_CONTENT_TYPE.FB_PRODUCER_STORY_REPLY: return r("LSXmaContentType").FB_PRODUCER_STORY_REPLY;
			case o("WAArmadilloXMA.pb").EXTENDED_CONTENT_MESSAGE_EXTENDED_CONTENT_TYPE.FB_EVENT: return r("LSXmaContentType").FB_EVENT;
			case o("WAArmadilloXMA.pb").EXTENDED_CONTENT_MESSAGE_EXTENDED_CONTENT_TYPE.FB_FEED_POST_PRIVATE_REPLY: return r("LSXmaContentType").FB_FEED_POST_PRIVATE_REPLY;
			case o("WAArmadilloXMA.pb").EXTENDED_CONTENT_MESSAGE_EXTENDED_CONTENT_TYPE.MSG_HIGHLIGHTS_TAB_FRIEND_UPDATES_REPLY: return r("LSXmaContentType").MSG_HIGHLIGHTS_TAB_FRIEND_UPDATES_REPLY;
			case o("WAArmadilloXMA.pb").EXTENDED_CONTENT_MESSAGE_EXTENDED_CONTENT_TYPE.FB_SHORT: return r("LSXmaContentType").FB_SHORT;
			case o("WAArmadilloXMA.pb").EXTENDED_CONTENT_MESSAGE_EXTENDED_CONTENT_TYPE.MSG_LOCATION_SHARING: return r("LSXmaContentType").MSG_LOCATION_SHARING;
			case o("WAArmadilloXMA.pb").EXTENDED_CONTENT_MESSAGE_EXTENDED_CONTENT_TYPE.MSG_LOCATION_SHARING_V2: return r("LSXmaContentType").MSG_LOCATION_SHARING_V2;
			case o("WAArmadilloXMA.pb").EXTENDED_CONTENT_MESSAGE_EXTENDED_CONTENT_TYPE.FB_POST_MENTION: return r("LSXmaContentType").FB_POST_MENTION;
			case o("WAArmadilloXMA.pb").EXTENDED_CONTENT_MESSAGE_EXTENDED_CONTENT_TYPE.FB_FEED_POST_REACTION_REPLY: return r("LSXmaContentType").FB_FEED_POST_REACTION_REPLY;
			case o("WAArmadilloXMA.pb").EXTENDED_CONTENT_MESSAGE_EXTENDED_CONTENT_TYPE.MSG_CONTACT: return r("LSXmaContentType").MSG_CONTACT;
			case o("WAArmadilloXMA.pb").EXTENDED_CONTENT_MESSAGE_EXTENDED_CONTENT_TYPE.MSG_AI_CONTACT: return r("LSXmaContentType").MSG_AI_CONTACT;
			case o("WAArmadilloXMA.pb").EXTENDED_CONTENT_MESSAGE_EXTENDED_CONTENT_TYPE.MSG_MEMORIES_SHARE: return r("LSXmaContentType").MSG_MEMORIES_SHARE;
			case o("WAArmadilloXMA.pb").EXTENDED_CONTENT_MESSAGE_EXTENDED_CONTENT_TYPE.MSG_MUSIC_STICKER: return r("gkx")("13570") ? r("LSXmaContentType").MSG_MUSIC_STICKER : null;
			case o("WAArmadilloXMA.pb").EXTENDED_CONTENT_MESSAGE_EXTENDED_CONTENT_TYPE.MSG_PHONE_NUMBER: return r("LSXmaContentType").MSG_PHONE_NUMBER;
			case o("WAArmadilloXMA.pb").EXTENDED_CONTENT_MESSAGE_EXTENDED_CONTENT_TYPE.MSG_EXTERNAL_LINK_SHARE: return r("LSXmaContentType").MSG_EXTERNAL_LINK_SHARE;
			case o("WAArmadilloXMA.pb").EXTENDED_CONTENT_MESSAGE_EXTENDED_CONTENT_TYPE.MSG_PRIVATE_XMA: return r("LSXmaContentType").MSG_PRIVATE_XMA;
			case o("WAArmadilloXMA.pb").EXTENDED_CONTENT_MESSAGE_EXTENDED_CONTENT_TYPE.RTC_AUDIO_CALL: return r("LSXmaContentType").RTC_AUDIO_CALL;
			case o("WAArmadilloXMA.pb").EXTENDED_CONTENT_MESSAGE_EXTENDED_CONTENT_TYPE.RTC_ONGOING_AUDIO_CALL: return r("gkx")("10883") ? r("LSXmaContentType").RTC_ONGOING_AUDIO_CALL : null;
			case o("WAArmadilloXMA.pb").EXTENDED_CONTENT_MESSAGE_EXTENDED_CONTENT_TYPE.RTC_VIDEO_CALL: return r("LSXmaContentType").RTC_VIDEO_CALL;
			case o("WAArmadilloXMA.pb").EXTENDED_CONTENT_MESSAGE_EXTENDED_CONTENT_TYPE.RTC_ONGOING_VIDEO_CALL: return r("gkx")("10883") ? r("LSXmaContentType").RTC_ONGOING_VIDEO_CALL : null;
			case o("WAArmadilloXMA.pb").EXTENDED_CONTENT_MESSAGE_EXTENDED_CONTENT_TYPE.RTC_MISSED_AUDIO_CALL: return r("LSXmaContentType").RTC_MISSED_AUDIO_CALL;
			case o("WAArmadilloXMA.pb").EXTENDED_CONTENT_MESSAGE_EXTENDED_CONTENT_TYPE.RTC_MISSED_VIDEO_CALL: return r("LSXmaContentType").RTC_MISSED_VIDEO_CALL;
			case o("WAArmadilloXMA.pb").EXTENDED_CONTENT_MESSAGE_EXTENDED_CONTENT_TYPE.FB_PROFILE_DIRECTORY_ITEM: return r("LSXmaContentType").FB_PROFILE_DIRECTORY_ITEM;
			case o("WAArmadilloXMA.pb").EXTENDED_CONTENT_MESSAGE_EXTENDED_CONTENT_TYPE.MSG_MANUS_GROWTH_REFERRAL: return r("LSXmaContentType").MSG_MANUS_GROWTH_REFERRAL;
			case o("WAArmadilloXMA.pb").EXTENDED_CONTENT_MESSAGE_EXTENDED_CONTENT_TYPE.MSG_SOCIAL_CUE_MEMORIES: return r("LSXmaContentType").MSG_SOCIAL_CUE_MEMORIES;
			default: return null;
		}
	}
	l.convertExtendedContentTypeToLSXmaContentType = e;
}), 98);
