__d("MAWConvertXMATargetTypeToExtendedContentTargetType", [
	"EchoMessageXMAFieldUtils",
	"WAArmadilloXMA.pb",
	"WALogger"
], (function(t, n, r, o, a, i, l) {
	"use strict";
	var e;
	function s(t) {
		switch (t) {
			case o("EchoMessageXMAFieldUtils").XMAContentType.IG_STORY_PHOTO_MENTION: return o("WAArmadilloXMA.pb").EXTENDED_CONTENT_MESSAGE_EXTENDED_CONTENT_TYPE.IG_STORY_PHOTO_MENTION;
			case o("EchoMessageXMAFieldUtils").XMAContentType.IG_SINGLE_IMAGE_POST_SHARE: return o("WAArmadilloXMA.pb").EXTENDED_CONTENT_MESSAGE_EXTENDED_CONTENT_TYPE.IG_SINGLE_IMAGE_POST_SHARE;
			case o("EchoMessageXMAFieldUtils").XMAContentType.IG_MULTIPOST_SHARE: return o("WAArmadilloXMA.pb").EXTENDED_CONTENT_MESSAGE_EXTENDED_CONTENT_TYPE.IG_MULTIPOST_SHARE;
			case o("EchoMessageXMAFieldUtils").XMAContentType.IG_SINGLE_VIDEO_POST_SHARE: return o("WAArmadilloXMA.pb").EXTENDED_CONTENT_MESSAGE_EXTENDED_CONTENT_TYPE.IG_SINGLE_VIDEO_POST_SHARE;
			case o("EchoMessageXMAFieldUtils").XMAContentType.IG_STORY_PHOTO_SHARE: return o("WAArmadilloXMA.pb").EXTENDED_CONTENT_MESSAGE_EXTENDED_CONTENT_TYPE.IG_STORY_PHOTO_SHARE;
			case o("EchoMessageXMAFieldUtils").XMAContentType.IG_STORY_VIDEO_SHARE: return o("WAArmadilloXMA.pb").EXTENDED_CONTENT_MESSAGE_EXTENDED_CONTENT_TYPE.IG_STORY_VIDEO_SHARE;
			case o("EchoMessageXMAFieldUtils").XMAContentType.IG_CLIPS_SHARE: return o("WAArmadilloXMA.pb").EXTENDED_CONTENT_MESSAGE_EXTENDED_CONTENT_TYPE.IG_CLIPS_SHARE;
			case o("EchoMessageXMAFieldUtils").XMAContentType.IG_IGTV_SHARE: return o("WAArmadilloXMA.pb").EXTENDED_CONTENT_MESSAGE_EXTENDED_CONTENT_TYPE.IG_IGTV_SHARE;
			case o("EchoMessageXMAFieldUtils").XMAContentType.IG_SHOP_SHARE: return o("WAArmadilloXMA.pb").EXTENDED_CONTENT_MESSAGE_EXTENDED_CONTENT_TYPE.IG_SHOP_SHARE;
			case o("EchoMessageXMAFieldUtils").XMAContentType.IG_PROFILE_SHARE: return o("WAArmadilloXMA.pb").EXTENDED_CONTENT_MESSAGE_EXTENDED_CONTENT_TYPE.IG_PROFILE_SHARE;
			case o("EchoMessageXMAFieldUtils").XMAContentType.IG_STORY_PHOTO_HIGHLIGHT_SHARE: return o("WAArmadilloXMA.pb").EXTENDED_CONTENT_MESSAGE_EXTENDED_CONTENT_TYPE.IG_STORY_PHOTO_HIGHLIGHT_SHARE;
			case o("EchoMessageXMAFieldUtils").XMAContentType.IG_STORY_VIDEO_HIGHLIGHT_SHARE: return o("WAArmadilloXMA.pb").EXTENDED_CONTENT_MESSAGE_EXTENDED_CONTENT_TYPE.IG_STORY_VIDEO_HIGHLIGHT_SHARE;
			case o("EchoMessageXMAFieldUtils").XMAContentType.IG_STORY_REPLY: return o("WAArmadilloXMA.pb").EXTENDED_CONTENT_MESSAGE_EXTENDED_CONTENT_TYPE.IG_STORY_REPLY;
			case o("EchoMessageXMAFieldUtils").XMAContentType.IG_STORY_REACTION: return o("WAArmadilloXMA.pb").EXTENDED_CONTENT_MESSAGE_EXTENDED_CONTENT_TYPE.IG_STORY_REACTION;
			case o("EchoMessageXMAFieldUtils").XMAContentType.FB_FEED_SHARE: return o("WAArmadilloXMA.pb").EXTENDED_CONTENT_MESSAGE_EXTENDED_CONTENT_TYPE.FB_FEED_SHARE;
			case o("EchoMessageXMAFieldUtils").XMAContentType.FB_STORY_REPLY: return o("WAArmadilloXMA.pb").EXTENDED_CONTENT_MESSAGE_EXTENDED_CONTENT_TYPE.FB_STORY_REPLY;
			case o("EchoMessageXMAFieldUtils").XMAContentType.FB_STORY_SHARE: return o("WAArmadilloXMA.pb").EXTENDED_CONTENT_MESSAGE_EXTENDED_CONTENT_TYPE.FB_STORY_SHARE;
			case o("EchoMessageXMAFieldUtils").XMAContentType.FB_STORY_MENTION: return o("WAArmadilloXMA.pb").EXTENDED_CONTENT_MESSAGE_EXTENDED_CONTENT_TYPE.FB_STORY_MENTION;
			case o("EchoMessageXMAFieldUtils").XMAContentType.FB_FEED_VIDEO_SHARE: return o("WAArmadilloXMA.pb").EXTENDED_CONTENT_MESSAGE_EXTENDED_CONTENT_TYPE.FB_FEED_VIDEO_SHARE;
			case o("EchoMessageXMAFieldUtils").XMAContentType.FB_GAMING_CUSTOM_UPDATE: return o("WAArmadilloXMA.pb").EXTENDED_CONTENT_MESSAGE_EXTENDED_CONTENT_TYPE.FB_GAMING_CUSTOM_UPDATE;
			case o("EchoMessageXMAFieldUtils").XMAContentType.FB_PRODUCER_STORY_REPLY: return o("WAArmadilloXMA.pb").EXTENDED_CONTENT_MESSAGE_EXTENDED_CONTENT_TYPE.FB_PRODUCER_STORY_REPLY;
			case o("EchoMessageXMAFieldUtils").XMAContentType.MSG_EXTERNAL_LINK_SHARE: return o("WAArmadilloXMA.pb").EXTENDED_CONTENT_MESSAGE_EXTENDED_CONTENT_TYPE.MSG_EXTERNAL_LINK_SHARE;
			case o("EchoMessageXMAFieldUtils").XMAContentType.RTC_AUDIO_CALL: return o("WAArmadilloXMA.pb").EXTENDED_CONTENT_MESSAGE_EXTENDED_CONTENT_TYPE.RTC_AUDIO_CALL;
			case o("EchoMessageXMAFieldUtils").XMAContentType.RTC_VIDEO_CALL: return o("WAArmadilloXMA.pb").EXTENDED_CONTENT_MESSAGE_EXTENDED_CONTENT_TYPE.RTC_VIDEO_CALL;
			case o("EchoMessageXMAFieldUtils").XMAContentType.RTC_MISSED_AUDIO_CALL: return o("WAArmadilloXMA.pb").EXTENDED_CONTENT_MESSAGE_EXTENDED_CONTENT_TYPE.RTC_MISSED_AUDIO_CALL;
			case o("EchoMessageXMAFieldUtils").XMAContentType.RTC_MISSED_VIDEO_CALL: return o("WAArmadilloXMA.pb").EXTENDED_CONTENT_MESSAGE_EXTENDED_CONTENT_TYPE.RTC_MISSED_VIDEO_CALL;
			case o("EchoMessageXMAFieldUtils").XMAContentType.RTC_GROUP_AUDIO_CALL: return o("WAArmadilloXMA.pb").EXTENDED_CONTENT_MESSAGE_EXTENDED_CONTENT_TYPE.RTC_GROUP_AUDIO_CALL;
			case o("EchoMessageXMAFieldUtils").XMAContentType.RTC_GROUP_VIDEO_CALL: return o("WAArmadilloXMA.pb").EXTENDED_CONTENT_MESSAGE_EXTENDED_CONTENT_TYPE.RTC_GROUP_VIDEO_CALL;
			case o("EchoMessageXMAFieldUtils").XMAContentType.FB_EVENT: return o("WAArmadilloXMA.pb").EXTENDED_CONTENT_MESSAGE_EXTENDED_CONTENT_TYPE.FB_EVENT;
			case o("EchoMessageXMAFieldUtils").XMAContentType.FB_SHORT: return o("WAArmadilloXMA.pb").EXTENDED_CONTENT_MESSAGE_EXTENDED_CONTENT_TYPE.FB_SHORT;
			case o("EchoMessageXMAFieldUtils").XMAContentType.MSG_RECEIVER_FETCH: return o("WAArmadilloXMA.pb").EXTENDED_CONTENT_MESSAGE_EXTENDED_CONTENT_TYPE.MSG_RECEIVER_FETCH;
			case o("EchoMessageXMAFieldUtils").XMAContentType.MSG_LOCATION_SHARING: return o("WAArmadilloXMA.pb").EXTENDED_CONTENT_MESSAGE_EXTENDED_CONTENT_TYPE.MSG_LOCATION_SHARING;
			case o("EchoMessageXMAFieldUtils").XMAContentType.MSG_LOCATION_SHARING_V2: return o("WAArmadilloXMA.pb").EXTENDED_CONTENT_MESSAGE_EXTENDED_CONTENT_TYPE.MSG_LOCATION_SHARING_V2;
			case o("EchoMessageXMAFieldUtils").XMAContentType.MSG_MEMORIES_SHARE: return o("WAArmadilloXMA.pb").EXTENDED_CONTENT_MESSAGE_EXTENDED_CONTENT_TYPE.MSG_MEMORIES_SHARE;
			case o("EchoMessageXMAFieldUtils").XMAContentType.MSG_MANUS_GROWTH_REFERRAL: return o("WAArmadilloXMA.pb").EXTENDED_CONTENT_MESSAGE_EXTENDED_CONTENT_TYPE.MSG_MANUS_GROWTH_REFERRAL;
			case o("EchoMessageXMAFieldUtils").XMAContentType.FB_FEED_POST_REACTION_REPLY: return o("WAArmadilloXMA.pb").EXTENDED_CONTENT_MESSAGE_EXTENDED_CONTENT_TYPE.FB_FEED_POST_REACTION_REPLY;
			default: return o("WALogger").ERROR(e || (e = babelHelpers.taggedTemplateLiteralLoose(["[labyrinth_web] Not a valid xmaTargetType: ", ""])), t), o("WAArmadilloXMA.pb").EXTENDED_CONTENT_MESSAGE_EXTENDED_CONTENT_TYPE.MSG_EXTERNAL_LINK_SHARE;
		}
	}
	l.convertXMATargetTypeToExtendedContentTargetType = s;
}), 98);
