__d("MAWLocalizationUtils", [
	"MAWAckLevel",
	"MAWLocalizationType",
	"MAWMsgType",
	"WAJids",
	"WATimeUtils"
], (function(t, n, r, o, a, i, l) {
	"use strict";
	var e, s = new Set([
		(e = o("MAWLocalizationType")).LOCALIZATION_TYPE.CURRENT_USER_CREATED_POLL,
		e.LOCALIZATION_TYPE.PARTICIPANT_CREATED_POLL,
		e.LOCALIZATION_TYPE.CURRENT_USER_ADDED_POLL_OPTION,
		e.LOCALIZATION_TYPE.PARTICIPANT_ADDED_POLL_OPTION,
		e.LOCALIZATION_TYPE.CURRENT_USER_ADDED_MULTIPLE_POLL_OPTIONS,
		e.LOCALIZATION_TYPE.PARTICIPANT_ADDED_MULTIPLE_POLL_OPTIONS,
		e.LOCALIZATION_TYPE.CURRENT_USER_ADDED_POLL_VOTE,
		e.LOCALIZATION_TYPE.PARTICIPANT_ADDED_POLL_VOTE,
		e.LOCALIZATION_TYPE.CURRENT_USER_ADDED_MULTIPLE_POLL_VOTES,
		e.LOCALIZATION_TYPE.PARTICIPANT_ADDED_MULTIPLE_POLL_VOTES,
		e.LOCALIZATION_TYPE.CURRENT_USER_REMOVED_POLL_VOTE,
		e.LOCALIZATION_TYPE.PARTICIPANT_REMOVED_POLL_VOTE,
		e.LOCALIZATION_TYPE.CURRENT_USER_REMOVED_MULTIPLE_POLL_VOTES,
		e.LOCALIZATION_TYPE.PARTICIPANT_REMOVED_MULTIPLE_POLL_VOTES,
		e.LOCALIZATION_TYPE.CURRENT_USER_MIXED_POLL_UPDATE,
		e.LOCALIZATION_TYPE.PARTICIPANT_MIXED_POLL_UPDATE,
		e.LOCALIZATION_TYPE.CURRENT_USER_CHANGED_POLL_VOTE,
		e.LOCALIZATION_TYPE.PARTICIPANT_CHANGED_POLL_VOTE,
		e.LOCALIZATION_TYPE.CURRENT_USER_CHANGED_MULTIPLE_POLL_VOTES,
		e.LOCALIZATION_TYPE.PARTICIPANT_CHANGED_MULTIPLE_POLL_VOTES,
		e.LOCALIZATION_TYPE.POLL_UNSENT_UPDATE
	]);
	function u(e, t, n, r, a, i) {
		return {
			ack: o("MAWAckLevel").ACK.sent,
			altIndex: a != null ? a : void 0,
			author: o("WAJids").AUTHOR_SYSTEM,
			externalId: n,
			msgContent: e,
			sortOrderMs: i,
			threadJid: t,
			ts: r != null ? r : o("WATimeUtils").unixTime(),
			type: o("MAWMsgType").MSG_TYPE.ADMIN
		};
	}
	function c(e) {
		if (s.has(e)) return !0;
		switch (e) {
			case o("MAWLocalizationType").LOCALIZATION_TYPE.CURRENT_USER_NAMED_GROUP:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.PARTICIPANT_NAMED_GROUP:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.UNKNOWN_USER_NAMED_GROUP:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.CURRENT_USER_ADDED_ONE_PARTICIPANT:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.CURRENT_USER_ADDED_TWO_PARTICIPANTS:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.CURRENT_USER_ADDED_MORE_THAN_TWO_PARTICIPANTS:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.PARTICIPANT_ADDED_YOU:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.PARTICIPANT_ADDED_YOU_AND_ONE_USER:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.PARTICIPANT_ADDED_YOU_AND_MORE_THAN_ONE_USERS:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.PARTICIPANT_ADDED_ONE_USER:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.PARTICIPANT_ADDED_TWO_USER:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.PARTICIPANT_ADDED_MORE_THAN_TWO_USER:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.CURRENT_USER_REMOVED_ONE_PARTICIPANT:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.CURRENT_USER_REMOVED_TWO_PARTICIPANTS:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.CURRENT_USER_REMOVED_MORE_THAN_TWO_PARTICIPANTS:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.PARTICIPANT_REMOVED_YOU:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.PARTICIPANT_REMOVED_YOU_AND_ONE_USER:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.PARTICIPANT_REMOVED_YOU_AND_MORE_THAN_ONE_USERS:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.PARTICIPANT_REMOVED_ONE_USER:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.PARTICIPANT_REMOVED_TWO_USER:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.PARTICIPANT_REMOVED_MORE_THAN_TWO_USER:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.PARTICIPANT_LEFT_GROUP:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.CURRENT_USER_SELF_DEMOTED:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.CURRENT_USER_PROMOTED_PARTICIPANT:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.CURRENT_USER_DEMOTED_PARTICIPANT:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.CURRENT_USER_GOT_PROMOTED:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.CURRENT_USER_GOT_DEMOTED:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.PARTICIPANT_GOT_PROMOTED:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.PARTICIPANT_GOT_DEMOTED:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.PARTICIPANT_PROMOTED_YOU:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.PARTICIPANT_DEMOTED_YOU:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.PARTICIPANT_PROMOTED_PARTICIPANT:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.PARTICIPANT_SELF_DEMOTED:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.PARTICIPANT_DEMOTED_PARTICIPANT:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.CURRENT_USER_ADDED_DEVICE:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.PARTICIPANT_ADDED_DEVICE:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.CURRENT_USER_REMOVED_DEVICE:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.PARTICIPANT_REMOVED_DEVICE:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.CURRENT_USER_UPDATED_DEVICE:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.PARTICIPANT_UPDATED_DEVICE:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.CURRENT_USER_CUSTOMIZE_HOTLIKE:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.CURRENT_USER_CUSTOMIZE_NICKNAME:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.CURRENT_USER_CUSTOMIZE_THEME:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.CURRENT_USER_CUSTOMIZE_PHOTO:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.CURRENT_USER_PINNED_MESSAGE:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.CURRENT_USER_UNPINNED_MESSAGE:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.PARTICIPANT_CUSTOMIZE_HOTLIKE:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.PARTICIPANT_CUSTOMIZE_THEME:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.PARTICIPANT_CUSTOMIZE_PHOTO:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.PARTICIPANT_PINNED_MESSAGE:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.PARTICIPANT_UNPINNED_MESSAGE:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.PARTICIPANT_CUSTOMIZE_PARTICIPANT_NICKNAME:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.PARTICIPANT_CLEAR_PARTICIPANT_NICKNAME:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.PARTICIPANT_CUSTOMIZE_CURRENT_USER_NICKNAME:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.CURRENT_USER_SET_OWN_NICKNAME:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.CURRENT_USER_CLEAR_OWN_NICKNAME:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.CURRENT_USER_CLEAR_PARTICIPANT_NICKNAME:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.PARTICIPANT_SET_OWN_NICKNAME:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.PARTICIPANT_CLEAR_OWN_NICKNAME:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.PARTICIPANT_CLEAR_CURRENT_USER_NICKNAME:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.PARTICIPANT_EPHEMERAL_SETTING_TURNED_ON_MINUTES:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.PARTICIPANT_EPHEMERAL_SETTING_CHANGE_MINUTES:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.PARTICIPANT_EPHEMERAL_SETTING_TURNED_ON_HOURS:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.PARTICIPANT_EPHEMERAL_SETTING_CHANGE_HOURS:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.PARTICIPANT_EPHEMERAL_SETTING_TURNED_ON_DAYS:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.PARTICIPANT_EPHEMERAL_SETTING_CHANGE_DAYS:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.PARTICIPANT_EPHEMERAL_SETTING_TURNED_OFF:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.PARTICIPANT_EPHEMERAL_SETTING_TURNED_ON_SECONDS:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.PARTICIPANT_EPHEMERAL_SETTING_CHANGE_SECONDS:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.PARTICIPANT_EPHEMERAL_TAKE_SCREENSHOT:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.PARTICIPANT_EPHEMERAL_RECORD_SCREEN:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.CURRENT_USER_SET_ADD_MODE_ADMIN_ONLY:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.CURRENT_USER_SET_ADD_MODE_ALL_MEMBERS:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.PARTICIPANT_SET_ADD_MODE_ADMIN_ONLY:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.PARTICIPANT_SET_ADD_MODE_ALL_MEMBERS:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.SERVER_SET_ADD_MODE_ADMIN_ONLY:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.SERVER_SET_ADD_MODE_ALL_MEMBERS:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.E2EE_THREAD_UK_OSA_ADMIN_MESSAGE:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.CURRENT_USER_LIMIT_SHARING_DISABLED:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.CURRENT_USER_LIMIT_SHARING_ENABLED:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.PARTICIPANT_LIMIT_SHARING_DISABLED:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.PARTICIPANT_LIMIT_SHARING_ENABLED:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.DUAL_THREAD_CUTOVER_ADMIN_MESSAGE_OTHER_USER_NAME_UNKNOWN:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.DUAL_THREAD_CUTOVER_ADMIN_MESSAGE_SELF_THREAD:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.DUAL_THREAD_CUTOVER_ADMIN_MESSAGE_WITH_OTHER_USER_NAME: return !0;
		}
		return !1;
	}
	function d(e) {
		switch (e) {
			case o("MAWLocalizationType").LOCALIZATION_TYPE.CURRENT_USER_ADDED_DEVICE:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.CURRENT_USER_REMOVED_DEVICE:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.CURRENT_USER_UPDATED_DEVICE:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.PARTICIPANT_ADDED_DEVICE:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.PARTICIPANT_REMOVED_DEVICE:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.PARTICIPANT_UPDATED_DEVICE: return !0;
		}
		return !1;
	}
	function m(e) {
		switch (e) {
			case o("MAWLocalizationType").LOCALIZATION_TYPE.CURRENT_USER_ADDED_ONE_PARTICIPANT:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.CURRENT_USER_ADDED_TWO_PARTICIPANTS:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.CURRENT_USER_ADDED_MORE_THAN_TWO_PARTICIPANTS:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.PARTICIPANT_ADDED_YOU:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.PARTICIPANT_ADDED_YOU_AND_ONE_USER:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.PARTICIPANT_ADDED_YOU_AND_MORE_THAN_ONE_USERS:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.PARTICIPANT_ADDED_ONE_USER:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.PARTICIPANT_ADDED_TWO_USER:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.PARTICIPANT_ADDED_MORE_THAN_TWO_USER:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.UNKNOWN_USER_ADDED_YOU:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.UNKNOWN_USER_ADDED_YOU_AND_ONE_USER:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.UNKNOWN_USER_ADDED_YOU_AND_MORE_THAN_ONE_USER:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.UNKNOWN_USER_ADDED_ONE_USER:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.UNKNOWN_USER_ADDED_TWO_USER:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.UNKNOWN_USER_ADDED_MORE_THAN_TWO_USER:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.CURRENT_USER_REMOVED_ONE_PARTICIPANT:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.CURRENT_USER_REMOVED_TWO_PARTICIPANTS:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.CURRENT_USER_REMOVED_MORE_THAN_TWO_PARTICIPANTS:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.PARTICIPANT_REMOVED_YOU:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.PARTICIPANT_REMOVED_YOU_AND_ONE_USER:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.PARTICIPANT_REMOVED_YOU_AND_MORE_THAN_ONE_USERS:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.PARTICIPANT_REMOVED_ONE_USER:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.PARTICIPANT_REMOVED_TWO_USER:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.PARTICIPANT_REMOVED_MORE_THAN_TWO_USER:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.UNKNOWN_USER_REMOVED_YOU:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.UNKNOWN_USER_REMOVED_YOU_AND_ONE_USER:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.UNKNOWN_USER_REMOVED_YOU_AND_MORE_THAN_ONE_USER:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.UNKNOWN_USER_REMOVED_ONE_USER:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.UNKNOWN_USER_REMOVED_TWO_USER:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.UNKNOWN_USER_REMOVED_MORE_THAN_TWO_USER:
			case o("MAWLocalizationType").LOCALIZATION_TYPE.PARTICIPANT_LEFT_GROUP: return !0;
		}
		return !1;
	}
	l.buildUnstoredDbAdminMsg = u, l.isAdminMsgNormalized = c, l.isDeviceChangeAdminMsg = d, l.isParticipantChangeAdminMsg = m;
}), 98);
