__d("MAWMsgActionType", [], (function(t, n, r, o, a, i) {
	"use strict";
	var e = {
		DELETE_FOR_ME: "DELETE_FOR_ME",
		NO_ACTION: "NO_ACTION",
		REVOKE: "REVOKE",
		UPDATE_CIPHERTEXT: "UPDATE_CIPHERTEXT",
		UPDATE_CIPHERTEXT_WITH_ASSOCIATED: "UPDATE_CIPHERTEXT_WITH_ASSOCIATED",
		WRITE: "WRITE",
		WRITE_WITH_ASSOCIATED: "WRITE_WITH_ASSOCIATED"
	};
	i.MSG_ACTION = e;
}), 66);
