__d("MAWParseXMAFBConfig", [
	"FBLogger",
	"MAWIsFbProfileDirectoryItemXmaEnabled",
	"WAArmadilloXMA.pb",
	"gkx"
], (function(t, n, r, o, a, i, l) {
	"use strict";
	var e, s = new Set([
		(e = o("WAArmadilloXMA.pb")).EXTENDED_CONTENT_MESSAGE_EXTENDED_CONTENT_TYPE.FB_FEED_SHARE,
		e.EXTENDED_CONTENT_MESSAGE_EXTENDED_CONTENT_TYPE.FB_SHORT,
		e.EXTENDED_CONTENT_MESSAGE_EXTENDED_CONTENT_TYPE.FB_STORY_SHARE,
		e.EXTENDED_CONTENT_MESSAGE_EXTENDED_CONTENT_TYPE.FB_STORY_REPLY,
		e.EXTENDED_CONTENT_MESSAGE_EXTENDED_CONTENT_TYPE.FB_GAMING_CUSTOM_UPDATE,
		e.EXTENDED_CONTENT_MESSAGE_EXTENDED_CONTENT_TYPE.MSG_EXTERNAL_LINK_SHARE,
		e.EXTENDED_CONTENT_MESSAGE_EXTENDED_CONTENT_TYPE.RTC_AUDIO_CALL,
		e.EXTENDED_CONTENT_MESSAGE_EXTENDED_CONTENT_TYPE.RTC_VIDEO_CALL,
		e.EXTENDED_CONTENT_MESSAGE_EXTENDED_CONTENT_TYPE.RTC_MISSED_AUDIO_CALL,
		e.EXTENDED_CONTENT_MESSAGE_EXTENDED_CONTENT_TYPE.RTC_MISSED_VIDEO_CALL,
		e.EXTENDED_CONTENT_MESSAGE_EXTENDED_CONTENT_TYPE.RTC_GROUP_AUDIO_CALL,
		e.EXTENDED_CONTENT_MESSAGE_EXTENDED_CONTENT_TYPE.RTC_GROUP_VIDEO_CALL,
		e.EXTENDED_CONTENT_MESSAGE_EXTENDED_CONTENT_TYPE.FB_FEED_POST_PRIVATE_REPLY,
		e.EXTENDED_CONTENT_MESSAGE_EXTENDED_CONTENT_TYPE.FB_FEED_POST_REACTION_REPLY,
		e.EXTENDED_CONTENT_MESSAGE_EXTENDED_CONTENT_TYPE.MSG_HIGHLIGHTS_TAB_FRIEND_UPDATES_REPLY,
		e.EXTENDED_CONTENT_MESSAGE_EXTENDED_CONTENT_TYPE.MSG_HIGHLIGHTS_TAB_LOCAL_EVENT_REPLY,
		e.EXTENDED_CONTENT_MESSAGE_EXTENDED_CONTENT_TYPE.FB_EVENT,
		e.EXTENDED_CONTENT_MESSAGE_EXTENDED_CONTENT_TYPE.FB_PRODUCER_STORY_REPLY,
		e.EXTENDED_CONTENT_MESSAGE_EXTENDED_CONTENT_TYPE.FB_STORY_MENTION,
		e.EXTENDED_CONTENT_MESSAGE_EXTENDED_CONTENT_TYPE.FB_PRODUCER_STORY_REPLY,
		e.EXTENDED_CONTENT_MESSAGE_EXTENDED_CONTENT_TYPE.MSG_RECEIVER_FETCH,
		e.EXTENDED_CONTENT_MESSAGE_EXTENDED_CONTENT_TYPE.MSG_CONTACT,
		e.EXTENDED_CONTENT_MESSAGE_EXTENDED_CONTENT_TYPE.MSG_AI_CONTACT,
		e.EXTENDED_CONTENT_MESSAGE_EXTENDED_CONTENT_TYPE.MSG_LOCATION_SHARING_V2,
		e.EXTENDED_CONTENT_MESSAGE_EXTENDED_CONTENT_TYPE.MSG_LOCATION_SHARING,
		e.EXTENDED_CONTENT_MESSAGE_EXTENDED_CONTENT_TYPE.FB_POST_MENTION,
		e.EXTENDED_CONTENT_MESSAGE_EXTENDED_CONTENT_TYPE.MSG_MEMORIES_SHARE,
		e.EXTENDED_CONTENT_MESSAGE_EXTENDED_CONTENT_TYPE.MSG_MANUS_GROWTH_REFERRAL,
		e.EXTENDED_CONTENT_MESSAGE_EXTENDED_CONTENT_TYPE.MSG_PHONE_NUMBER,
		e.EXTENDED_CONTENT_MESSAGE_EXTENDED_CONTENT_TYPE.MSG_SOCIAL_CUE_MEMORIES
	]);
	function u(e) {
		var t = e.fbTargetType;
		if (t != null && s.has(t)) return !0;
		switch (t) {
			case o("WAArmadilloXMA.pb").EXTENDED_CONTENT_MESSAGE_EXTENDED_CONTENT_TYPE.RTC_ONGOING_AUDIO_CALL:
			case o("WAArmadilloXMA.pb").EXTENDED_CONTENT_MESSAGE_EXTENDED_CONTENT_TYPE.RTC_ONGOING_VIDEO_CALL: return r("gkx")("10883");
			case o("WAArmadilloXMA.pb").EXTENDED_CONTENT_MESSAGE_EXTENDED_CONTENT_TYPE.GEN_AI_RICH_RESPONSE: return !0;
			case o("WAArmadilloXMA.pb").EXTENDED_CONTENT_MESSAGE_EXTENDED_CONTENT_TYPE.MSG_PRIVATE_XMA: return r("gkx")("21807");
			case o("WAArmadilloXMA.pb").EXTENDED_CONTENT_MESSAGE_EXTENDED_CONTENT_TYPE.FB_PROFILE_DIRECTORY_ITEM: return o("MAWIsFbProfileDirectoryItemXmaEnabled").isFbProfileDirectoryItemXmaEnabled();
			case o("WAArmadilloXMA.pb").EXTENDED_CONTENT_MESSAGE_EXTENDED_CONTENT_TYPE.MSG_MUSIC_STICKER: return r("gkx")("13570");
			default: return r("FBLogger")("maw_db").mustfix("MAWParseXMAFBConfig encountered an unknown unsupported XMA type: %s", String(t)), !1;
		}
	}
	l.FB_FULLY_SUPPORTED_TARGET_TYPES = s, l.isFBSupportedTargetType = u;
}), 98);
