__d("WAFlowsComponentConstants", [], (function(t, n, r, o, a, i) {
	"use strict";
	var e = 20, l = 150, s = 80, u = s, c = 80, d = 600, m = s, p = 80, _ = 80, f = 4096, g = 4096, h = 30, y = 300, C = 200, b = 100, v = 80, S = 20, R = 80, L = 300, E = 20, k = 2, I = 20, T = 40, D = s, x = e, $ = s, P = 80, N = 300, M = {
		BRANDING: 1,
		DROPDOWN_LABEL_ANDROID: 1,
		DROPDOWN_LABEL_IOS: 2,
		DROPDOWN_VALUE: 1,
		MEDIA_UPLOAD_NAME: 1,
		NAVBAR_CLOSE: 1,
		NAVBAR_TITLE: 1,
		SELECT_LIST_GROUP_LABEL: 3,
		SELECT_LIST_GROUP_DESCRIPTION: 8,
		SELECT_LIST_OPTION_TITLE: 2,
		SELECT_LIST_OPTION_DESCRIPTION: 3,
		SELECT_LIST_OPTION_METADATA: 2,
		SELECT_LIST_OPTION_METADATA_MULTILINE: 1,
		SNACKBAR_LABEL: 2,
		TEXT_HEADING_IOS: 4,
		TEXT_HEADING_ANDROID: 5,
		TEXT_SUBHEADING: 4,
		TEXT_BODY: 150,
		TEXT_CAPTION: 150,
		TEXT_INPUT_LABEL_ANDROID: 1,
		TEXT_INPUT_LABEL_WA_WEB: 1,
		TEXT_INPUT_LABEL_IOS: 2,
		TEXT_INPUT_LABEL_LARGE: 4,
		TEXT_INPUT_HELPER: 3,
		TEXTAREA_LABEL_ANDROID: 1,
		TEXTAREA_LABEL_WA_WEB: 1,
		TEXTAREA_LABEL_LARGE: 4,
		TEXTAREA_HELPER: 3,
		FOOTER_LABEL: 1
	}, w = new Set([
		"CheckboxGroup",
		"DatePicker",
		"Dropdown",
		"RadioButtonsGroup",
		"OptIn",
		"TextArea",
		"TextInput",
		"PhotoPicker",
		"DocumentPicker",
		"CalendarPicker",
		"ChipsSelector"
	]), A = new Set(["If", "Switch"]), F = 300, O = 360, B = 5, W = 64, q = 64, U = 80, V = 80, H = 72, G = 72, z = 72, j = 72, K = "USD", Q = 0, X = 0, Y = Number.MAX_SAFE_INTEGER, J = 600;
	i.TEXT_ENTRY_LABEL_MAX_LENGTH = e, i.TEXT_ENTRY_LABEL_LARGE_MAX_LENGTH = l, i.TEXT_INPUT_HELPER_TEXT_MAX_LENGTH = u, i.TEXT_INPUT_MAX_CHARS_DEFAULT = c, i.TEXT_AREA_MAX_CHARS_DEFAULT = d, i.TEXT_AREA_HELPER_TEXT_MAX_LENGTH = m, i.TEXT_HEADING_MAX_LENGTH = p, i.TEXT_SUBHEADING_MAX_LENGTH = _, i.TEXT_BODY_MAX_LENGTH = f, i.TEXT_CAPTION_MAX_LENGTH = g, i.EMBEDDED_LINK_MAX_LENGTH = h, i.OPT_IN_MAX_LENGTH = y, i.DROPDOWN_MAX_OPTIONS = C, i.DROPDOWN_MAX_OPTIONS_IMAGES = b, i.DROPDOWN_SELECT_LIST_OPTION_TITLE_MAX_LENGTH = v, i.DROPDOWN_SELECT_LIST_LABEL_MAX_LENGTH = S, i.CHIPS_SELECTOR_TITLE_MAX_LENGTH = R, i.CHIPS_SELECTOR_DESCRIPTION_MAX_LENGTH = L, i.CHIPS_SELECTOR_CHIP_LABEL_MAX_LENGTH = E, i.CHIPS_SELECTOR_MIN_ITEMS = k, i.CHIPS_SELECTOR_MAX_ITEMS = I, i.DATE_PICKER_LABEL_MAX_LENGTH = T, i.DATE_PICKER_HELPER_TEXT_MAX_LENGTH = D, i.CALENDAR_PICKER_MAX_LENGTH_LABEL = x, i.CALENDAR_PICKER_MAX_LENGTH_HELPER_TEXT = $, i.CALENDAR_PICKER_MAX_LENGTH_TITLE = P, i.CALENDAR_PICKER_MAX_LENGTH_DESCRIPTION = N, i.LABEL_LINES_MAX = M, i.FORM_COMPONENT_TYPES = w, i.CONDITIONAL_COMPONENT_TYPES = A, i.ITEM_DETAIL_DESCRIPTION_MAX_LENGTH = F, i.ITEM_DETAIL_IMAGE_DEFAULT_SIZE = O, i.ITEM_DETAIL_VARIANT_SELECTION_THRESHOLD = B, i.CATEGORY_LIST_IMAGE_HEIGHT = W, i.CATEGORY_LIST_IMAGE_WIDTH = q, i.ITEM_LIST_IMAGE_HEIGHT_IOS = U, i.ITEM_LIST_IMAGE_WIDTH_IOS = V, i.ITEM_LIST_IMAGE_HEIGHT_ANDROID = H, i.ITEM_LIST_IMAGE_WIDTH_ANDROID = G, i.CART_ITEM_LIST_IMAGE_HEIGHT = z, i.CART_ITEM_LIST_IMAGE_WIDTH = j, i.CART_DEFAULT_CURRENCY = K, i.QUANTITY_INPUT_INITIAL_VALUE = Q, i.QUANTITY_INPUT_MIN_VALUE = X, i.QUANTITY_INPUT_MAX_VALUE = Y, i.WAITING_THRESHOLD = J;
}), 66);
