__d("WDSNativeSelectListOptionConstant", [], (function(t, n, r, o, a, i) {
	"use strict";
	var e = 1, l = 20, s = 30, u = 80, c = 30, d = 20, m = 300, p = 56, _ = 72, f = 40;
	i.SELECT_LIST_MIN_OPTIONS = e, i.SELECT_LIST_MAX_OPTIONS = l, i.SELECT_LIST_LABEL_MAX_LENGTH = s, i.CBG_RBG_LIST_LABEL_MAX_LENGTH_v400 = u, i.SELECT_LIST_OPTION_TITLE_MAX_LENGTH = c, i.SELECT_LIST_OPTION_METADATA_MAX_LENGTH = d, i.SELECT_LIST_OPTION_DESCRIPTION_MAX_LENGTH = m, i.SELECT_LIST_OPTION_IMAGE_DEFAULT_SIZE = p, i.SELECT_LIST_OPTION_LARGE_IMAGE_DEFAULT_SIZE = _, i.SELECT_LIST_OPTION_COLOUR_DEFAULT_SIZE = f;
}), 66);
