#[repr(i64)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ABOUTCONSUMPTIONSURFACETYPE {
    ONEONONECHAT = 1,
    NEWMESSAGECONTACTS = 2,
    GROUPMEMBERSLIST = 3,
    COMMUNITYMEMBERSLIST = 4,
    FORWARDCONTACTS = 5,
    PROFILEINFOBOTTOMSHEET = 6,
    PROFILEINFO = 7,
    CONTACTSTABFAVORITES = 8,
    CONTACTSTABLIST = 9,
}