#[repr(i64)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ACTIONTARGET {
    REACHTAB = 0,
    GROWTHTAB = 1,
    FOLLOWERSTAB = 2,
    ACCOUNTSREACHEDINFOICON = 3,
    TOPREGIONSREACHINFOICON = 4,
    GROWTHCHARTINFOICON = 5,
    TOPREGIONSFOLLOWERSINFOICON = 6,
    HELPCENTERDATAUNAVAILABLEARTICLE = 7,
    HELPCENTERCHANNELMETRICSARTICLE = 8,
    WIDGETINFOICON = 9,
    TOTALFOLLOWERSINFOICON = 10,
}