#[repr(i64)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ADDMEMBERSENTRYPOINTTYPE {
    GROUPINFOACTIONBUTTON = 0,
    GROUPINFOCONTEXTMENU = 1,
    GROUPINFOMEMBERSLISTITEM = 2,
    GROUPCREATEDCONTEXTCARD = 3,
    GROUPADDEDCONTEXTCARD = 4,
    GROUPUSERJOINEDBYLINKCONTEXTCARD = 5,
    GROUPADDMEMBERENTRYPOINTOTHER = 6,
    GROUPCONVERSATIONOVERFLOWMENU = 7,
    GROUPADDMEMBERFROMSHAREDCONTACT = 8,
    GROUPADDMEMBERFROMEMPTYGROUPBANNER = 9,
    GROUPADDMEMBERFROMSHAREDNONCONTACT = 10,
    GROUPSAVECONTACTFROMSHAREDNONCONTACT = 11,
    GROUPADDMEMBERFROMCHATHEADER = 12,
    GROUPMENTIONPICKER = 13,
    COMMUNITYCONTEXTCARD = 14,
    COMMUNITYEMPTYSUBGROUP = 15,
    GROUPMEMBERSLISTADDBUTTON = 16,
}