#[repr(i64)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ANDROIDKEYSTORESTATETYPE {
    NOTAVAILABLE = 1,
    SELFTESTFAILURE = 2,
    ENCKEYREADFAILURE = 3,
    ENCKEYSTOREDUSED = 4,
    ENCKEYPLAINDELETED = 5,
    ENCKEYPLAINRECOVERED = 6,
}