#[repr(i64)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum BANNERSTATUSREASON {
    NOSIMILARCHANNELSFOUND = 0,
    NOTENOUGHSIMILARCHANNELS = 1,
    SIMILARCHANNELSFOUND = 2,
    CLOSETAP = 3,
    UNFOLLOWTAP = 4,
}