#[repr(i64)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum BOTBIZACTIONTYPE {
    BOTBIZCARDCLICK = 1,
    BOTBIZCARDMESSAGECLICK = 2,
    BOTBIZCARDVIEWAICLICK = 3,
    BOTBIZDEEPLINKCLICK = 4,
    BOTBIZNUXAPPEAR = 5,
    BOTBIZNUXDISMISS = 6,
    BOTBIZNUXSELECT = 7,
    BOTBIZINFOCHATCLICK = 8,
    BOTBIZNUXCONTINUECLICKED = 9,
    BOTBIZNUXDISMISSAUTOACCEPT = 10,
    BOTBIZNUXAPPEARMERGED = 11,
    BOTBIZNUXAPPEARNEW = 12,
    BOTBIZMESSAGESENDCLICK = 13,
    BOTBIZMESSAGERENDERED = 14,
}