#[repr(i64)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum BUSINESSPROFILEENTRYPOINT {
    REGISTRATION = 1,
    SETTINGS = 2,
    COMPLIANCE = 3,
    QUICKREPLYSMARTDEFAULT = 4,
    WAPAGES = 5,
    PROFILECOMPLETENESS = 6,
    DIRECTORYONBOARDING = 7,
    BUSINESSHOME = 8,
    DEEPLINK = 9,
    CHATBANNER = 10,
    BUSINESSSEARCH = 11,
    METAVERIFIED = 12,
    UNKNOWN = 13,
    QUICKREPLYSETTINGS = 14,
    EVENTCOMPOSER = 15,
}