#[repr(i64)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum BUSINESSTOOLSENTRYPOINTTYPE {
    ENTRYBANNER = 0,
    ENTRYREGISTRATIONONBOARDING = 1,
    ENTRYCONVERSATIONS = 2,
    ENTRYSETTINGS = 3,
    ENTRYDEEPLINK = 4,
    ENTRYSTATUSTABMENU = 5,
    ENTRYCALLSTABMENU = 6,
    ENTRYBUSINESSTOOLSTAB = 7,
}