#[repr(i64)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CHANNELDIRECTORYENTRYPOINT {
    SUGGESTEDCHANNELS = 1,
    FINDCHANNELSMENU = 2,
    DEEPLINK = 3,
    WAITLISTNOTIFICATION = 4,
    NUXBANNER = 5,
    FINDCHANNELSBUTTON = 6,
    UPDATESTABSEARCH = 7,
    EXPLORESECTIONHEADERBUTTON = 8,
    UPDATESTABSEARCHNULLSTATE = 9,
}