#[repr(i64)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CHANNELEVENTSURFACE {
    CHANNELUPDATESHOME = 1,
    CHANNELTHREAD = 2,
    CHANNELDIRECTORY = 3,
    CHANNELDIRECTORYSEARCH = 4,
    CHANNELPROFILE = 5,
    CHANNELUPDATESHOMESEARCH = 6,
    CHANNELDIRECTORYCATEGORIES = 7,
    CHANNELDIRECTORYCATEGORIESSEARCH = 8,
}