#[repr(i64)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CHATFILTERTYPES {
    NONE = 0,
    OTHERLABELS = 1,
    UNREAD = 2,
    GROUP = 3,
    BROADCASTLIST = 4,
    NEWCUSTOMER = 5,
    NEWORDER = 6,
    PENDINGPAYMENT = 7,
    PAID = 8,
    ORDERCOMPLETE = 9,
    CONTACT = 10,
    NONCONTACT = 11,
    PHOTOS = 12,
    GIFS = 13,
    LINKS = 14,
    VIDEOS = 15,
    DOCUMENTS = 16,
    AUDIOS = 17,
    ASSIGNEDTOYOU = 18,
    PERSONAL = 19,
    BUSINESS = 20,
    LABEL = 21,
    FAVORITES = 22,
    STICKERS = 23,
    COMMUNITY = 24,
    BUSINESSAI = 25,
    DRAFTS = 26,
    CAMPAIGNREPLIES = 27,
    BUSINESSFOLDER = 28,
}