#[repr(i64)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CHATLOCKACTIONTYPE {
    CHATINFOIMPRESSION = 0,
    LOCKCHATSCREENIMPRESSION = 1,
    AUTHINITIATED = 2,
    AUTHSUCCEEDED = 3,
    SETUPAUTHIMPRESSION = 4,
    ADDCHATLOCK = 5,
    REMOVECHATLOCK = 6,
    CLEARANDUNLOCKIMPRESSION = 7,
    CLEARANDUNLOCKSUCCESS = 8,
    CLEARANDUNLOCKFAILURE = 9,
    AUTHFAILURE = 10,
    BOTTOMSHEETIMPRESSION = 11,
    BOTTOMSHEETCONTINUECLICK = 12,
    BOTTOMSHEETLEARNMORECLICK = 13,
    FOLDEROPEN = 14,
    FORGOTSECRETCODE = 15,
    UNLOCKANDCLEARWARNING = 16,
    USESECRETCODEAUTH = 17,
}