#[repr(i64)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CHATACTIONENTRYPOINT {
    CONVERSATIONLIST = 1,
    CONTACTINFO = 2,
    GROUPINFO = 3,
    SEARCHLIST = 4,
    CONVERSATIONLISTBULKEDIT = 5,
    CONVERSATIONMENU = 6,
    WEBACTION = 7,
    SYSTEMNOTIFICATIONS = 8,
    SPAMFOLDER = 9,
    DEPENDENTMESSAGEREQUESTSFOLDER = 10,
    DEPENDENTCONVERSATIONMESAGEREQUEST = 11,
}