#[repr(i64)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CLIENTMESSAGESENDSTAGE {
    CLIENTRENDERED = 1,
    CLIENTSAVED = 2,
    CLIENTWRITTENWIRE = 3,
    CLIENTQUEUED = 4,
    CLIENTWAITINGTOENCRYPT = 5,
    CLIENTREADYTOSEND = 6,
    CLIENTENCRYPT = 7,
    CLIENTPREKEYSFETCH = 8,
}