#[repr(i64)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum COMPANIONINVITEORIGINTYPE {
    UNKNOWN = 0,
    CHATLISTSEARCH = 1,
    CONTACTPICKERLIST = 2,
    CONTACTPICKERSEARCH = 3,
    GROUPSCREATEPARTICIPANTSELECTOR = 4,
    GROUPSADDPARTICIPANTSELECTOR = 5,
    CONTACTEDITDRAWER = 6,
}