#[repr(i64)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum COMPANIONADDCONTACTSOURCE {
    CONTACTINFO = 0,
    VCARD = 1,
    CONTACTLIST = 2,
    NEWCHAT = 3,
    PHONENUMBERDIALER = 4,
    FMXCARD = 5,
    NEWCHATDRAWER = 6,
    CHATHEADER = 7,
    GROUPMEMBER = 8,
    CHATLISTGLOBALSEARCH = 9,
    SUSPICIOUSCHATBANNER = 10,
}