#[repr(i64)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CONSUMERBIZSURFACEENUM {
    SEARCHRESULTS = 0,
    BUSINESSPROFILE = 1,
    CONTACTCARD = 2,
    SHAREDIALOG = 3,
    CHATHEADER = 4,
    FMXCARD = 5,
    BLOCKEDCOMPOSER = 6,
    OFFBOARDEDBOTTOMSHEET = 7,
    CHATTHREAD = 8,
}