#[repr(i64)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CONTACTNOTIFICATIONSETTINGACTIONTYPE {
    MESSAGESMUTEALWAYS = 1,
    MESSAGESMUTE8H = 2,
    MESSAGESMUTE1W = 3,
    MESSAGESUNMUTE = 4,
    CALLSMUTEALWAYS = 5,
    CALLSMUTE8H = 6,
    CALLSMUTE1W = 7,
    CALLSUNMUTE = 8,
    CHANGEDMESSAGEALERTTONE = 9,
    CHANGEDMESSAGEVIBRATION = 10,
    CHANGEDCALLTONE = 11,
    CHANGEDCALLVIBRATION = 12,
    CHANGEDMESSAGENOTIFICATIONTHEME = 13,
    CHANGEDMESSAGEPOPUPNOTIFICATION = 14,
    CHANGEDMESSAGENOTIFICATIONPRIORITY = 15,
    STATUSESMUTE = 16,
    STATUSESUNMUTE = 17,
    MUTEMENTIONEVERYONEOFF = 18,
    MUTEMENTIONEVERYONEON = 19,
}