#[repr(i64)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CROSSPOSTORIGINTYPE {
    AUTOXPOSTSTATUSCREATIONSHAREVIEW = 1,
    AUTOXPOSTSTATUSCREATIONAUDIENCESELECTORVIEW = 2,
    CONTEXTUALSHAREICON = 3,
    STATUSLISTSINGLESTATUSSHAREMENU = 4,
    STATUSLISTSINGLESTATUSLONGPRESSSHAREMENU = 5,
    STATUSLISTMULTIPLESTATUSESSHAREMENU = 6,
    STATUSDETAILTOPSHAREMENU = 7,
    STATUSDETAILOVERLAYAPPICON = 8,
    XPOSTRETRY = 9,
    AUTOXPOSTRETRY = 10,
    AUTOXPOSTSHAREEXTENSION = 11,
}