#[repr(i64)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CTAFALLBACKREASON {
    NOOTPREQUESTRECEIVED = 0,
    OTPREQUESTEXPIRED = 1,
    HASHMISMATCH = 2,
    NOACTIVITYLISTENINGONTHIRDPARTYAPP = 3,
    OTHER = 4,
    NOPACKAGENAMEONMESSAGE = 5,
    NOCTADISPLAYNAME = 6,
    INCOMPATIBLEOSVERSION = 7,
    NORETRIEVERBUTTON = 8,
    FEATUREDISABLED = 9,
    AMBIGUOUSDELIVERYDESTINATION = 10,
}