#[repr(i64)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CTWABIZUSERJOURNEYOPERATION {
    AGMINJECTED = 1,
    AGMCTACLICKED = 2,
    AGMVIEWDETAILSCLICKED = 3,
    AGMBOTTOMSHEETSHOWN = 4,
    AGMBOTTOMSHEETCLOSED = 5,
    AGMBOTTOMSHEETEXTERNALNAVIGATION = 6,
    DUPLICATEDAGMNOTINJECTED = 7,
    AGMWELCOMEMESSAGENULL = 8,
    AGMINVALIDCTATYPEFROMMESSAGE = 9,
    AGMINVALIDCTAPAYLOADFROMMESSAGE = 10,
    AGMINVALIDSOURCEAPPFROMMESSAGE = 11,
    AGMBOTTOMSHEETIMAGEERROR = 12,
    AGMBOTTOMSHEETTEXTERROR = 13,
    ADPREVIEWDEEPLINKV1CLICKED = 14,
    ADPREVIEWFETCHFROMDEEPLINKV2STARTED = 15,
    ADPREVIEWFETCHFROMDEEPLINKV2SUCCESS = 16,
    ADPREVIEWFETCHFROMDEEPLINKV2FAILED = 17,
    ADPREVIEWOPEN = 18,
    ADPREVIEWCLOSE = 19,
    ADPREVIEWRENDERFAILED = 20,
}