#[repr(i64)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum DEFENSEMODEQUARANTINEACTION {
    QUARANTINEDMSG = 0,
    QUARANTINERESTORECLICK = 1,
    QUARANTINERESTOREDISMISS = 2,
    QUARANTINERESTORECONFIRM = 3,
    QUARANTINERESTOREAUTO = 4,
    QUARANTINERESTORESUCCESS = 5,
    QUARANTINERESTOREFAILED = 6,
}