#[repr(i64)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum DISAPPEARINGMODESETTINGEVENTNAMETYPE {
    DEFAULTMESSAGETIMEROPEN = 1,
    DEFAULTMESSAGETIMERSET = 2,
    DEFAULTMESSAGETIMEREXIT = 3,
    LEARNMORECLICK = 4,
}