#[repr(i64)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum DISCLOSUREEVENTTYPE {
    CTAURLCLICK = 0,
    BODYURLCLICK = 1,
    BODYURLLONGPRESS = 2,
    DISCLOSUREINFOCLICK = 3,
    OPENCHATWITHUNREADMM = 4,
    CTAAPPCLICK = 5,
}