#[repr(i64)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum DOWNLOADORIGINTYPE {
    CHATPERSONAL = 1,
    CHATGROUP = 2,
    STATUSUSER = 3,
    STATUSADS = 4,
    PRODUCTCATALOG = 5,
    GDPR = 6,
    STICKERPICKER = 7,
    PROFILEPICTURE = 8,
    BLOKS = 9,
    P2B = 10,
    MESSAGEHISTORYSYNC = 11,
    COMMUNITY = 12,
    CHANNEL = 13,
    BROADCAST = 14,
    INTEROP = 15,
    WAMOSTATUS = 16,
    WAMOBIZPROFILE = 17,
    WAMOPREFERENCES = 18,
    RICHORDERSTATUS = 19,
    WABACKUP = 20,
}