#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ENUMASPRESENTEDBIMONTHLYDAILYFORTNIGHTLYHALFYEARLYMONTHLYONETIMEQUARTERLYUNKNOWNWEEKLYYEARLY {
    ASPRESENTED,
    BIMONTHLY,
    DAILY,
    FORTNIGHTLY,
    HALFYEARLY,
    MONTHLY,
    ONETIME,
    QUARTERLY,
    UNKNOWN,
    WEEKLY,
    YEARLY,
}