#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ENUMACTIVEDELETEDINACTIVENEEDSRETOKENIZATIONNEEDSRETOKENIZATIONDELETEDSUSPENDED {
    ACTIVE,
    DELETED,
    INACTIVE,
    NEEDSRETOKENIZATION,
    NEEDSRETOKENIZATIONDELETED,
    SUSPENDED,
}