#[repr(i64)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ESRFAILUREREASONTYPE {
    ESRABPROPOFF = 1,
    DMRELIABILITYABPROPOFF = 2,
    INVALIDMESSAGETYPE = 3,
    OLDEREPHEMERALSETTINGTIMESTAMP = 4,
    NOEPHEMERALINFO = 5,
    ATTEMPTSEXHAUSTED = 6,
    NOUSERINFO = 7,
    NOCHATSESSION = 8,
    INVALIDEPHEMERALDURATION = 9,
}