#[repr(i64)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum GENAIEXITPOINT {
    CANCELFULLSHEET = 1,
    CANCELHALFSHEET = 2,
    DISMISSFULLSHEET = 3,
    DISMISSHALFSHEET = 4,
    INACTIVITYFULLSHEET = 5,
    INACTIVITYHALFSHEET = 6,
    KEYBOARDFULLSHEET = 7,
    KEYBOARDHALFSHEET = 8,
    CAMERAFULLSHEET = 9,
    CAMERAHALFSHEET = 10,
    BACKGROUNDEDFULLSHEET = 11,
    BACKGROUNDEDHALFSHEET = 12,
    HALFSHEETDIRECTTOSETTING = 13,
    FULLSHEETDIRECTTOSETTING = 14,
    EXITMMSURFACE = 15,
    COMPOSERTRANSITION = 16,
}