#[repr(i64)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum GROUPSUSPENSIONAPPEALUIACTION {
    CONTACTSUPPORTCLICK = 1,
    DELETEGROUPCLICK = 2,
    SEEGROUPCLICK = 3,
    DEACTIVATECOMMUNITY = 4,
    LEAVECOMMUNITYCLICK = 5,
    SUSPENSIONBOTTOMSHEETIMPRESSION = 6,
    REQUESTREVIEWCLICK = 7,
    OKCLICK = 8,
    SEEDETAILSCLICK = 9,
    NOTIFICATIONCLICK = 10,
    INREVIEWBOTTOMSHEETIMPRESSION = 11,
    ACCEPTBOTTOMSHEETIMPRESSION = 12,
    REJECTBOTTOMSHEETIMPRESSION = 13,
    REQUESTREVIEWSUBMITSUCCESS = 14,
    REQUESTREVIEWSUBMITFAILURE = 15,
    FOOTERIMPRESSION = 16,
    NOTIFICATIONIMPRESSION = 17,
}