#[repr(i64)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum GROUPPROFILEACTIONTYPE {
    CHANGEPROFILEPHOTO = 1,
    TAPACTIONITEMTAKEPHOTO = 2,
    TAPACTIONITEMVIEWPHOTO = 3,
    TAPACTIONITEMEMOJISTICKER = 4,
    TAPACTIONITEMUPLOADPHOTO = 5,
    TAPACTIONITEMREMOVEPHOTO = 6,
    TAPACTIONITEMWEBSEARCH = 7,
    EMOJIPANELOPEN = 8,
    STICKERPANELOPEN = 9,
    PROFILEPICUPDATED = 10,
}