#[repr(i64)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum GROUPJOINREQUESTACTIONTYPE {
    MEMBERSHIPREQUESTCREATE = 1,
    VIEWPENDINGPARTICIPANTS = 2,
    MEMBERSHIPREQUESTAPPROVALMODEON = 3,
    MEMBERSHIPREQUESTAPPROVALMODEOFF = 4,
    MEMBERSHIPREQUESTAPPROVE = 5,
    MEMBERSHIPREQUESTREJECT = 6,
    MEMBERSHIPREQUESTCANCEL = 7,
    DISMISSPENDINGPARTICIPANTSBANNER = 8,
}