#[repr(i64)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum GROUPHISTORYINELIGIBILITYREASON {
    NOSHAREABLEMESSAGES = 0,
    NOTINGROUP = 1,
    RECEIVERNOTELIGIBLE = 2,
    SENDERNOTELIGIBLE = 3,
    NOTNEWORALREADYSENT = 4,
    GROUPNOTFOUND = 5,
    EXPERIMENTDISABLED = 6,
    GROUPTYPENOTELIGIBLE = 7,
    UNKNOWN = 8,
}