#[repr(i64)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum GROUPMEMBERUPDATESACTIONNAME {
    VIEW = 0,
    CLICKPASTMEMBERUPDATE = 1,
    CLICKUSERNAMEUPDATE = 2,
    CLICKINFOOPTION = 3,
    CLICKMESSAGEOPTION = 4,
    CLICKAUDIOOPTION = 5,
    CLICKVIDEOOPTION = 6,
    CLICKUSERNAMEUPSELLOPTION = 7,
    CLICKEDITCONTACTINFO = 8,
    FETCHMEMBERUPDATESSUCCESS = 9,
    FETCHMEMBERUPDATESFAILURE = 10,
    FETCHMEMBERUPDATESEMPTY = 11,
    VIEWUSERNAMEUPSELLBUTTON = 12,
    CLICKADDTOCONTACTS = 13,
}