#[repr(i64)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum GROUPSUSPENSIONAPPEALUISURFACE {
    GROUPSUSPENSIONBOTTOMSHEET = 1,
    COMMUNITYSUSPENSIONBOTTOMSHEET = 2,
    SUSPENDEDFOOTER = 3,
    INREVIEWFOOTER = 4,
    REJECTFOOTER = 5,
    INREVIEWBOTTOMSHEET = 6,
    ACCEPTBOTTOMSHEET = 7,
    REJECTBOTTOMSHEET = 8,
    SUSPENDEDNOTIFICATION = 9,
    ACCEPTNOTIFICATION = 10,
    REJECTNOTIFICATION = 11,
    REQUESTREVIEWERRORDIALOG = 12,
}