#[repr(i64)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum HASHVERIFICATIONFAILURETYPE {
    HMACCHUNK = 1,
    ENCRYPTEDSHA256MISMATCH = 2,
    PLAINTEXTSHA256MISMATCH = 3,
    ENCRYPTEDSHA256NULL = 4,
    PLAINTEXTSHA256NULL = 5,
    DECRYPTIONFAILED = 6,
    TRUNCATEDHMACVERIFICATIONFAILED = 7,
}