#[repr(i64)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum INCOMINGCALLNOTIFICATIONSTATETYPE {
    INCOMINGCALLNOTIFICATIONSTATEINIT = 1,
    INCOMINGCALLNOTIFICATIONSTATESHOWATTEMPTED = 2,
    INCOMINGCALLNOTIFICATIONSTATESILENCED = 3,
    INCOMINGCALLNOTIFICATIONSTATEDECLINED = 4,
    INCOMINGCALLNOTIFICATIONSTATEACCEPTED = 5,
    INCOMINGCALLNOTIFICATIONSTATETIMEOUT = 6,
    INCOMINGCALLNOTIFICATIONSTATEDEVICEERROR = 7,
    INCOMINGCALLNOTIFICATIONSTATEVOIPLAYOUT = 8,
    INCOMINGCALLNOTIFICATIONSTATELOBBYLAYOUT = 9,
    INCOMINGCALLNOTIFICATIONSTATEAPPWINDOWSHOWATTEMPTED = 10,
    INCOMINGCALLNOTIFICATIONSTATEAPPWINDOWSUCCESS = 11,
    INCOMINGCALLNOTIFICATIONSTATEAPPWINDOWFAIURE = 12,
    INCOMINGCALLNOTIFICATIONSTATETOASTSHOWATTEMPTED = 13,
    INCOMINGCALLNOTIFICATIONSTATETOASTSUCCESS = 14,
    INCOMINGCALLNOTIFICATIONSTATETOASTFAILURE = 15,
    INCOMINGCALLNOTIFICATIONSTATESETTINGSCLICKED = 16,
}