#[repr(i64)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum INCOMINGCALLUIACTIONTYPE {
    INCOMINGCALLSCREENANSWER = 1,
    INCOMINGCALLSCREENREJECT = 2,
    INCOMINGCALLNOTIFICATIONANSWER = 3,
    INCOMINGCALLNOTIFICATIONREJECT = 4,
    PENDINGCALLSCREENENDANDANSWER = 5,
    PENDINGCALLSCREENHOLDANDANSWER = 6,
    PENDINGCALLSCREENREJECT = 7,
    INCOMINGCALLREMOTEANSWER = 8,
    INCOMINGCALLREMOTEREJECT = 9,
    PENDINGCALLNOTIFICATIONENDANDANSWER = 10,
    PENDINGCALLNOTIFICATIONREJECT = 11,
    MINIMIZEDBANNERANSWER = 12,
    MINIMIZEDBANNERREJECT = 13,
    INCOMINGCALLSCREENTURNOFFVIDEO = 14,
    INCOMINGCALLSCREENTURNONVIDEO = 15,
}