#[repr(i64)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum INTERACTIONSURFACE {
    NEWSLETTERINFODRAWER = 0,
    NEWSLETTERCONVERSATIONSCREEN = 1,
    ENFORCEMENTALERTLIST = 2,
    ENFORCEMENTDETAILSCREEN = 3,
    REMEDIATIONOPTIONSCREEN = 4,
    REQUESTREVIEWDESCRIPTIONSCREEN = 5,
    REQUESTREVIEWREASONSCREEN = 6,
    REQUESTREVIEWTEXTREASONSCREEN = 7,
    SEEREVIEWDETAILSSCREEN = 8,
    DSBFLOWSCREEN1 = 9,
    DSBFLOWSCREEN2 = 10,
    DSBFLOWSCREEN3 = 11,
    DELETECHANNELMSGCONFIRMATIONSCREEN = 12,
    DELETECHANNELCONFIRMATIONSCREEN = 13,
    DELETECHANNELPHONENUMBERCONFIRM = 14,
    CONTACTREPORTERSCREEN1 = 15,
    CONTACTREPORTERSCREEN2 = 16,
    ENFORCEMENTPOLICYDETAILSBOTTOMSHEET = 17,
}