#[repr(i64)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum LABELTARGETS {
    LABEL = 1,
    MESSAGE = 2,
    CONTACT = 3,
    LABELSSCREEN = 4,
    LABELDETAILSSCREEN = 5,
    EDITLABELDIALOG = 6,
    DELETELABELDIALOG = 7,
    LABELMESSAGEDIALOG = 8,
    LABELCHATDIALOG = 9,
    ADDLABELDIALOG = 10,
    BULKUNLABELDIALOG = 11,
    LABELCOMBINEDDIALOG = 12,
    GROUP = 13,
    BROADCAST = 14,
    NEWLISTSCREEN = 15,
}