#[repr(i64)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum LOBBYEXITTYPE {
    ERROR = 0,
    CONNECTED = 1,
    REJECTEDBYUSER = 2,
    MISSED = 3,
    LOBBYNACK = 4,
    ACCEPTNACK = 5,
    MISSEDNORING = 6,
    LINKQUERYNACK = 7,
    LINKJOINNACK = 8,
    TIMEOUT = 9,
    LOBBYSWITCH = 10,
    OFFERNACK = 11,
    WAITINGROOMDENIED = 12,
    WAITINGROOMLEAVE = 13,
    WAITINGROOMTIMEOUT = 14,
}