#[repr(i64)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum LWICTWAADCTATYPE {
    PROMOTEAGAIN = 1,
    PAUSEAD = 2,
    RESUMEAD = 3,
    ADDBUDGET = 4,
    VIEWAD = 5,
    COMPLETEPAYMENT = 6,
    RECREATEADWITHRECOMMENDATION = 7,
    EDITADWITHRECOMMENDATION = 8,
    DELETEAD = 9,
    SGCINCREASEBUDGET = 10,
    SGCEXTENDDURATION = 11,
    ADVANTAGEPLUSAUDIENCEMFR = 12,
    DURATIONMFR = 13,
}