#[repr(i64)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum LWIADCREATIONACCOUNTCONSENTFLOW {
    SKIPCONSENTWITHEXISTINGFBCONSENT = 1,
    SKIPCONSENTWITHOUTFBWEBLOGINOPTION = 2,
    SKIPCONSENTWITHFBWEBLOGINOPTION = 3,
    SKIPCONSENTWITHSUGGESTFBCONSENT = 4,
    ACCEPTCONSENTWITHSUGGESTFBCONSENT = 5,
    ACCEPTCONSENTWITHREQUIREFBCONSENT = 6,
    RELOADBLOKSSCREENONSUCCESSFBWEBSSO = 7,
}