#[repr(i64)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum MANAGEADSENTRYPOINT {
    WEBOVERFLOWMENU = 1,
    SMBCHATLISTCTWABANNER = 2,
    SMBNATIVEADSMANAGEMENT = 3,
    SMBBUSINESSTOOLSMANAGEADSLISTITEM = 4,
}