#[repr(i64)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum MDCHATASSIGNMENTSECONDARYACTIONTYPE {
    ACTIONSYSTEMMESSAGEADDEDTOCHATHISTORY = 0,
    ACTIONSYSTEMMESSAGECREATIONERROR = 1,
    ACTIONSYSTEMMESSAGERENDERED = 2,
    ACTIONCHATSTATUSTICKERSHOWN = 3,
    ACTIONTOOLTIPSHOWN = 4,
}