#[repr(i64)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum METAVERIFIEDUSERACTIONINTERACTIONERROR {
    EDITPROFILEPICTURELIMITREACHED = 1,
    NEWSUBSCRIPTION = 2,
    LINKEDDEVICELIMITREACHEDERROR = 3,
    PROFILEPICNOTAUTHORISEDERROR = 4,
}