#[repr(i64)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum METAVERIFIEDINTERACTIONACTION {
    MVINTERACTIONACTIONVIEWMVEDUCATIONBOTTOMSHEET = 2,
    MVINTERACTIONACTIONCLICKMVEDUCATIONLINK = 3,
    MVINTERACTIONACTIONVIEWCROSSSELLPROFILEINTERSTITIAL = 4,
    MVINTERACTIONACTIONCLICKMVMORELINK = 5,
    MVINTERACTIONACTIONCLICKGETWABUSINESS = 6,
    MVINTERACTIONACTIONCLICKSUPPORT = 7,
    MVINTERACTIONACTIONCLICKCUSTOMWEBPAGEANDLINK = 8,
    MVINTERACTIONACTIONCLICKMULTIDEVICE = 9,
    MVINTERACTIONACTIONCLICKMVLEARNMORE = 10,
    MVINTERACTIONACTIONCLICKMVHOME = 11,
    MVINTERACTIONACTIONCLICKBLOCK = 12,
    MVINTERACTIONACTIONCLICKPROFILE = 13,
    VIEWNOTMVLABEL = 14,
    CLICKNOTMVLABEL = 15,
    VIEW = 16,
    CLICKLEARNMORE = 17,
    CLICKGETMV = 18,
    CLICKDISMISS = 19,
    CLICKBADGE = 20,
    VIEWBADGE = 21,
}