#[repr(i64)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum MIGRATIONSTAGEENUM {
    GOTABPROP = 1,
    PRIMARYLOCALMIGRATIONSTARTED = 2,
    PRIMARYLOCALMIGRATIONENDED = 3,
    PRIMARYLOCALMIGRATIONFAILED = 4,
    PRIMARYSENTPEERMESSAGE = 5,
    COMPANIONRECEIVEDPEERMESSAGE = 6,
    COMPANIONLOCALMIGRATIONSTARTED = 7,
    COMPANIONLOCALMIGRATIONENDED = 8,
    COMPANIONLOCALMIGRATIONFAILED = 9,
    COMPANIONMIGRATEDONNEWPAIRING = 10,
    COMPANIONRECEIVEDDEVICECAPABILITY = 11,
    COMPANIONEXTRACTEDANDSAVEDPEERMESSAGE = 12,
}