#[repr(i64)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum MLUNDERSHOOTPYTORCHEDGELIBLOADERRORCODE {
    PTLOADERRORNONE = 0,
    PTLOADERRORDLOPENFAILED = 1,
    PTLOADERRORDLSYMFAILED = 2,
    PTLOADERRORSYMBOLDEREFERENCEFAILED = 3,
    PTLOADERRORINVALIDFRAMEWORKTYPE = 4,
    PTLOADERRORETLOADMETHODFAILED = 5,
}