#[repr(i64)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum MMUSERCONTROLSENTRYPOINT {
    MESSAGEBUBBLE = 1,
    BOTTOMSHEET = 2,
    SYSTEMMESSAGE = 3,
    FMXCARD = 4,
    BUSINESSPROFILE = 5,
    TOAST = 6,
    BLOCKBOTTOMSHEETOTHER = 7,
    BLOCKBOTTOMSHEETCHATLIST = 8,
    BLOCKBOTTOMSHEETPROFILE = 9,
    BLOCKBOTTOMSHEETFMX = 10,
    MESSAGECONTEXTMENU = 11,
    MESSAGETHUMBS = 12,
    POSTSENDSYSTEMMESSAGE = 13,
    NUDGECHAT = 14,
}