#[repr(i64)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ONBOARDINGENTRYPOINT {
    ONBOARDINGENTRYPOINTFASTTRACK = 1,
    ONBOARDINGENTRYPOINTADREVIEWSCREEN = 2,
    ONBOARDINGENTRYPOINTCONSENTHOST = 3,
}