#[repr(i64)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum OPPOSITEVISIBLEIDENTIFICATIONTYPE {
    PHONENUMBER = 1,
    SAVEDCONTACTNAME = 2,
    USERNAME = 3,
    MASKEDPHONENUMBER = 4,
    VERIFIEDBUSINESSNAME = 5,
    PLACEHOLDER = 6,
    PUSHNAME = 7,
}