#[repr(i64)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum OTPEVENTSOURCE {
    NOTIFICATIONCTA = 0,
    NOTIFICATIONBODY = 1,
    CHATCTA = 2,
    OTHER = 3,
    OTPMESSAGE = 4,
    OTPMESSAGEINFO = 5,
    OTPCONFIGURATION = 6,
    OTPREQUESTSENDER = 7,
    OTPZEROTAPSENDER = 8,
    OTPCONFOPTION = 9,
}