#[repr(i64)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum PAIDMESSAGINGUSERINTERACTIONSACTIONTARGET {
    NONE = 0,
    HEADER = 1,
    CTACOPYCODE = 2,
    CTAURL = 3,
    QUICKREPLY = 4,
    CTACALL = 5,
    CTAREMINDER = 6,
    SEEALL = 7,
    THUMBNAIL = 8,
    VIEWPRODUCT = 9,
    URL = 10,
    CTAAPP = 11,
    IMAGEHEADERURL = 12,
    FULLSCREENIMAGECTAURL = 13,
    FULLSCREENVIDEOCTAURL = 14,
    TEXTHEADERURL = 15,
    FULLSCREENALBUMCTAURL = 16,
    WATCHANDBROWSEVIDEO = 17,
    SUGGESTEDQUICKREPLY = 18,
    QUICKREPLYPILL = 19,
}