#[repr(i64)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum PEERDATAREQUESTTYPE {
    UPLOADSTICKER = 0,
    SENDRECENTSTICKERBOOTSTRAP = 1,
    GENERALLINKPREVIEW = 2,
    HISTORYSYNCONDEMAND = 3,
    PLACEHOLDERMESSAGERESEND = 4,
    WAFFLELINKINGNONCEFETCH = 5,
    SYNCDSNAPSHOTRECOVERY = 6,
    HISTORYSYNCCHUNKRETRY = 7,
    GALAXYFLOWACTION = 8,
}