#[repr(i64)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum PEERDATAREQUESTERRORCODE {
    NOTSUPPORTED = 0,
    GENERATIONERROR = 1,
    CHUNKCONSUMED = 2,
    TIMEOUT = 3,
    SESSIONEXHAUSTED = 4,
    CHUNKEXHAUSTED = 5,
    DUPLICATEREQUEST = 6,
}