#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum POLLSTICKER {
    BACKGROUNDCOLORBLUE,
    BACOGROUNDCOLORSLATE,
    CHILDPADDINGRATIO,
    DEFAULTOPTIONWIDTHRATIO,
    FIVEOPTIONSTARRATING,
    IGLEFTTEXTCOLOR,
    IGMULTIOPTION,
    IGRIGHTTEXTCOLOR,
    IGTWOOPTIONCOMBINED,
    MINIMUMLABELWIDTHRATIO,
    TEXTCOLORGREY,
    TWOOPTIONCOMBINED,
    VOTEOPTIONMAXWIDTHRATIO,
}