#[repr(i64)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum PRIVACYCONTROLENTRYPOINTTYPE {
    PRIVACYSETTINGS = 0,
    PROFILEPHOTOJIT = 1,
    SETTINGSSEARCH = 2,
    DEEPLINK = 3,
    PRIVACYCHECKUPBANNER = 4,
    PRIVACYCHECKUPDEEPLINK = 5,
    PRIVACYCHECKUPWACHAT = 6,
    PRIVACYCHECKUPSETTINGSSEARCH = 7,
    DEFENSEMODELOCKEDINTERSTITIAL = 8,
    STICKERINFOSHEET = 9,
    DEFENSEMODEQUARANTINEDINTERSTITIAL = 10,
    DEFENSEMODESETTINGSREMINDERBANNER = 11,
}