#[repr(i64)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum PROTOBUFVALIDATIONFLOW {
    STANZAMESSAGERECEIVE = 0,
    STANZAMESSAGESEND = 1,
    NOTIFICATIONEXTENSIONRECEIVE = 2,
    HISTORYSYNCRECEIVE = 3,
    STANZAPSAMESSAGERECEIVE = 4,
    FUTUREPROOFPROCESSING = 5,
    CROSSPLATFORMMIGRATIONRECEIVE = 6,
    HISTORYSYNCSEND = 7,
}