#[repr(i64)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum PSTOKENNOTREADYREASON {
    NOREASON = 0,
    REASONUNKNOWN = 1,
    REASONWAITFORFIRSTTOKEN = 2,
    REASONINVALIDSHAREDKEY = 3,
    REASONINVALIDFACTOR = 4,
    REASONGENFACTORFAILURE = 5,
    REASONCOMPUTEHMACFAILURE = 6,
    REASONBLINDFAILURE = 7,
    REASONUNBLINDFAILURE = 8,
    REASONLASTSIGNREQNETWORKFAILURE = 9,
    REASONLASTSIGNREQSERVERERROR = 10,
    REASONLASTSIGNREQBADREQUEST = 11,
    REASONLASTSIGNREQOTHERERROR = 12,
    REASONWAITFORGENTOKEN = 13,
    REASONGENSHAREDKEYFAILURE = 14,
    REASONWAITFORGENFIRSTTOKEN = 15,
}