#[repr(i64)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum QUICKREPLYTYPE {
    QUICKREPLYTYPEPIXKEY = 1,
    QUICKREPLYTYPESHAREUPIQR = 2,
    QUICKREPLYTYPESETUPUPIQR = 3,
    QUICKREPLYTYPEPAYMENTKEY = 4,
    QUICKREPLYTYPEREQUESTCONTACTINFO = 5,
}