#[repr(i64)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum QUOTEDMESSAGEUSERJOURNEYENTRYPOINT {
    CONTEXTMENUREPLYBUTTON = 1,
    SWIPEDTOREPLY = 2,
    AUTO = 3,
    MESSAGEDOUBLETAP = 4,
    KEYBOARDSHORTCUT = 5,
    INTENTBASED = 6,
}