#[repr(i64)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum QUOTEDMESSAGEUSERJOURNEYACTION {
    QUOTEDMESSAGEADDED = 1,
    QUOTEDMESSAGEDELETED = 2,
    QUOTEDMESSAGETAPPEDINCOMPOSER = 3,
    QUOTEDMESSAGEBUBBLETAPPED = 4,
    QUOTEDMESSAGESENT = 5,
    QUOTEDMESSAGEUPDATED = 6,
}