#[repr(i64)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum REACTIONUSERJOURNEYACTION {
    TRAYOPEN = 1,
    SEARCHOPEN = 2,
    REACTIONSELECT = 3,
    REACTIONUNSELECT = 4,
    REACTIONSEARCH = 5,
    SEARCHCLOSE = 6,
    TRAYCLOSE = 7,
    REACTIONDETAILS = 8,
    SELECTPROFILE = 9,
    DETAILSDISMISS = 10,
    SELECTALBUMTHUMBNAIL = 11,
    SELECTTABINREACTIONDETAILS = 12,
}