#[repr(i64)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum REPORTINGTOKENVALIDATIONFAILUREREASON {
    MISSINGMESSAGESECRET = 0,
    EMPTYREPORTINGTOKENCONTENT = 1,
    MISMATCHREPORTINGTOKEN = 2,
    UNSUPPORTEDVERSION = 3,
    GROUPHISTORYMESSAGEMISSINGFROMPUBLICSTANZA = 4,
}