#[repr(i64)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum REPORTTOADMININTERACTION {
    CLICKOPENADMINDASHBOARD = 0,
    CLICKSENDFORADMINREVIEW = 1,
    CLICKCONFIRMSENDFORADMINREVIEW = 2,
    CLICKCANCELSENDFORADMINREVIEW = 3,
}