#[repr(i64)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum RETRYREJECTREASON {
    OTHER = 0,
    DOUBLECHECKMARK = 1,
    IDENTITYCHANGE = 2,
    MESSAGENOTEXIST = 3,
    HIGHRETRYCOUNT = 4,
    MESSAGEEXPIRED = 5,
    STATUSEXPIRED = 6,
    INCORRECTCHATTYPE = 7,
    RECEIPTNOTFOUND = 8,
    DEVICENOTRECIPIENT = 9,
    HOSTEDDEVICECHANGED = 10,
    DEVICENOTINDATABASE = 11,
    DEVICEREVOKED = 12,
}