#[repr(i64)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SETTING {
    ALLCONTACTS = 1,
    ALLCONTACTSEXCEPT = 2,
    ONLYSHAREWITHCONTACTS = 3,
    ONLYSHAREWITHCLOSEFRIENDS = 4,
    ONLYSHAREWITHCUSTOMLIST = 5,
    GROUPSTATUS = 6,
}