#[repr(i64)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SHARECONTENTUSERJOURNEYACTION {
    CONTACTPICKERDISPLAYED = 1,
    RECIPIENTSSELECTED = 2,
    CONTENTSHARED = 4,
    CANCEL = 5,
    ABANDONED = 6,
    MEDIACOMPOSERDISPLAYED = 7,
    SHAREDTEXTCOMPOSERDISPLAYED = 8,
    FUNNELSTART = 9,
    SAVESTATUS = 10,
}