#[repr(i64)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SHOPSMANAGEMENTACTION {
    ACTIONCLICKSHOPSSETTING = 1,
    ACTIONCLICKCATALOGSETTING = 2,
    ACTIONCLICKCOMMERCEMANAGERINCATALOGSETTING = 3,
    ACTIONCLICKCANCELINCATALOGSETTING = 4,
    ACTIONCLICKVIEWSHOPSINSHOPSSETTING = 5,
    ACTIONCLICKCOMMERCEMANAGERINSHOPSSETTING = 6,
    ACTIONCLICKCANCELINSHOPSSETTING = 7,
    ACTIONSHOPSPRODUCTPREVIEWVISIBLE = 8,
    ACTIONCLICKSHOPSPRODUCTPREVIEWTILE = 9,
    ACTIONCLICKMANAGESHOPS = 10,
    ACTIONSHARESHOPS = 11,
    ACTIONCLICKVIEWSHOPSFROMEDITBIZPROFILE = 12,
    ACTIONCLICKCOMMERCEMANAGERFROMEDITBIZPROFILE = 13,
    ACTIONCLICKCANCELFROMEDITBIZPROFILE = 14,
}