#[repr(i64)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SMBDATASHARINGCONSENTSETTINGENTRYPOINT {
    ENTRYPOINTORDERSCREEN = 0,
    ENTRYPOINTSETTINGSSCREEN = 1,
    ENTRYPOINTLABELSSCREEN = 2,
    ENTRYPOINTCHATSCREEN = 3,
    ENTRYPOINTUNKNOWN = 4,
    ENTRYPOINTDEEPLINKGENERIC = 5,
    ENTRYPOINTDEEPLINKADSMANAGER3PDGUIDANCECARD = 6,
}