#[repr(i64)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum STAGEFAILUREREASONENUM {
    MALFORMEDPEERMESSAGE = 1,
    INITIATEDLOGOUTBASEDONMAPPING = 2,
    DIDNOTGETPEERMESSAGEONTIME = 3,
    DIDNOTCOMPLETEMIGRATIONONTIME = 4,
    COMPANIONUNSUPPORTEDVERSION = 5,
    INTERNALERROR = 6,
    COMPANIONTIMEOUTBASEDONDEVICECAPABILITY = 7,
}