#[repr(i64)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum STATUSINTERACTIONTYPE {
    QUESTIONANSWERSENT = 1,
    QUESTIONANSWERRECEIVED = 2,
    REPLY = 3,
    MENTIONRESHARESENT = 4,
    MENTIONRESHARERECEIVED = 5,
    STATUSRESHARESENT = 6,
    STATUSRESHARERECEIVED = 7,
    REACTIONSTICKERSENT = 8,
    REACTIONSTICKERRECEIVED = 9,
    REACTION = 10,
    ADDYOURSRESPONSE = 11,
    REPLYWITHSTATUS = 12,
}