#[repr(i64)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum STATUSVIEWENTRYMETHOD {
    FORWARDTAP = 1,
    BACKTAP = 2,
    FORWARDSWIPE = 3,
    BACKSWIPE = 4,
    DIRECTPOGTAP = 5,
    AUTONAVIGATETIMEREND = 6,
    STATUSWIDGET = 7,
    CHAININGPILLTAP = 8,
    ENGAGEMENTCARDCTATAP = 9,
    MYSTATUSESSCREEN = 10,
}