#[repr(i64)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum STATUSPRIVACYSURFACE {
    STATUSPRIVACYSETTINGS = 1,
    TEXTCOMPOSER = 2,
    MEDIACOMPOSER = 3,
    CONTACTPICKER = 4,
    VOICECOMPOSER = 5,
    STATUSVIEWERCLOSESHARINGMIMICRY = 6,
}