#[repr(i64)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum STICKERSENDORIGINTYPE {
    STICKERSEARCH = 1,
    FORWARD = 2,
    STICKERPICKERTABRECENTS = 3,
    STICKERPICKERTABFAVORITES = 4,
    STICKERPICKERTABEMOTION = 5,
    STICKERPICKERTABPACK = 6,
    STICKERPICKERTABCONTEXTUALSUGGESTIONS = 7,
    STICKERMAKER = 8,
    STICKERSTORE = 9,
    AISTICKERCREATE = 10,
    AISTICKERCREATETRAY = 11,
    AISTICKERCREATECHAT = 12,
    STATUSQUICKREPLY = 13,
    DISCOVERYPACK = 14,
    STICKERFROMDEVICEKEYBOARD = 15,
    STICKERPACKINFO = 16,
    CONVERSATIONSTARTER = 17,
    STICKERSEARCHTRENDING = 18,
}