#[repr(i64)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SUPPORTAIEVENTTYPE {
    CONTACTUSCLICKED = 1,
    STARTCHATCLICKED = 2,
    NOINTERNETDIALOGSHOWN = 6,
    TICKETCREATIONDIALOGSHOWN = 7,
    REVIEWINFORMATIONLEARNMORECLICKED = 8,
    SUPPORTAISCREENSHOWN = 9,
    THUMBUPCLICKED = 10,
    THUMBDOWNCLICKED = 11,
    SUBMITMESSAGEFEEDBACK = 12,
    SUBMITMESSAGEFEEDBACKFAILED = 13,
    SUBMITMESSAGEFEEDBACKSUCCEEDED = 14,
    NEGATIVEFEEDBACKOPTIONSSCREENCANCELLED = 15,
    NEGATIVEFEEDBACKOPTIONSSCREENSHOWN = 16,
    CONTACTUSERRORDIALOGSHOWN = 17,
    CONTACTUSERRORDIALOGEMAILBUTTONCLICKED = 18,
    CREATESUPPORTTICKETSUCCESS = 19,
    CREATESUPPORTTICKETERROR = 20,
    SUPPORTAISCREENOKCLICKED = 21,
    SUPPORTAISCREENSHOWNONTHECHAT = 22,
    SUPPORTAICITATIONTAPPED = 23,
}