#[repr(i64)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum THREADACTIONTYPES {
    PIN = 1,
    UNPIN = 2,
    DELETE = 3,
    RENAME = 4,
    CLICKNEWCHAT = 5,
    CLICKCHATHISTORY = 6,
    CLICKCONVERSATIONTHREAD = 7,
    THREADENTER = 8,
    THREADEXIT = 9,
    THREADLISTIMPRESSION = 10,
    THREEDOTMENU = 11,
    FIRSTPROMPTSENT = 12,
    SEARCHRESULTCLICK = 13,
    SEARCHRESULTSHOWN = 14,
    AIHOMEIMPRESSION = 15,
    CLICKCONTINUECHATMODULE = 16,
}