#[repr(i64)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TYPE {
    NONE = 0,
    OFFER = 1,
    OFFERRECEIPT = 2,
    ACCEPT = 3,
    REJECT = 4,
    TERMINATE = 5,
    TRANSPORT = 6,
    OFFERACK = 7,
    OFFERNACK = 8,
    RELAYLATENCY = 9,
    RELAYELECTION = 10,
    INTERRUPTION = 11,
    MUTE = 12,
    PREACCEPT = 13,
    ACCEPTRECEIPT = 14,
    VIDEOSTATE = 15,
    NOTIFY = 16,
    GROUPINFO = 17,
    ENCREKEY = 18,
    PEERSTATE = 19,
    VIDEOSTATEACK = 20,
    FLOWCONTROL = 21,
    WEBCLIENT = 22,
    ACCEPTACK = 23,
    GROUPUPDATE = 24,
    OFFERNOTICE = 25,
    MAX = 26,
}