#[repr(i64)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum UIMESSAGEYOURSELFACTIONTYPE {
    NEWCHATPRESSED = 1,
    YOUSELECTED = 2,
    SEARCHBARPRESSED = 3,
    SEARCHFULLNAMEYOUSELECTED = 4,
    NEWNTSCREATED = 5,
    EXISTINGNTSOPENED = 6,
}