#[repr(i64)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum USERNAMECREATIONENTRYPOINT {
    USERNAMEUPSELL = 1,
    PROFILESETTING = 2,
    PINUPSELLINTEGRITYBANNER = 3,
    USERNAMEACTIVATIONBANNER = 4,
    USERNAMEUPSELLCREATIONBANNERWA = 5,
    USERNAMEUPSELLRESERVATIONBANNERWA = 6,
    SMBFBUSERNAMERESERVATION = 7,
    ACTIVATIONAPPFOREGROUND = 8,
    DEEPLINK = 9,
    FBPAGEWADEEPLINK = 10,
    IGWADEEPLINK = 11,
    USERNAMEUPSELLSYSMSG = 12,
    USERNAMEKEYUPSELLPREACTIVATIONBANNERWA = 13,
    ACCOUNTSETTING = 14,
}