#[repr(i64)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum USERNOTICEERROREVENT {
    INVALIDSTANZA = 1,
    JSONFETCH = 2,
    JSONPARSE = 3,
    IMAGEFETCH = 4,
    NOELIGIBLEDISCLOSURE = 5,
    DISCLOSURESTAGEFETCH = 6,
    UITEMPLATEMISMATCHED = 7,
    ERRORUNKNOWN = 8,
    SYNCSTAGEMISMATCH = 9,
    IMAGEFETCH400 = 10,
    JSONFETCH400 = 11,
    JSONFETCHREDIRECT = 12,
    IMAGEFETCHREDIRECT = 13,
    IMAGEFETCHFORBIDDEN = 14,
    JSONFETCHFORBIDDEN = 15,
    FAILTOSENDSTAGETOSERVER = 16,
}