#[repr(i64)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum WAFFLELIFECYCLETRACESOURCETYPE {
    NOTAPPLICABLE = 0,
    SYNCD = 1,
    NOTIFICATIONLINKED = 2,
    NOTIFICATIONUNLINKED = 3,
    NOTIFICATIONRESYNC = 4,
    NONCEREQUEST = 5,
    NONCERESPONSE = 6,
    REFRESHTOKEN = 7,
    ERRORRETRY = 8,
    PRIMARYNONCEREQUEST = 9,
    PRIMARYNONCERESPONSE = 10,
}