#[repr(i64)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum WEBCQUICKACTIONID {
    TEXTSTATUS = 1,
    PHOTOVIDEO = 2,
    CREATECHANNEL = 3,
    FINDCHANNELS = 4,
    COMMUNITYINFO = 5,
    COMMUNITYMEMBERS = 6,
    COMMUNITYSETTINGS = 7,
    COMMUNITYNEWGROUP = 8,
    COMMUNITYEXISTINGGROUP = 9,
    SENDDOCUMENT = 10,
    ADDCONTACT = 11,
    ASKMETAAI = 12,
    STARTCALL = 13,
    GOTOCALLS = 14,
}