#[repr(i64)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum WEBCDISPLAYSTATUSTYPE {
    SHOWEDPREVIEWTOUSER = 1,
    PREVIEWTIMEOUT = 2,
    PREVIEWMALFORMED = 3,
    PREVIEWNOTFOUND = 4,
    PREVIEWGENERALERROR = 5,
    PREVIEWDECRYPTIONERROR = 6,
}