#[repr(i64)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum WPBUJSURFACE {
    APPTHEME = 1,
    APPICON = 2,
    RINGTONE = 3,
    LIST = 4,
    CHATTHEME = 5,
    ALERTTONE = 6,
    PINNEDCHAT = 7,
    STICKERTRAY = 8,
    STICKERRECEIVED = 9,
    STICKERSTORE = 10,
    APPEARANCESETTINGS = 11,
    NOTIFICATIONSETTINGS = 12,
    WHATSAPPSETTINGS = 13,
    STICKERGENERIC = 14,
    BACKUPPROVIDERSELECTION = 15,
    BACKUPNEWUSERSETUP = 16,
}