const WamMediaPicker = 1038 // channel: regular

type MediaPickerEvent struct {
	MediaType MEDIATYPE `wam:"media_type"` // field 1
	MediaPickerSent int64 `wam:"media_picker_sent"` // field 2
	MediaPickerDeleted int64 `wam:"media_picker_deleted"` // field 3
	MediaPickerChanged int64 `wam:"media_picker_changed"` // field 4
	MediaPickerSentUnchanged int64 `wam:"media_picker_sent_unchanged"` // field 5
	MediaPickerCroppedRotated int64 `wam:"media_picker_cropped_rotated"` // field 10
	MediaPickerDrawing int64 `wam:"media_picker_drawing"` // field 11
	MediaPickerStickers int64 `wam:"media_picker_stickers"` // field 12
	MediaPickerText int64 `wam:"media_picker_text"` // field 13
	MediaPickerOrigin MEDIAPICKERORIGINTYPE `wam:"media_picker_origin"` // field 14
	MediaPickerT string `wam:"media_picker_t"` // field 15
	ChatRecipients int64 `wam:"chat_recipients"` // field 16
	StatusRecipients int64 `wam:"status_recipients"` // field 17
	MediaPickerFilter int64 `wam:"media_picker_filter"` // field 18
	MediaPickerLikeDoc int64 `wam:"media_picker_like_doc"` // field 19
	MediaPickerNotLikeDoc int64 `wam:"media_picker_not_like_doc"` // field 20
	MediaPickerOriginThirdParty bool `wam:"media_picker_origin_third_party"` // field 21
	IsViewOnce bool `wam:"is_view_once"` // field 22
	PhotoGalleryDurationT string `wam:"photo_gallery_duration_t"` // field 23
	AudienceSelectorClicked bool `wam:"audience_selector_clicked"` // field 24
	AudienceSelectorUpdated bool `wam:"audience_selector_updated"` // field 25
	MediaPickerHasLocationSticker bool `wam:"media_picker_has_location_sticker"` // field 26
	PhotoQualitySetting MEDIAQUALITY `wam:"photo_quality_setting"` // field 27
	VideoQualitySetting MEDIAQUALITY `wam:"video_quality_setting"` // field 28
	MediaPickerSessionId string `wam:"media_picker_session_id"` // field 29
	PickerSessionId int64 `wam:"picker_session_id"` // field 30
	MotionPhotoImpressionCount int64 `wam:"motion_photo_impression_count"` // field 31
	MotionPhotoSentCount int64 `wam:"motion_photo_sent_count"` // field 32
	MediaPickerAvatarStickers int64 `wam:"media_picker_avatar_stickers"` // field 33
	HdToggleChange int64 `wam:"hd_toggle_change"` // field 34
	HdToggleEligible bool `wam:"hd_toggle_eligible"` // field 35
	HdToggleState MEDIAQUALITY `wam:"hd_toggle_state"` // field 36
	CaptionPositions string `wam:"caption_positions"` // field 37
	HasCollectionCaption bool `wam:"has_collection_caption"` // field 38
	ItemCaptionCount int64 `wam:"item_caption_count"` // field 39
	IsSentInLandscape bool `wam:"is_sent_in_landscape"` // field 41
	MediaPickerArBackground int64 `wam:"media_picker_ar_background"` // field 42
	MediaPickerArFilter int64 `wam:"media_picker_ar_filter"` // field 43
	MediaPickerArFunEffect int64 `wam:"media_picker_ar_fun_effect"` // field 44
	NumberOfArPostCapture int64 `wam:"number_of_ar_post_capture"` // field 45
	NumberOfArPreCapture int64 `wam:"number_of_ar_pre_capture"` // field 46
	MediaPickerIgluLowlight int64 `wam:"media_picker_iglu_lowlight"` // field 47
	MediaPickerIgluTouchup int64 `wam:"media_picker_iglu_touchup"` // field 48
	NumberOfIgluPostCapture int64 `wam:"number_of_iglu_post_capture"` // field 49
	NumberOfIgluPreCapture int64 `wam:"number_of_iglu_pre_capture"` // field 50
	AutoScaleCount int64 `wam:"auto_scale_count"` // field 51
	TransformCount int64 `wam:"transform_count"` // field 52
	MediaPickerPosition string `wam:"media_picker_position"` // field 53
	IsFbCrosspostingEnabled bool `wam:"is_fb_crossposting_enabled"` // field 54
	IsIgCrosspostingEnabled bool `wam:"is_ig_crossposting_enabled"` // field 55
}