const WamStatusPost = 1176 // channel: regular

type StatusPostEvent struct {
	StatusSessionId int64 `wam:"status_session_id"` // field 1
	MediaType MEDIATYPE `wam:"media_type"` // field 2
	StatusPostResult STATUSPOSTRESULT `wam:"status_post_result"` // field 3
	StatusPostOrigin STATUSPOSTORIGIN `wam:"status_post_origin"` // field 4
	RetryCount int64 `wam:"retry_count"` // field 5
	DefaultStatusPrivacySetting PRIVACYSETTINGSVALUETYPE `wam:"default_status_privacy_setting"` // field 6
	PerPostStatusPrivacySetting PRIVACYSETTINGSVALUETYPE `wam:"per_post_status_privacy_setting"` // field 7
	StatusAudienceSelectorClicked bool `wam:"status_audience_selector_clicked"` // field 8
	StatusAudienceSelectorUpdated bool `wam:"status_audience_selector_updated"` // field 9
	StatusMentionCount int64 `wam:"status_mention_count"` // field 10
	IsResultTerminal bool `wam:"is_result_terminal"` // field 11
	MessageSendT string `wam:"message_send_t"` // field 12
	IsReshare bool `wam:"is_reshare"` // field 13
	StatusContainsMusic bool `wam:"status_contains_music"` // field 14
	Editable bool `wam:"editable"` // field 15
	ExternalInteractables int64 `wam:"external_interactables"` // field 16
	ExternalPackageName string `wam:"external_package_name"` // field 17
	ShareType string `wam:"share_type"` // field 18
	ContainsPrompt bool `wam:"contains_prompt"` // field 19
	IsPromptResponse bool `wam:"is_prompt_response"` // field 20
	MessageKeyHash string `wam:"message_key_hash"` // field 21
	ExtraStickersData string `wam:"extra_stickers_data"` // field 22
	HasArFilters bool `wam:"has_ar_filters"` // field 23
	HasCaption bool `wam:"has_caption"` // field 24
	HasDrawings bool `wam:"has_drawings"` // field 25
	HasFilters bool `wam:"has_filters"` // field 26
	IsVideoMuted bool `wam:"is_video_muted"` // field 27
	IsVideoTrimmed bool `wam:"is_video_trimmed"` // field 28
	StatusId string `wam:"status_id"` // field 29
	StatusType STATUSTYPE `wam:"status_type"` // field 30
	StickersCount int64 `wam:"stickers_count"` // field 31
	TextStatusColorChanged bool `wam:"text_status_color_changed"` // field 32
	TextStatusFontChanged bool `wam:"text_status_font_changed"` // field 33
	TextToolCount int64 `wam:"text_tool_count"` // field 34
	UnifiedSessionId string `wam:"unified_session_id"` // field 35
	IsCropped bool `wam:"is_cropped"` // field 36
	IsRotated bool `wam:"is_rotated"` // field 37
	IsVideoManuallyTrimmed bool `wam:"is_video_manually_trimmed"` // field 38
	StatusAudienceSize int64 `wam:"status_audience_size"` // field 39
	IsSameSongFromAttribution bool `wam:"is_same_song_from_attribution"` // field 40
	IsFromLayouts bool `wam:"is_from_layouts"` // field 41
	UrlHasAdditionalText bool `wam:"url_has_additional_text"` // field 42
	IsMediaAiImagineGenerated bool `wam:"is_media_ai_imagine_generated"` // field 43
	DualUploadPairedMediaId string `wam:"dual_upload_paired_media_id"` // field 44
	PairedMediaType PAIREDMEDIATYPE `wam:"paired_media_type"` // field 45
	StatusPairedMediaQuality STATUSPAIREDMEDIAQUALITY `wam:"status_paired_media_quality"` // field 46
	IsResharable bool `wam:"is_resharable"` // field 47
	GroupMentionCount string `wam:"group_mention_count"` // field 48
	IndividualMentionCount int64 `wam:"individual_mention_count"` // field 49
	IsForwardable bool `wam:"is_forwardable"` // field 51
	IsForwarded bool `wam:"is_forwarded"` // field 52
	StatusCategory STATUSCATEGORY `wam:"status_category"` // field 53
	UpdatesTabSessionId int64 `wam:"updates_tab_session_id"` // field 54
	IsDraft bool `wam:"is_draft"` // field 55
	StatusAudienceSelected int64 `wam:"status_audience_selected"` // field 56
	ChannelStatusId int64 `wam:"channel_status_id"` // field 57
	Cid string `wam:"cid"` // field 58
	IsBatched bool `wam:"is_batched"` // field 59
	StatusPartCode string `wam:"status_part_code"` // field 60
	ErrorMetadata string `wam:"error_metadata"` // field 61
	StatusPostFailureStage STATUSPOSTFAILURESTAGE `wam:"status_post_failure_stage"` // field 62
}