const WamChatMessageCounts = 1644 // channel: regular

type ChatMessageCountsEvent struct {
	ChatTypeInd CHATTYPE `wam:"chat_type_ind"` // field 2
	MessagesSent int64 `wam:"messages_sent"` // field 3
	MessagesReceived int64 `wam:"messages_received"` // field 4
	IsAGroup bool `wam:"is_a_group"` // field 5
	IsAContact bool `wam:"is_a_contact"` // field 6
	StartTime int64 `wam:"start_time"` // field 7
	ChatMuted CHATMUTEDTYPE `wam:"chat_muted"` // field 8
	IsPinned bool `wam:"is_pinned"` // field 9
	IsArchived bool `wam:"is_archived"` // field 10
	MessagesUnread int64 `wam:"messages_unread"` // field 11
	MessagesStarred int64 `wam:"messages_starred"` // field 12
	EphemeralMessagesSent int64 `wam:"ephemeral_messages_sent"` // field 13
	EphemeralMessagesReceived int64 `wam:"ephemeral_messages_received"` // field 14
	ChatEphemeralityDuration int64 `wam:"chat_ephemerality_duration"` // field 15
	ViewOnceMessagesSent int64 `wam:"view_once_messages_sent"` // field 16
	ViewOnceMessagesReceived int64 `wam:"view_once_messages_received"` // field 17
	ViewOnceMessagesOpened int64 `wam:"view_once_messages_opened"` // field 18
	GroupSize int64 `wam:"group_size"` // field 19
	SenderDefaultDisappearingDuration int64 `wam:"sender_default_disappearing_duration"` // field 20
	ReceiverDefaultDisappearingDuration int64 `wam:"receiver_default_disappearing_duration"` // field 21
	GaStatus GASTATUS `wam:"ga_status"` // field 22
	FirstResponseTime int64 `wam:"first_response_time"` // field 25
	CallOffersSent int64 `wam:"call_offers_sent"` // field 26
	CallOffersReceived int64 `wam:"call_offers_received"` // field 27
	TotalCallDuration int64 `wam:"total_call_duration"` // field 28
	BroadcastMsgsSent int64 `wam:"broadcast_msgs_sent"` // field 29
	BroadcastMsgsReceived int64 `wam:"broadcast_msgs_received"` // field 30
	SpamReports int64 `wam:"spam_reports"` // field 31
	IsBlocked bool `wam:"is_blocked"` // field 32
	BlockReason BLOCKREASON `wam:"block_reason"` // field 33
	IsCommerceViewed bool `wam:"is_commerce_viewed"` // field 35
	IsCartAddClicked bool `wam:"is_cart_add_clicked"` // field 36
	IsCtaOnPdpClicked bool `wam:"is_cta_on_pdp_clicked"` // field 37
	OrdersSent int64 `wam:"orders_sent"` // field 38
	PaymentsSent int64 `wam:"payments_sent"` // field 39
	CommerceMsgsSent int64 `wam:"commerce_msgs_sent"` // field 40
	CommerceMsgsReceived int64 `wam:"commerce_msgs_received"` // field 41
	PdpInquiriesSent int64 `wam:"pdp_inquiries_sent"` // field 42
	StorefrontInquiriesSent int64 `wam:"storefront_inquiries_sent"` // field 43
	CollectionInquiriesSent int64 `wam:"collection_inquiries_sent"` // field 44
	FbCtaInquiriesSent int64 `wam:"fb_cta_inquiries_sent"` // field 45
	EntryPointConversionSource string `wam:"entry_point_conversion_source"` // field 46
	EntryPointConversionApp string `wam:"entry_point_conversion_app"` // field 47
	StatusViews int64 `wam:"status_views"` // field 49
	StatusReplies int64 `wam:"status_replies"` // field 50
	GroupMembershipReplies int64 `wam:"group_membership_replies"` // field 51
	GroupPrivateReplies int64 `wam:"group_private_replies"` // field 52
	IsLabelled bool `wam:"is_labelled"` // field 54
	LabelledMsgs int64 `wam:"labelled_msgs"` // field 55
	AwayMsgsSent int64 `wam:"away_msgs_sent"` // field 56
	GreetingMsgsSent int64 `wam:"greeting_msgs_sent"` // field 57
	QuickRepliesSent int64 `wam:"quick_replies_sent"` // field 58
	DisappearingChatInitiator DISAPPEARINGCHATINITIATORTYPE `wam:"disappearing_chat_initiator"` // field 59
	BizCatalogType BIZCATALOGTYPE `wam:"biz_catalog_type"` // field 60
	PdpViews int64 `wam:"pdp_views"` // field 61
	IsOppositePartyInitiated bool `wam:"is_opposite_party_initiated"` // field 62
	ProfileViews int64 `wam:"profile_views"` // field 63
	ProfileReplies int64 `wam:"profile_replies"` // field 64
	BizConversationDepth int64 `wam:"biz_conversation_depth"` // field 65
	ThreadDs string `wam:"thread_ds"` // field 66
	ThreadId string `wam:"thread_id"` // field 67
	NewThread bool `wam:"new_thread"` // field 68
	EphemeralMessagesUnreadExpired int64 `wam:"ephemeral_messages_unread_expired"` // field 69
	CallsResultBusy int64 `wam:"calls_result_busy"` // field 70
	CallsResultCancelled int64 `wam:"calls_result_cancelled"` // field 71
	CallsResultConnected int64 `wam:"calls_result_connected"` // field 72
	CallsResultMissed int64 `wam:"calls_result_missed"` // field 73
	CallsResultRejected int64 `wam:"calls_result_rejected"` // field 74
	GroupContainsBiz bool `wam:"group_contains_biz"` // field 75
	VideoCallsOffered int64 `wam:"video_calls_offered"` // field 76
	VoiceCallsOffered int64 `wam:"voice_calls_offered"` // field 77
	CallsResultError int64 `wam:"calls_result_error"` // field 78
	ChatOverflowClicks int64 `wam:"chat_overflow_clicks"` // field 79
	RepliesSent int64 `wam:"replies_sent"` // field 80
	IsWaPayRegistered bool `wam:"is_wa_pay_registered"` // field 81
	OdReceived int64 `wam:"od_received"` // field 82
	P2mOdNnpTransactionsSent int64 `wam:"p2m_od_nnp_transactions_sent"` // field 83
	P2mOdNpTransactionsSent int64 `wam:"p2m_od_np_transactions_sent"` // field 84
	TypeOfGroup TYPEOFGROUPENUM `wam:"type_of_group"` // field 85
	CartViews int64 `wam:"cart_views"` // field 86
	GroupInfoSetting GROUPINFOSETTINGTYPE `wam:"group_info_setting"` // field 87
	CanEditDmSettings bool `wam:"can_edit_dm_settings"` // field 88
	ForwardMessagesReceived int64 `wam:"forward_messages_received"` // field 89
	ForwardMessagesSent int64 `wam:"forward_messages_sent"` // field 90
	IsMessageYourself bool `wam:"is_message_yourself"` // field 91
	IsPnhEnabledChat bool `wam:"is_pnh_enabled_chat"` // field 92
	RequestedPhoneNumber bool `wam:"requested_phone_number"` // field 93
	SeenMaskedPhoneNumber bool `wam:"seen_masked_phone_number"` // field 94
	LocationsSent int64 `wam:"locations_sent"` // field 96
	ReactionsReceived int64 `wam:"reactions_received"` // field 97
	ReactionsSent int64 `wam:"reactions_sent"` // field 98
	SharedPhoneNumber bool `wam:"shared_phone_number"` // field 99
	EditedMsgsSent int64 `wam:"edited_msgs_sent"` // field 100
	SmbMarketingMessagesReactionsSent int64 `wam:"smb_marketing_messages_reactions_sent"` // field 101
	SmbMarketingMessagesRepliesSent int64 `wam:"smb_marketing_messages_replies_sent"` // field 102
	SmbMarketingMessagesSpamReports int64 `wam:"smb_marketing_messages_spam_reports"` // field 103
	SmbMarketingMsgsReceived int64 `wam:"smb_marketing_msgs_received"` // field 104
	SmbMarketingMsgsSent int64 `wam:"smb_marketing_msgs_sent"` // field 105
	IsInviteCreatedThread bool `wam:"is_invite_created_thread"` // field 106
	ViaContactlessChats bool `wam:"via_contactless_chats"` // field 107
	IsAutoMuted bool `wam:"is_auto_muted"` // field 108
	EphemeralityInitiator EPHEMERALITYINITIATORTYPE `wam:"ephemerality_initiator"` // field 109
	EphemeralityTriggerAction EPHEMERALITYTRIGGERACTIONTYPE `wam:"ephemerality_trigger_action"` // field 110
	IsUserAgent bool `wam:"is_user_agent"` // field 111
	TotalMessageEditsFromAgentCnt int64 `wam:"total_message_edits_from_agent_cnt"` // field 112
	TotalMessageFromAgentCnt int64 `wam:"total_message_from_agent_cnt"` // field 113
	TotalMessageToAgentCnt int64 `wam:"total_message_to_agent_cnt"` // field 114
	PollCreationMessagesReceived int64 `wam:"poll_creation_messages_received"` // field 115
	PollCreationMessagesSent int64 `wam:"poll_creation_messages_sent"` // field 116
	PollUpdateMessagesReceived int64 `wam:"poll_update_messages_received"` // field 117
	PollUpdateMessagesSent int64 `wam:"poll_update_messages_sent"` // field 118
	PttMessagesReceived int64 `wam:"ptt_messages_received"` // field 119
	PttMessagesSent int64 `wam:"ptt_messages_sent"` // field 120
	PtvMessagesReceived int64 `wam:"ptv_messages_received"` // field 121
	PtvMessagesSent int64 `wam:"ptv_messages_sent"` // field 122
	IsUserCreatedAgent bool `wam:"is_user_created_agent"` // field 123
	TextMessagesToUserCreatedAgentCnt int64 `wam:"text_messages_to_user_created_agent_cnt"` // field 124
	TotalMessagesToUserCreatedAgentCnt int64 `wam:"total_messages_to_user_created_agent_cnt"` // field 125
	CommentsReceived int64 `wam:"comments_received"` // field 126
	MessagesRead int64 `wam:"messages_read"` // field 127
	ForwardPhotoMessagesReceived int64 `wam:"forward_photo_messages_received"` // field 128
	ForwardPhotoMessagesSent int64 `wam:"forward_photo_messages_sent"` // field 129
	ForwardTextMessagesReceived int64 `wam:"forward_text_messages_received"` // field 130
	ForwardTextMessagesSent int64 `wam:"forward_text_messages_sent"` // field 131
	ForwardUrlMessagesReceived int64 `wam:"forward_url_messages_received"` // field 132
	ForwardUrlMessagesSent int64 `wam:"forward_url_messages_sent"` // field 133
	PhotoMessagesReceived int64 `wam:"photo_messages_received"` // field 134
	PhotoMessagesSent int64 `wam:"photo_messages_sent"` // field 135
	TextMessagesReceived int64 `wam:"text_messages_received"` // field 136
	TextMessagesSent int64 `wam:"text_messages_sent"` // field 137
	UrlMessagesReceived int64 `wam:"url_messages_received"` // field 138
	UrlMessagesSent int64 `wam:"url_messages_sent"` // field 139
	IsUser3pBotChat bool `wam:"is_user3p_bot_chat"` // field 140
	IsUser1pBizBotChat bool `wam:"is_user1p_biz_bot_chat"` // field 141
	EventCreationMessagesReceived int64 `wam:"event_creation_messages_received"` // field 142
	EventCreationMessagesSent int64 `wam:"event_creation_messages_sent"` // field 143
	EventResponseMessagesReceived int64 `wam:"event_response_messages_received"` // field 144
	EventResponseMessagesSent int64 `wam:"event_response_messages_sent"` // field 145
	ImagineMentionClick int64 `wam:"imagine_mention_click"` // field 146
	MetaAiMentionClick int64 `wam:"meta_ai_mention_click"` // field 147
	MetaAiMentionShow int64 `wam:"meta_ai_mention_show"` // field 148
	AudioMessagesReceived int64 `wam:"audio_messages_received"` // field 149
	AudioMessagesSent int64 `wam:"audio_messages_sent"` // field 150
	DocumentMessagesReceived int64 `wam:"document_messages_received"` // field 151
	DocumentMessagesSent int64 `wam:"document_messages_sent"` // field 152
	ForwardAudioMessagesReceived int64 `wam:"forward_audio_messages_received"` // field 153
	ForwardAudioMessagesSent int64 `wam:"forward_audio_messages_sent"` // field 154
	ForwardDocumentMessagesReceived int64 `wam:"forward_document_messages_received"` // field 155
	ForwardDocumentMessagesSent int64 `wam:"forward_document_messages_sent"` // field 156
	ForwardGifMessagesReceived int64 `wam:"forward_gif_messages_received"` // field 157
	ForwardGifMessagesSent int64 `wam:"forward_gif_messages_sent"` // field 158
	ForwardPtvMessagesReceived int64 `wam:"forward_ptv_messages_received"` // field 159
	ForwardPtvMessagesSent int64 `wam:"forward_ptv_messages_sent"` // field 160
	ForwardStatusReplyMessagesReceived int64 `wam:"forward_status_reply_messages_received"` // field 161
	ForwardStatusReplyMessagesSent int64 `wam:"forward_status_reply_messages_sent"` // field 162
	ForwardStickerMessagesReceived int64 `wam:"forward_sticker_messages_received"` // field 163
	ForwardStickerMessagesSent int64 `wam:"forward_sticker_messages_sent"` // field 164
	ForwardVideoMessagesReceived int64 `wam:"forward_video_messages_received"` // field 165
	ForwardVideoMessagesSent int64 `wam:"forward_video_messages_sent"` // field 166
	GifMessagesReceived int64 `wam:"gif_messages_received"` // field 167
	GifMessagesSent int64 `wam:"gif_messages_sent"` // field 168
	StatusReplyMessagesReceived int64 `wam:"status_reply_messages_received"` // field 169
	StickerMessagesReceived int64 `wam:"sticker_messages_received"` // field 170
	StickerMessagesSent int64 `wam:"sticker_messages_sent"` // field 171
	VideoMessagesReceived int64 `wam:"video_messages_received"` // field 172
	VideoMessagesSent int64 `wam:"video_messages_sent"` // field 173
	CommandSheetShow int64 `wam:"command_sheet_show"` // field 174
	ImagineCommandClick int64 `wam:"imagine_command_click"` // field 175
	ImagineMentionShow int64 `wam:"imagine_mention_show"` // field 176
	SuggestionPromptsClick int64 `wam:"suggestion_prompts_click"` // field 177
	SuggestionPromptsShow int64 `wam:"suggestion_prompts_show"` // field 178
	ChatOrigins CHATORIGINSTYPE `wam:"chat_origins"` // field 179
	HasUsername bool `wam:"has_username"` // field 180
	OppositeVisibleIdentification OPPOSITEVISIBLEIDENTIFICATIONTYPE `wam:"opposite_visible_identification"` // field 181
	IsDeleted bool `wam:"is_deleted"` // field 185
	IsReported bool `wam:"is_reported"` // field 186
	ThreadCreationDate string `wam:"thread_creation_date"` // field 189
	AutoReplyFromIcebreakerSent int64 `wam:"auto_reply_from_icebreaker_sent"` // field 190
	StatusReactionsReceived int64 `wam:"status_reactions_received"` // field 191
	StatusReactionsSent int64 `wam:"status_reactions_sent"` // field 192
	MarkedReadCnt int64 `wam:"marked_read_cnt"` // field 193
	MarkedReadMessageCnt int64 `wam:"marked_read_message_cnt"` // field 194
	AiDiscoveryTab string `wam:"ai_discovery_tab"` // field 195
	BottomSheetForwardMessagesSent int64 `wam:"bottom_sheet_forward_messages_sent"` // field 196
	BottomSheetImagesGenerated int64 `wam:"bottom_sheet_images_generated"` // field 197
	BottomSheetMessagesDownloaded int64 `wam:"bottom_sheet_messages_downloaded"` // field 198
	BottomSheetMessagesReceived int64 `wam:"bottom_sheet_messages_received"` // field 199
	BottomSheetMessagesSent int64 `wam:"bottom_sheet_messages_sent"` // field 200
	BottomSheetPromptsInitiated int64 `wam:"bottom_sheet_prompts_initiated"` // field 201
	ImagineMeMessagesSent int64 `wam:"imagine_me_messages_sent"` // field 202
	ImagineMePromptsInitiatedCount int64 `wam:"imagine_me_prompts_initiated_count"` // field 203
	OppositePartyHasBusinessIntent bool `wam:"opposite_party_has_business_intent"` // field 204
	UserHasBusinessIntent bool `wam:"user_has_business_intent"` // field 205
	BottomSheetAnimatedSent int64 `wam:"bottom_sheet_animated_sent"` // field 206
	BottomSheetEditedAnimatedSent int64 `wam:"bottom_sheet_edited_animated_sent"` // field 207
	BottomSheetEditedSent int64 `wam:"bottom_sheet_edited_sent"` // field 208
	BottomSheetImagesEdited int64 `wam:"bottom_sheet_images_edited"` // field 209
	BottomSheetRegeneratedSent int64 `wam:"bottom_sheet_regenerated_sent"` // field 210
	IsMetaAiAssistant bool `wam:"is_meta_ai_assistant"` // field 211
	IsAContactAtThreadCreation bool `wam:"is_a_contact_at_thread_creation"` // field 213
	GoogleSearchClick int64 `wam:"google_search_click"` // field 214
	GoogleSearchShow int64 `wam:"google_search_show"` // field 215
	HasReplied1On1 bool `wam:"has_replied1_on1"` // field 216
	OppositePartyHasProfilePhoto bool `wam:"opposite_party_has_profile_photo"` // field 217
	SharesCommonGroup bool `wam:"shares_common_group"` // field 218
	DeviceLanguage string `wam:"device_language"` // field 219
	BottomSheetMemuImagesGenerated int64 `wam:"bottom_sheet_memu_images_generated"` // field 220
	BottomSheetMemuInitiated int64 `wam:"bottom_sheet_memu_initiated"` // field 221
	BottomSheetMemuMessagesSent int64 `wam:"bottom_sheet_memu_messages_sent"` // field 222
	ThreadIdMonthly string `wam:"thread_id_monthly"` // field 223
	AiChatOrigins AICHATORIGINSTYPE `wam:"ai_chat_origins"` // field 224
	GroupLimitSharingOnCnt int64 `wam:"group_limit_sharing_on_cnt"` // field 225
	LimitSharingOption bool `wam:"limit_sharing_option"` // field 226
	OppositePartyLimitSharingOption bool `wam:"opposite_party_limit_sharing_option"` // field 227
	HasUsernamePin bool `wam:"has_username_pin"` // field 228
	FmxNotMvClicks int64 `wam:"fmx_not_mv_clicks"` // field 229
	IsBizMvFrictionEligible bool `wam:"is_biz_mv_friction_eligible"` // field 230
	NotMvImpressions int64 `wam:"not_mv_impressions"` // field 231
	FmxNotMvBottomSheetDismissedCount int64 `wam:"fmx_not_mv_bottom_sheet_dismissed_count"` // field 234
	FmxNotMvBottomSheetGetMvButtonClicks int64 `wam:"fmx_not_mv_bottom_sheet_get_mv_button_clicks"` // field 235
	FmxNotMvBottomSheetGetMvButtonImpressions int64 `wam:"fmx_not_mv_bottom_sheet_get_mv_button_impressions"` // field 236
	FmxNotMvBottomSheetImpressions int64 `wam:"fmx_not_mv_bottom_sheet_impressions"` // field 237
	FmxNotMvBottomSheetLearnMoreButtonClicks int64 `wam:"fmx_not_mv_bottom_sheet_learn_more_button_clicks"` // field 238
	OppositePartyHasBadge bool `wam:"opposite_party_has_badge"` // field 240
	MessagesReceivedWithEnabledReadReceipt int64 `wam:"messages_received_with_enabled_read_receipt"` // field 245
	MatchedMessagesMarkedAsReadWithDeltaTime string `wam:"matched_messages_marked_as_read_with_delta_time"` // field 246
	MatchedMessagesReadWithDeltaTime string `wam:"matched_messages_read_with_delta_time"` // field 247
	EphemeralMessagesExpired int64 `wam:"ephemeral_messages_expired"` // field 248
	GroupStatusLikesOthersToOthers int64 `wam:"group_status_likes_others_to_others"` // field 249
	GroupStatusLikesOthersToOwn int64 `wam:"group_status_likes_others_to_own"` // field 250
	GroupStatusLikesOwnToOthers int64 `wam:"group_status_likes_own_to_others"` // field 251
	GroupStatusLikesOwnToOwn int64 `wam:"group_status_likes_own_to_own"` // field 252
	GroupStatusRepliesOthersToOthers int64 `wam:"group_status_replies_others_to_others"` // field 253
	GroupStatusRepliesOthersToOwn int64 `wam:"group_status_replies_others_to_own"` // field 254
	GroupStatusRepliesOwnToOthers int64 `wam:"group_status_replies_own_to_others"` // field 255
	GroupStatusRepliesOwnToOwn int64 `wam:"group_status_replies_own_to_own"` // field 256
	IsGuestThread bool `wam:"is_guest_thread"` // field 257
	IsUsernameThread bool `wam:"is_username_thread"` // field 258
	IsUsernameThreadAtCreation bool `wam:"is_username_thread_at_creation"` // field 259
	IsManagedAccount bool `wam:"is_managed_account"` // field 260
	IsNewManagedAccountEmIgnored bool `wam:"is_new_managed_account_em_ignored"` // field 261
	TombstoneEphemeralMessagesReceived int64 `wam:"tombstone_ephemeral_messages_received"` // field 262
	TombstoneViewOnceMessagesReceived int64 `wam:"tombstone_view_once_messages_received"` // field 263
	TombstoneAiFutureproofedMessagesReceived int64 `wam:"tombstone_ai_futureproofed_messages_received"` // field 264
}