const WamAndroidMessageSendPerf = 1994 // channel: regular

type AndroidMessageSendPerfEvent struct {
	DurationT string `wam:"duration_t"` // field 1
	SendStage CLIENTMESSAGESENDSTAGE `wam:"send_stage"` // field 2
	MediaType MEDIATYPE `wam:"media_type"` // field 3
	MessageType MESSAGETYPE `wam:"message_type"` // field 4
	IsMessageForward bool `wam:"is_message_forward"` // field 8
	IsMessageFanout bool `wam:"is_message_fanout"` // field 9
	SendRetryCount int64 `wam:"send_retry_count"` // field 10
	DurationAbs string `wam:"duration_abs"` // field 11
	DurationRelative string `wam:"duration_relative"` // field 12
	SendCount int64 `wam:"send_count"` // field 13
	NetworkWasDisconnected bool `wam:"network_was_disconnected"` // field 14
	FetchPrekeys bool `wam:"fetch_prekeys"` // field 15
	AppRestart bool `wam:"app_restart"` // field 16
	GroupSizeBucket CLIENTGROUPSIZEBUCKET `wam:"group_size_bucket"` // field 17
	JobsInQueue int64 `wam:"jobs_in_queue"` // field 18
	ThreadsInExecution int64 `wam:"threads_in_execution"` // field 19
	TargetDeviceGroupSizeBucket CLIENTGROUPSIZEBUCKET `wam:"target_device_group_size_bucket"` // field 20
	FetchPrekeysPercentage int64 `wam:"fetch_prekeys_percentage"` // field 21
	SenderKeyDistributionCountPercentage int64 `wam:"sender_key_distribution_count_percentage"` // field 23
	IsRevokeMessage bool `wam:"is_revoke_message"` // field 24
	SessionsMissingWhenComposing bool `wam:"sessions_missing_when_composing"` // field 25
	DeviceSizeBucket SIZEBUCKET `wam:"device_size_bucket"` // field 26
	IsE2eBackfill bool `wam:"is_e2e_backfill"` // field 27
	PrekeysEligibleForPrallelProcessing bool `wam:"prekeys_eligible_for_prallel_processing"` // field 28
	IsViewOnce bool `wam:"is_view_once"` // field 29
	MessageIsFirstUserMessage bool `wam:"message_is_first_user_message"` // field 30
	MessageIsInvisible bool `wam:"message_is_invisible"` // field 31
	BucketedSenderKeyDistributionCountPercentage int64 `wam:"bucketed_sender_key_distribution_count_percentage"` // field 32
	IsDirectedMessage bool `wam:"is_directed_message"` // field 33
	PhoneCores int64 `wam:"phone_cores"` // field 34
	BucketedSenderKeyDistributionHashTime int64 `wam:"bucketed_sender_key_distribution_hash_time"` // field 35
	DeviceCount int64 `wam:"device_count"` // field 36
	ParticipantCount int64 `wam:"participant_count"` // field 37
	TypeOfGroup TYPEOFGROUPENUM `wam:"type_of_group"` // field 38
	ReceiverDeviceCount int64 `wam:"receiver_device_count"` // field 39
	SenderDeviceCount int64 `wam:"sender_device_count"` // field 40
	IsLid bool `wam:"is_lid"` // field 41
	EditType EDITTYPE `wam:"edit_type"` // field 42
	RunningTasks string `wam:"running_tasks"` // field 44
	InvisibleMessageCategory INVISIBLEMESSAGECATEGORYTYPE `wam:"invisible_message_category"` // field 45
	UserToDeviceSizeBucket string `wam:"user_to_device_size_bucket"` // field 46
	AgentEngagementType AGENTENGAGEMENTENUMTYPE `wam:"agent_engagement_type"` // field 47
	BotType BOTTYPE `wam:"bot_type"` // field 48
	IsPq bool `wam:"is_pq"` // field 49
	MessageSendResult MESSAGESENDRESULTTYPE `wam:"message_send_result"` // field 50
}