const WamPaymentsUserAction = 2162 // channel: regular

type PaymentsUserActionEvent struct {
	PaymentsEventId string `wam:"payments_event_id"` // field 1
	PaymentsCountryCode string `wam:"payments_country_code"` // field 2
	PaymentActionType PAYMENTACTIONTYPES `wam:"payment_action_type"` // field 3
	ActionTarget PAYMENTACTIONTARGETS `wam:"action_target"` // field 4
	Screen string `wam:"screen"` // field 5
	Referral string `wam:"referral"` // field 6
	PaymentMode PAYMENTMODETYPES `wam:"payment_mode"` // field 7
	UpiPaymentsPspId UPIPAYMENTSPSPIDTYPE `wam:"upi_payments_psp_id"` // field 8
	PaymentsErrorCode string `wam:"payments_error_code"` // field 9
	PaymentsErrorText string `wam:"payments_error_text"` // field 10
	PaymentsBankId string `wam:"payments_bank_id"` // field 11
	PaymentsResponseResult PAYMENTSRESPONSERESULTTYPE `wam:"payments_response_result"` // field 12
	PaymentsAccountsExist bool `wam:"payments_accounts_exist"` // field 13
	PaymentsSmsProviderRetryCount int64 `wam:"payments_sms_provider_retry_count"` // field 14
	PaymentSmsProviderNumber string `wam:"payment_sms_provider_number"` // field 15
	PaymentsSmsRequestRetryCount int64 `wam:"payments_sms_request_retry_count"` // field 16
	PaymentsRequestName PAYMENTSREQUESTNAMETYPE `wam:"payments_request_name"` // field 17
	PaymentsBanksSearchActivated bool `wam:"payments_banks_search_activated"` // field 18
	PaymentsBanksSearchString string `wam:"payments_banks_search_string"` // field 19
	PaymentsBanksSearchSelected bool `wam:"payments_banks_search_selected"` // field 20
	PaymentsBanksScrolled bool `wam:"payments_banks_scrolled"` // field 21
	PaymentsBanksRowSelected int64 `wam:"payments_banks_row_selected"` // field 22
	PaymentNumberOfAccountsAvailable int64 `wam:"payment_number_of_accounts_available"` // field 23
	PaymentAccountRowSelected int64 `wam:"payment_account_row_selected"` // field 24
	PaymentsBanksSelectedName string `wam:"payments_banks_selected_name"` // field 25
	PaymentsRequestRetryCount int64 `wam:"payments_request_retry_count"` // field 26
	PaymentsRequestRetryTimeDelaySeconds int64 `wam:"payments_request_retry_time_delay_seconds"` // field 27
	PaymentsUpiCheckPinErrorReason PAYMENTSUPICHECKPINUSERERRORREASONTYPE `wam:"payments_upi_check_pin_error_reason"` // field 28
	PaymentsHasMultipleSims bool `wam:"payments_has_multiple_sims"` // field 29
	PaymentsVerifyCardResult PAYMENTSVERIFYCARDRESULTTYPE `wam:"payments_verify_card_result"` // field 30
	PaymentsContactsBucket PAYMENTSCONTACTSBUCKETTYPE `wam:"payments_contacts_bucket"` // field 31
	PaymentNumberOfPeopleInvited int64 `wam:"payment_number_of_people_invited"` // field 32
	PaymentPinSetUp bool `wam:"payment_pin_set_up"` // field 33
	PaymentSent bool `wam:"payment_sent"` // field 34
	QueryParams string `wam:"query_params"` // field 35
	PaymentsIsOrder bool `wam:"payments_is_order"` // field 36
	ReferralContext string `wam:"referral_context"` // field 37
	PaymentsOrderType string `wam:"payments_order_type"` // field 38
	PaymentsP2mPaymentConfigId string `wam:"payments_p2m_payment_config_id"` // field 39
	PaymentsIsMandate bool `wam:"payments_is_mandate"` // field 40
	PaymentsMandate string `wam:"payments_mandate"` // field 41
	PaymentsIqCallStatus PAYMENTSIQCALL `wam:"payments_iq_call_status"` // field 42
	MerchantType MERCHANTTYPETYPE `wam:"merchant_type"` // field 43
	P2mType P2MTYPETYPE `wam:"p2m_type"` // field 44
	PaymentTransactionStatus PAYMENTTRANSACTIONSTATUSTYPE `wam:"payment_transaction_status"` // field 45
	PreviousScreenName string `wam:"previous_screen_name"` // field 46
	PaymentsErrorTitle string `wam:"payments_error_title"` // field 47
	CustomPaymentMethodsSyncStatus CUSTOMPAYMENTMETHODSSYNCSTATUS `wam:"custom_payment_methods_sync_status"` // field 48
}