const WamMdFatalError = 2304 // channel: regular

type MdFatalErrorEvent struct {
	MdFatalErrorCode MDSYNCDFATALERRORCODE `wam:"md_fatal_error_code"` // field 1
	Collection COLLECTION `wam:"collection"` // field 2
	IsBootstrap bool `wam:"is_bootstrap"` // field 3
	PatchVersion int64 `wam:"patch_version"` // field 5
	TimeSincePairingMs int64 `wam:"time_since_pairing_ms"` // field 6
	TimeSinceRefreshMs int64 `wam:"time_since_refresh_ms"` // field 7
	TimeSinceTabTakeoverMs int64 `wam:"time_since_tab_takeover_ms"` // field 8
	PatchSnapshotMutationCount int64 `wam:"patch_snapshot_mutation_count"` // field 9
	SourceType MDSYNCDFATALERRORSOURCE `wam:"source_type"` // field 10
	DaysSinceLastPeriodicSync int64 `wam:"days_since_last_periodic_sync"` // field 11
	HoursSinceFirstFiniteFailure int64 `wam:"hours_since_first_finite_failure"` // field 12
	MailboxAgeDays int64 `wam:"mailbox_age_days"` // field 13
	CurrentPrimaryAppVersion string `wam:"current_primary_app_version"` // field 14
	SessionStartPrimaryAppVersion string `wam:"session_start_primary_app_version"` // field 15
	IsFatal bool `wam:"is_fatal"` // field 16
	IsWebLthashConsistent bool `wam:"is_web_lthash_consistent"` // field 17
	MacFatalCollectionNameMismatch bool `wam:"mac_fatal_collection_name_mismatch"` // field 18
	MacFatalCurrentLthashMismatch bool `wam:"mac_fatal_current_lthash_mismatch"` // field 19
	MacFatalFirstTwoBytesFromAHashOfSnapshotMacKeyMismatch bool `wam:"mac_fatal_first_two_bytes_from_a_hash_of_snapshot_mac_key_mismatch"` // field 20
	MacFatalNewLthashMismatch bool `wam:"mac_fatal_new_lthash_mismatch"` // field 21
	MacFatalPatchVersionMismatch bool `wam:"mac_fatal_patch_version_mismatch"` // field 22
	IsPatchSenderPrimary bool `wam:"is_patch_sender_primary"` // field 23
	IsPreviousPatchAnIncomingPatch bool `wam:"is_previous_patch_an_incoming_patch"` // field 24
	IsPreviousPatchSenderPrimary bool `wam:"is_previous_patch_sender_primary"` // field 25
	MacFatalDidPreviousPatchFailPostSaveValidation bool `wam:"mac_fatal_did_previous_patch_fail_post_save_validation"` // field 26
	MacFatalNewLthashSubtractMismatch bool `wam:"mac_fatal_new_lthash_subtract_mismatch"` // field 27
	MacFatalNumberAddMismatch bool `wam:"mac_fatal_number_add_mismatch"` // field 28
	MacFatalNumberHasOverrideMutation bool `wam:"mac_fatal_number_has_override_mutation"` // field 29
	MacFatalNumberNumAddMutation int64 `wam:"mac_fatal_number_num_add_mutation"` // field 30
	MacFatalNumberNumRemoveMutation int64 `wam:"mac_fatal_number_num_remove_mutation"` // field 31
	MacFatalNumberOverrideMismatch bool `wam:"mac_fatal_number_override_mismatch"` // field 32
	MacFatalNumberRemoveMismatch bool `wam:"mac_fatal_number_remove_mismatch"` // field 33
	MacFatalPreviousPatchNewLthashToCurrentPatchCurrentLthash bool `wam:"mac_fatal_previous_patch_new_lthash_to_current_patch_current_lthash"` // field 34
	MacFatalSenderCurrentLthashToLocalCalculatedCurrentLthashMismatch bool `wam:"mac_fatal_sender_current_lthash_to_local_calculated_current_lthash_mismatch"` // field 35
	MacFatalDidUseMacFetchFallback bool `wam:"mac_fatal_did_use_mac_fetch_fallback"` // field 36
	MacFatalHasMissingRemove bool `wam:"mac_fatal_has_missing_remove"` // field 37
	DidBootstrapFromSnapshot bool `wam:"did_bootstrap_from_snapshot"` // field 38
	IsSenderIndexSameAsPreviousSenderIndex bool `wam:"is_sender_index_same_as_previous_sender_index"` // field 39
	IsThereAnotherSyncdCompanion bool `wam:"is_there_another_syncd_companion"` // field 40
	AppSessionId string `wam:"app_session_id"` // field 41
	CompanionSessionIds string `wam:"companion_session_ids"` // field 42
	MdCompanionDeviceAccountType MDCOMPANIONDEVICEACCOUNTTYPE `wam:"md_companion_device_account_type"` // field 43
	MdRegAttemptId string `wam:"md_reg_attempt_id"` // field 44
	SeqNumber int64 `wam:"seq_number"` // field 45
	AppContext string `wam:"app_context"` // field 46
	AppContextBitfield int64 `wam:"app_context_bitfield"` // field 47
	IsPureSyncdSession ISPURESYNCDSESSIONENUM `wam:"is_pure_syncd_session"` // field 48
	LidMigrationStage LIDMIGRATIONSTAGEENUM `wam:"lid_migration_stage"` // field 49
	RecoveryRequestDurationMs int64 `wam:"recovery_request_duration_ms"` // field 50
	RecoveryStatus RECOVERYSTATUSENUM `wam:"recovery_status"` // field 51
}