const WamJoinableCall = 2572 // channel: regular

type JoinableCallEvent struct {
	CallRandomId string `wam:"call_random_id"` // field 1
	LobbyEntryPoint LOBBYENTRYPOINTTYPE `wam:"lobby_entry_point"` // field 2
	IsRejoin bool `wam:"is_rejoin"` // field 3
	LobbyExit LOBBYEXITTYPE `wam:"lobby_exit"` // field 4
	LobbyExitNackCode int64 `wam:"lobby_exit_nack_code"` // field 5
	LegacyCallResult CALLRESULTTYPE `wam:"legacy_call_result"` // field 6
	LobbyVisibleT string `wam:"lobby_visible_t"` // field 7
	IsRering bool `wam:"is_rering"` // field 8
	JoinableDuringCall bool `wam:"joinable_during_call"` // field 9
	VideoEnabled bool `wam:"video_enabled"` // field 10
	NumInvitedParticipants int64 `wam:"num_invited_participants"` // field 12
	NumConnectedPeers int64 `wam:"num_connected_peers"` // field 13
	IsPendingCall bool `wam:"is_pending_call"` // field 14
	JoinableAcceptBeforeLobbyAck bool `wam:"joinable_accept_before_lobby_ack"` // field 16
	JoinableEndCallBeforeLobbyAck bool `wam:"joinable_end_call_before_lobby_ack"` // field 17
	LobbyQueryWhileConnected bool `wam:"lobby_query_while_connected"` // field 18
	LobbyAckLatencyMs string `wam:"lobby_ack_latency_ms"` // field 19
	NumOutgoingRingingPeers int64 `wam:"num_outgoing_ringing_peers"` // field 20
	TimeSinceLastClientPollMinutes string `wam:"time_since_last_client_poll_minutes"` // field 21
	RejoinMissingDbMapping bool `wam:"rejoin_missing_db_mapping"` // field 22
	AcceptAckLatencyMs string `wam:"accept_ack_latency_ms"` // field 23
	IsLinkedGroupCall bool `wam:"is_linked_group_call"` // field 24
	HasSpamDialog bool `wam:"has_spam_dialog"` // field 26
	NseEnabled bool `wam:"nse_enabled"` // field 27
	NseOfflineQueueMs string `wam:"nse_offline_queue_ms"` // field 28
	ReceivedByNse bool `wam:"received_by_nse"` // field 29
	IsCallFull bool `wam:"is_call_full"` // field 30
	CallReplayerId string `wam:"call_replayer_id"` // field 31
	IsFromCallLink bool `wam:"is_from_call_link"` // field 32
	IsLinkJoin bool `wam:"is_link_join"` // field 33
	JoinAckLatencyMs string `wam:"join_ack_latency_ms"` // field 34
	QueryAckLatencyMs string `wam:"query_ack_latency_ms"` // field 35
	TimeSinceAcceptMs string `wam:"time_since_accept_ms"` // field 36
	GroupAcceptNoCriticalGroupUpdate bool `wam:"group_accept_no_critical_group_update"` // field 37
	GroupAcceptToCriticalGroupUpdateMs string `wam:"group_accept_to_critical_group_update_ms"` // field 38
	IsLinkCreator bool `wam:"is_link_creator"` // field 39
	IsScheduledCall bool `wam:"is_scheduled_call"` // field 40
	CallSide CALLSIDE `wam:"call_side"` // field 41
	HasScheduleExactAlarmPermission bool `wam:"has_schedule_exact_alarm_permission"` // field 42
	IsVoiceChat bool `wam:"is_voice_chat"` // field 43
	RandomScheduledId int64 `wam:"random_scheduled_id"` // field 44
	IsLidCall bool `wam:"is_lid_call"` // field 45
	IsPhashBased bool `wam:"is_phash_based"` // field 46
	IsUpgradedGroupCallBeforeConnected bool `wam:"is_upgraded_group_call_before_connected"` // field 47
	IsPhashMismatch bool `wam:"is_phash_mismatch"` // field 48
	LobbyOpenDurationMs int64 `wam:"lobby_open_duration_ms"` // field 49
	IsEventsLink bool `wam:"is_events_link"` // field 50
	CallLinkRandomId string `wam:"call_link_random_id"` // field 51
	IsWaitingRoomEnabled bool `wam:"is_waiting_room_enabled"` // field 52
	TimeInWaitingRoomMs int64 `wam:"time_in_waiting_room_ms"` // field 53
	IsOneOnOneCall bool `wam:"is_one_on_one_call"` // field 54
	IsDeviceSwitch bool `wam:"is_device_switch"` // field 55
	IsTransferRejoin bool `wam:"is_transfer_rejoin"` // field 56
}