const WamLwiScreen = 2772 // channel: regular

type LwiScreenEvent struct {
	LwiFlowId string `wam:"lwi_flow_id"` // field 1
	LwiEventSequenceNumber int64 `wam:"lwi_event_sequence_number"` // field 2
	ProductId string `wam:"product_id"` // field 3
	LwiScreenReference LWISCREENREFERENCE `wam:"lwi_screen_reference"` // field 4
	LwiScreenAction LWISCREENACTION `wam:"lwi_screen_action"` // field 5
	LwiAlertReason LWIALERTREASON `wam:"lwi_alert_reason"` // field 6
	UserHasLinkedFbPage bool `wam:"user_has_linked_fb_page"` // field 7
	SelectedProductsIdsList string `wam:"selected_products_ids_list"` // field 8
	DefaultAdsContentSelected LWIADSCONTENTTYPE `wam:"default_ads_content_selected"` // field 9
	UserHasCatalogItemsToPromote bool `wam:"user_has_catalog_items_to_promote"` // field 10
	UserHasStatusToPromote bool `wam:"user_has_status_to_promote"` // field 11
	CreateAdEnabled bool `wam:"create_ad_enabled"` // field 12
	PaymentMethodSet bool `wam:"payment_method_set"` // field 13
	UserProvidedFbConsent bool `wam:"user_provided_fb_consent"` // field 14
	LwiBudgetInLocal int64 `wam:"lwi_budget_in_local"` // field 15
	LwiCurrency string `wam:"lwi_currency"` // field 16
	LwiDefaultBudgetInLocal int64 `wam:"lwi_default_budget_in_local"` // field 17
	LwiDefaultDurationInDays int64 `wam:"lwi_default_duration_in_days"` // field 18
	LwiDefaultTargetingSpec LWIDEFAULTTARGETINGSPEC `wam:"lwi_default_targeting_spec"` // field 19
	LwiDurationInDays int64 `wam:"lwi_duration_in_days"` // field 20
	LwiTargetingSpec string `wam:"lwi_targeting_spec"` // field 21
	LwiAdsIdentityType LWIADSIDENTITYTYPE `wam:"lwi_ads_identity_type"` // field 22
	UserWentThroughFbWebLogin bool `wam:"user_went_through_fb_web_login"` // field 23
	LwiCtwaAdCtaType LWICTWAADCTATYPE `wam:"lwi_ctwa_ad_cta_type"` // field 24
	LwiCtwaAdStatusType LWICTWAADSTATUSTYPE `wam:"lwi_ctwa_ad_status_type"` // field 25
	LwiTotalCtwaAds int64 `wam:"lwi_total_ctwa_ads"` // field 26
	LwiIsFbAppInstalled bool `wam:"lwi_is_fb_app_installed"` // field 27
	LwiViewerHasEditPermission bool `wam:"lwi_viewer_has_edit_permission"` // field 28
	LwiExtras string `wam:"lwi_extras"` // field 30
	UsedSavedAudience bool `wam:"used_saved_audience"` // field 31
	LwiViewerHasPromotePermission bool `wam:"lwi_viewer_has_promote_permission"` // field 32
	AlertCount int64 `wam:"alert_count"` // field 33
	UserHasSeenRecommendedBudget bool `wam:"user_has_seen_recommended_budget"` // field 34
	UserHasAdvancedAudience bool `wam:"user_has_advanced_audience"` // field 35
	BillingStatus BILLINGSTATUS `wam:"billing_status"` // field 36
	ValidationStatus VALIDATIONSTATUS `wam:"validation_status"` // field 37
	OnboardingEntryPoint ONBOARDINGENTRYPOINT `wam:"onboarding_entry_point"` // field 38
	ItemCount int64 `wam:"item_count"` // field 39
	AdMediaTypeSelected LWIADMEDIATYPE `wam:"ad_media_type_selected"` // field 40
	AdContentRecommendation ADCONTENTRECOMMENDATIONTYPE `wam:"ad_content_recommendation"` // field 41
	AdsContentSelected LWIADSCONTENTTYPE `wam:"ads_content_selected"` // field 42
	UserHasBpCredentials bool `wam:"user_has_bp_credentials"` // field 43
	WaAdAccountId string `wam:"wa_ad_account_id"` // field 44
	AudienceType AUDIENCETYPE `wam:"audience_type"` // field 45
	LwiAdCampaignId string `wam:"lwi_ad_campaign_id"` // field 46
	MediaEdited bool `wam:"media_edited"` // field 49
	TotalMediaCount int64 `wam:"total_media_count"` // field 50
	LwiIsIgAppInstalled bool `wam:"lwi_is_ig_app_installed"` // field 51
	LwiMaxDurationInDays int64 `wam:"lwi_max_duration_in_days"` // field 52
	LwiMinDurationInDays int64 `wam:"lwi_min_duration_in_days"` // field 53
	LwiBudgetOptionsInLocal string `wam:"lwi_budget_options_in_local"` // field 54
	LwiLocationTypesSetOnAudienceSelection string `wam:"lwi_location_types_set_on_audience_selection"` // field 55
	UserHasChangedDefaultCityLevelAudience bool `wam:"user_has_changed_default_city_level_audience"` // field 56
	DefaultAudienceLocationType DEFAULTAUDIENCELOCATIONTYPE `wam:"default_audience_location_type"` // field 57
	CtwaAdAccountType CTWAADACCOUNTTYPE `wam:"ctwa_ad_account_type"` // field 58
	CtwaLoginType CTWALOGINTYPE `wam:"ctwa_login_type"` // field 59
	UserHasMultisourceMedia bool `wam:"user_has_multisource_media"` // field 60
	AdMediaTemplateName string `wam:"ad_media_template_name"` // field 61
	LwiAdCreationAccountConsentFlow LWIADCREATIONACCOUNTCONSENTFLOW `wam:"lwi_ad_creation_account_consent_flow"` // field 63
	SmbiAdCreationAccessTokenSource SMBIADCREATIONACCESSTOKENSOURCE `wam:"smbi_ad_creation_access_token_source"` // field 64
	UserHasFbMediaToPromote bool `wam:"user_has_fb_media_to_promote"` // field 65
	MediaSource MEDIASOURCE `wam:"media_source"` // field 66
	UserHasMediaCarousel bool `wam:"user_has_media_carousel"` // field 67
}