const WamPttDaily = 2938 // channel: regular

type PttDailyEvent struct {
	PttRecordIndividual int64 `wam:"ptt_record_individual"` // field 1
	PttRecordGroup int64 `wam:"ptt_record_group"` // field 2
	PttRecordBroadcast int64 `wam:"ptt_record_broadcast"` // field 3
	PttSendIndividual int64 `wam:"ptt_send_individual"` // field 4
	PttSendGroup int64 `wam:"ptt_send_group"` // field 5
	PttSendBroadcast int64 `wam:"ptt_send_broadcast"` // field 6
	PttCancelIndividual int64 `wam:"ptt_cancel_individual"` // field 7
	PttCancelGroup int64 `wam:"ptt_cancel_group"` // field 8
	PttCancelBroadcast int64 `wam:"ptt_cancel_broadcast"` // field 9
	PttLockIndividual int64 `wam:"ptt_lock_individual"` // field 10
	PttLockGroup int64 `wam:"ptt_lock_group"` // field 11
	PttLockBroadcast int64 `wam:"ptt_lock_broadcast"` // field 12
	PttDraftReviewIndividual int64 `wam:"ptt_draft_review_individual"` // field 13
	PttDraftReviewGroup int64 `wam:"ptt_draft_review_group"` // field 14
	PttDraftReviewBroadcast int64 `wam:"ptt_draft_review_broadcast"` // field 15
	PttPlaybackIndividual int64 `wam:"ptt_playback_individual"` // field 16
	PttPlaybackGroup int64 `wam:"ptt_playback_group"` // field 17
	PttPlaybackBroadcast int64 `wam:"ptt_playback_broadcast"` // field 18
	PttFastplaybackIndividual int64 `wam:"ptt_fastplayback_individual"` // field 19
	PttFastplaybackGroup int64 `wam:"ptt_fastplayback_group"` // field 20
	PttFastplaybackBroadcast int64 `wam:"ptt_fastplayback_broadcast"` // field 21
	PttPausedRecordBroadcast int64 `wam:"ptt_paused_record_broadcast"` // field 22
	PttPausedRecordGroup int64 `wam:"ptt_paused_record_group"` // field 23
	PttPausedRecordIndividual int64 `wam:"ptt_paused_record_individual"` // field 24
	PttStopTapBroadcast int64 `wam:"ptt_stop_tap_broadcast"` // field 25
	PttStopTapGroup int64 `wam:"ptt_stop_tap_group"` // field 26
	PttStopTapIndividual int64 `wam:"ptt_stop_tap_individual"` // field 27
	PttOutOfChatBroadcast int64 `wam:"ptt_out_of_chat_broadcast"` // field 29
	PttOutOfChatGroup int64 `wam:"ptt_out_of_chat_group"` // field 30
	PttOutOfChatIndividual int64 `wam:"ptt_out_of_chat_individual"` // field 31
	PttCancelNewsletter int64 `wam:"ptt_cancel_newsletter"` // field 32
	PttDraftReviewNewsletter int64 `wam:"ptt_draft_review_newsletter"` // field 33
	PttFastplaybackNewsletter int64 `wam:"ptt_fastplayback_newsletter"` // field 34
	PttLockNewsletter int64 `wam:"ptt_lock_newsletter"` // field 35
	PttOutOfChatNewsletter int64 `wam:"ptt_out_of_chat_newsletter"` // field 36
	PttPausedRecordNewsletter int64 `wam:"ptt_paused_record_newsletter"` // field 37
	PttPlaybackNewsletter int64 `wam:"ptt_playback_newsletter"` // field 38
	PttRecordNewsletter int64 `wam:"ptt_record_newsletter"` // field 39
	PttSendNewsletter int64 `wam:"ptt_send_newsletter"` // field 40
	PttStopTapNewsletter int64 `wam:"ptt_stop_tap_newsletter"` // field 41
	PttCancelInterop int64 `wam:"ptt_cancel_interop"` // field 42
	PttDraftReviewInterop int64 `wam:"ptt_draft_review_interop"` // field 43
	PttFastplaybackInterop int64 `wam:"ptt_fastplayback_interop"` // field 44
	PttLockInterop int64 `wam:"ptt_lock_interop"` // field 45
	PttOutOfChatInterop int64 `wam:"ptt_out_of_chat_interop"` // field 46
	PttPausedRecordInterop int64 `wam:"ptt_paused_record_interop"` // field 47
	PttPlaybackInterop int64 `wam:"ptt_playback_interop"` // field 48
	PttRecordInterop int64 `wam:"ptt_record_interop"` // field 49
	PttSendInterop int64 `wam:"ptt_send_interop"` // field 50
	PttStopTapInterop int64 `wam:"ptt_stop_tap_interop"` // field 51
}