const WamOfflineResume = 3112 // channel: regular

type OfflineResumeEvent struct {
	ChatThreadCount int64 `wam:"chat_thread_count"` // field 1
	IsOfflineCompleteMissed bool `wam:"is_offline_complete_missed"` // field 2
	LastStanzaT string `wam:"last_stanza_t"` // field 3
	MainScreenLoadT string `wam:"main_screen_load_t"` // field 4
	OfflineDecryptErrorCount int64 `wam:"offline_decrypt_error_count"` // field 5
	OfflineMessageCount int64 `wam:"offline_message_count"` // field 6
	OfflineNotificationCount int64 `wam:"offline_notification_count"` // field 7
	OfflinePreviewT string `wam:"offline_preview_t"` // field 8
	OfflineReceiptCount int64 `wam:"offline_receipt_count"` // field 9
	OfflineSizeBytes int64 `wam:"offline_size_bytes"` // field 10
	PageLoadT string `wam:"page_load_t"` // field 11
	SocketConnectT string `wam:"socket_connect_t"` // field 12
	IsResumeInForeground bool `wam:"is_resume_in_foreground"` // field 13
	MailboxAge int64 `wam:"mailbox_age"` // field 14
	OnTrickleMode bool `wam:"on_trickle_mode"` // field 15
	ExpectedOfflineMessageCount int64 `wam:"expected_offline_message_count"` // field 17
	ExpectedOfflineNotificationCount int64 `wam:"expected_offline_notification_count"` // field 18
	ExpectedOfflineReceiptCount int64 `wam:"expected_offline_receipt_count"` // field 19
	OfflineProcessingT string `wam:"offline_processing_t"` // field 20
	OfflineResumeResult OFFLINERESUMERESULTTYPE `wam:"offline_resume_result"` // field 21
	IsRunningFromServiceExtension bool `wam:"is_running_from_service_extension"` // field 22
	ExpectedOfflineCallCount int64 `wam:"expected_offline_call_count"` // field 23
	OfflineCallCount int64 `wam:"offline_call_count"` // field 24
	PassiveModeT string `wam:"passive_mode_t"` // field 25
	PreackCallCount int64 `wam:"preack_call_count"` // field 26
	PreackMessageCount int64 `wam:"preack_message_count"` // field 27
	PreackNotificationCount int64 `wam:"preack_notification_count"` // field 28
	PreackReceiptCount int64 `wam:"preack_receipt_count"` // field 29
	ProcessedCallCount int64 `wam:"processed_call_count"` // field 30
	ProcessedMessageCount int64 `wam:"processed_message_count"` // field 31
	ProcessedNotificationCount int64 `wam:"processed_notification_count"` // field 32
	ProcessedReceiptCount int64 `wam:"processed_receipt_count"` // field 33
	TransientOfflineSessionId string `wam:"transient_offline_session_id"` // field 34
	AffectedBySleepMode bool `wam:"affected_by_sleep_mode"` // field 35
	AttemptNumber int64 `wam:"attempt_number"` // field 36
	IsResumeStartedInForeground bool `wam:"is_resume_started_in_foreground"` // field 37
	LogoutSessionId int64 `wam:"logout_session_id"` // field 38
	DbDurationT string `wam:"db_duration_t"` // field 39
	DbMainThreadDurationT string `wam:"db_main_thread_duration_t"` // field 40
	DbMainThreadReadsCount int64 `wam:"db_main_thread_reads_count"` // field 41
	DbMainThreadWritesCount int64 `wam:"db_main_thread_writes_count"` // field 42
	DbReadsCount int64 `wam:"db_reads_count"` // field 43
	DbWritesCount int64 `wam:"db_writes_count"` // field 44
	Disconnected bool `wam:"disconnected"` // field 45
	OfflineSessionT string `wam:"offline_session_t"` // field 46
	PreacksCount int64 `wam:"preacks_count"` // field 47
	RunningTasks string `wam:"running_tasks"` // field 48
	AppContext string `wam:"app_context"` // field 49
	AppContextBitfield int64 `wam:"app_context_bitfield"` // field 50
	QueuedMessageCount int64 `wam:"queued_message_count"` // field 51
	QueuedNotificationCount int64 `wam:"queued_notification_count"` // field 52
	QueuedReceiptCount int64 `wam:"queued_receipt_count"` // field 53
	NseMergeT string `wam:"nse_merge_t"` // field 54
	ChatQueueSize int64 `wam:"chat_queue_size"` // field 55
	E2eeQueueSize int64 `wam:"e2ee_queue_size"` // field 56
	UnorderedQueueSize int64 `wam:"unordered_queue_size"` // field 57
}