const WamQbmIncomingMessage = 3790 // channel: regular

type QbmIncomingMessageEvent struct {
	ChatsFolderType CHATSFOLDERTYPE `wam:"chats_folder_type"` // field 1
	ContactType CONTACTTYPE `wam:"contact_type"` // field 2
	KeepChatsArchivedEnabled bool `wam:"keep_chats_archived_enabled"` // field 3
	Muted bool `wam:"muted"` // field 4
	NotificationEnabled bool `wam:"notification_enabled"` // field 5
	QbmFlag QBMFLAG `wam:"qbm_flag"` // field 6
	MessageTypeStr string `wam:"message_type_str"` // field 7
	ThreadIdHmac string `wam:"thread_id_hmac"` // field 8
	ReadReceiptsEnabled bool `wam:"read_receipts_enabled"` // field 9
	CompanionDevices int64 `wam:"companion_devices"` // field 10
	LastOutgoingMessageDeltaTime int64 `wam:"last_outgoing_message_delta_time"` // field 11
	QbmFlagStr string `wam:"qbm_flag_str"` // field 12
	LastOutgoingMessageDeltaTimeReceived int64 `wam:"last_outgoing_message_delta_time_received"` // field 13
	HsmTagStr string `wam:"hsm_tag_str"` // field 14
	IsFromAdsManagerMm bool `wam:"is_from_ads_manager_mm"` // field 15
	IsFromCapi bool `wam:"is_from_capi"` // field 16
	MessageIdHmac string `wam:"message_id_hmac"` // field 17
	MessageHasButton bool `wam:"message_has_button"` // field 18
	MessageHasUrl bool `wam:"message_has_url"` // field 19
	IsMuted bool `wam:"is_muted"` // field 20
	ApiDailyThreadCount7d int64 `wam:"api_daily_thread_count7d"` // field 21
	ApiMessageCount1d int64 `wam:"api_message_count1d"` // field 22
	ApiMessageCount7d int64 `wam:"api_message_count7d"` // field 23
	ApiUniqueThreadCount1d int64 `wam:"api_unique_thread_count1d"` // field 24
	ApiUniqueThreadCount7d int64 `wam:"api_unique_thread_count7d"` // field 25
	ApiTotalMessageCount int64 `wam:"api_total_message_count"` // field 26
	ApiTotalNewThreadCount int64 `wam:"api_total_new_thread_count"` // field 27
	SmbDailyThreadCount7d int64 `wam:"smb_daily_thread_count7d"` // field 28
	SmbMessageCount1d int64 `wam:"smb_message_count1d"` // field 29
	SmbMessageCount7d int64 `wam:"smb_message_count7d"` // field 30
	SmbTotalMessageCount int64 `wam:"smb_total_message_count"` // field 31
	SmbTotalNewThreadCount int64 `wam:"smb_total_new_thread_count"` // field 32
	SmbUniqueThreadCount1d int64 `wam:"smb_unique_thread_count1d"` // field 33
	SmbUniqueThreadCount7d int64 `wam:"smb_unique_thread_count7d"` // field 34
	ThreadCreationTime THREADCREATIONTIME `wam:"thread_creation_time"` // field 35
	BizTrustTier string `wam:"biz_trust_tier"` // field 36
	IsBizIntent bool `wam:"is_biz_intent"` // field 37
	IsBroadcastMessage bool `wam:"is_broadcast_message"` // field 38
	IsInsubContact bool `wam:"is_insub_contact"` // field 39
	EntSourceSubplatform string `wam:"ent_source_subplatform"` // field 40
	DecisionId string `wam:"decision_id"` // field 41
	ThreadLidHmac string `wam:"thread_lid_hmac"` // field 42
	FmxCardShown bool `wam:"fmx_card_shown"` // field 43
	IsOba bool `wam:"is_oba"` // field 44
	ButtonValueJsonArray string `wam:"button_value_json_array"` // field 45
	MessageFieldJsonArray string `wam:"message_field_json_array"` // field 46
	SubmessageFieldJsonArray string `wam:"submessage_field_json_array"` // field 47
	BodyUrlCountInt int64 `wam:"body_url_count_int"` // field 52
	BodyUrlUniqueCountInt int64 `wam:"body_url_unique_count_int"` // field 53
	CtaUrlUniqueCountInt int64 `wam:"cta_url_unique_count_int"` // field 54
	UrlUniqueCountInt int64 `wam:"url_unique_count_int"` // field 55
	IsCoex bool `wam:"is_coex"` // field 56
	IsThroughDecisionService bool `wam:"is_through_decision_service"` // field 57
	GapRules string `wam:"gap_rules"` // field 58
	GeEvaluationTimestamp int64 `wam:"ge_evaluation_timestamp"` // field 59
	IasEntryPoint SIGNUPENTRYPOINT `wam:"ias_entry_point"` // field 60
	IasOptinDs string `wam:"ias_optin_ds"` // field 61
	IsIasSubscriber bool `wam:"is_ias_subscriber"` // field 62
	IsFromPill bool `wam:"is_from_pill"` // field 63
	PillEntryPoint PILLENTRYPOINT `wam:"pill_entry_point"` // field 64
}