const WamQbmMessageRead = 3792 // channel: regular

type QbmMessageReadEvent struct {
	ChatsFolderType CHATSFOLDERTYPE `wam:"chats_folder_type"` // field 1
	ContactType CONTACTTYPE `wam:"contact_type"` // field 2
	DeltaTime int64 `wam:"delta_time"` // field 3
	QbmFlag QBMFLAG `wam:"qbm_flag"` // field 4
	ReadSource READSOURCE `wam:"read_source"` // field 5
	MessageTypeStr string `wam:"message_type_str"` // field 6
	ThreadIdHmac string `wam:"thread_id_hmac"` // field 7
	DeltaTimeReceived int64 `wam:"delta_time_received"` // field 8
	HsmTagStr string `wam:"hsm_tag_str"` // field 9
	IsFromAdsManagerMm bool `wam:"is_from_ads_manager_mm"` // field 10
	IsFromCapi bool `wam:"is_from_capi"` // field 11
	ReadReceiptsEnabled bool `wam:"read_receipts_enabled"` // field 12
	MessageIdHmac string `wam:"message_id_hmac"` // field 13
	IsBulkAction bool `wam:"is_bulk_action"` // field 14
	IsMuted bool `wam:"is_muted"` // field 15
	MessageHasButton bool `wam:"message_has_button"` // field 16
	MessageHasUrl bool `wam:"message_has_url"` // field 17
	ApiDailyThreadCount7d int64 `wam:"api_daily_thread_count7d"` // field 18
	ApiMessageCount1d int64 `wam:"api_message_count1d"` // field 19
	ApiMessageCount7d int64 `wam:"api_message_count7d"` // field 20
	ApiUniqueThreadCount1d int64 `wam:"api_unique_thread_count1d"` // field 21
	ApiUniqueThreadCount7d int64 `wam:"api_unique_thread_count7d"` // field 22
	ApiTotalMessageCount int64 `wam:"api_total_message_count"` // field 23
	ApiTotalNewThreadCount int64 `wam:"api_total_new_thread_count"` // field 24
	SmbDailyThreadCount7d int64 `wam:"smb_daily_thread_count7d"` // field 25
	SmbMessageCount1d int64 `wam:"smb_message_count1d"` // field 26
	SmbMessageCount7d int64 `wam:"smb_message_count7d"` // field 27
	SmbTotalMessageCount int64 `wam:"smb_total_message_count"` // field 28
	SmbTotalNewThreadCount int64 `wam:"smb_total_new_thread_count"` // field 29
	SmbUniqueThreadCount1d int64 `wam:"smb_unique_thread_count1d"` // field 30
	SmbUniqueThreadCount7d int64 `wam:"smb_unique_thread_count7d"` // field 31
	ThreadCreationTime THREADCREATIONTIME `wam:"thread_creation_time"` // field 32
	ThreadDwellTime int64 `wam:"thread_dwell_time"` // field 33
	BizTrustTier string `wam:"biz_trust_tier"` // field 34
	IsInsubContact bool `wam:"is_insub_contact"` // field 35
	ThumbnailType THUMBNAILTYPE `wam:"thumbnail_type"` // field 36
	IsBizIntent bool `wam:"is_biz_intent"` // field 37
	IsBroadcastMessage bool `wam:"is_broadcast_message"` // field 38
	EntSourceSubplatform string `wam:"ent_source_subplatform"` // field 39
	DecisionId string `wam:"decision_id"` // field 40
	CompanionDevices int64 `wam:"companion_devices"` // field 41
	ThreadLidHmac string `wam:"thread_lid_hmac"` // field 42
	IsOba bool `wam:"is_oba"` // field 43
	ButtonValueJsonArray string `wam:"button_value_json_array"` // field 44
	MessageFieldJsonArray string `wam:"message_field_json_array"` // field 45
	SubmessageFieldJsonArray string `wam:"submessage_field_json_array"` // field 46
	BodyUrlCountInt int64 `wam:"body_url_count_int"` // field 51
	BodyUrlUniqueCountInt int64 `wam:"body_url_unique_count_int"` // field 52
	CtaUrlUniqueCountInt int64 `wam:"cta_url_unique_count_int"` // field 53
	UrlUniqueCountInt int64 `wam:"url_unique_count_int"` // field 54
	IsCoex bool `wam:"is_coex"` // field 55
	IsThroughDecisionService bool `wam:"is_through_decision_service"` // field 56
	IasEntryPoint SIGNUPENTRYPOINT `wam:"ias_entry_point"` // field 57
	IasOptinDs string `wam:"ias_optin_ds"` // field 58
	IsIasSubscriber bool `wam:"is_ias_subscriber"` // field 59
	IsFromPill bool `wam:"is_from_pill"` // field 60
	PillEntryPoint PILLENTRYPOINT `wam:"pill_entry_point"` // field 61
}