const WamMessageReceive = 450 // channel: regular

type MessageReceiveEvent struct {
	MessageType MESSAGETYPE `wam:"message_type"` // field 1
	MessageMediaType MEDIATYPE `wam:"message_media_type"` // field 2
	NumOfWebUrlsInTextMessage int64 `wam:"num_of_web_urls_in_text_message"` // field 3
	MessageIsInternational bool `wam:"message_is_international"` // field 4
	MessageIsOffline bool `wam:"message_is_offline"` // field 5
	MessageReceiveT0 string `wam:"message_receive_t0"` // field 6
	MessageReceiveT1 string `wam:"message_receive_t1"` // field 7
	MutedGroupMessage bool `wam:"muted_group_message"` // field 8
	IsViewOnce bool `wam:"is_view_once"` // field 9
	DeviceSizeBucket SIZEBUCKET `wam:"device_size_bucket"` // field 10
	SenderDefaultDisappearingDuration int64 `wam:"sender_default_disappearing_duration"` // field 11
	ReceiverDefaultDisappearingDuration int64 `wam:"receiver_default_disappearing_duration"` // field 12
	EphemeralityDuration int64 `wam:"ephemerality_duration"` // field 13
	DisappearingChatInitiator DISAPPEARINGCHATINITIATORTYPE `wam:"disappearing_chat_initiator"` // field 14
	MessageQueueTime string `wam:"message_queue_time"` // field 15
	DeviceCount int64 `wam:"device_count"` // field 16
	ParticipantCount int64 `wam:"participant_count"` // field 17
	IsForwardedForward bool `wam:"is_forwarded_forward"` // field 18
	IsAReply bool `wam:"is_a_reply"` // field 19
	RevokeType REVOKETYPE `wam:"revoke_type"` // field 20
	TypeOfGroup TYPEOFGROUPENUM `wam:"type_of_group"` // field 21
	PaddingBytesSize int64 `wam:"padding_bytes_size"` // field 22
	MessageIsInvisible bool `wam:"message_is_invisible"` // field 23
	IsLid bool `wam:"is_lid"` // field 24
	EditType EDITTYPE `wam:"edit_type"` // field 25
	EphemeralityInitiator EPHEMERALITYINITIATORTYPE `wam:"ephemerality_initiator"` // field 26
	EphemeralityTriggerAction EPHEMERALITYTRIGGERACTIONTYPE `wam:"ephemerality_trigger_action"` // field 27
	AgentEngagementType AGENTENGAGEMENTENUMTYPE `wam:"agent_engagement_type"` // field 28
	StickerIsAi bool `wam:"sticker_is_ai"` // field 29
	OfflineCount int64 `wam:"offline_count"` // field 30
	StickerIsFromStickerMaker bool `wam:"sticker_is_from_sticker_maker"` // field 31
	StickerMakerSourceType STICKERMAKERSOURCETYPE `wam:"sticker_maker_source_type"` // field 32
	LocalAddressingMode ADDRESSINGMODE `wam:"local_addressing_mode"` // field 33
	MessageAddressingMode ADDRESSINGMODE `wam:"message_addressing_mode"` // field 34
	ServerAddressingMode ADDRESSINGMODE `wam:"server_addressing_mode"` // field 35
	IsAComment bool `wam:"is_a_comment"` // field 36
	BotType BOTTYPE `wam:"bot_type"` // field 37
	ChatOrigins CHATORIGINSTYPE `wam:"chat_origins"` // field 38
	HasUsername bool `wam:"has_username"` // field 39
	OppositeVisibleIdentification OPPOSITEVISIBLEIDENTIFICATIONTYPE `wam:"opposite_visible_identification"` // field 40
	InvisibleMessageCategory INVISIBLEMESSAGECATEGORYTYPE `wam:"invisible_message_category"` // field 41
	PairedMediaType PAIREDMEDIATYPE `wam:"paired_media_type"` // field 42
	AppContext string `wam:"app_context"` // field 43
	AppContextBitfield int64 `wam:"app_context_bitfield"` // field 44
	HasUsernamePin bool `wam:"has_username_pin"` // field 45
	ProcessingDeferred bool `wam:"processing_deferred"` // field 47
	StanzaProcessCount int64 `wam:"stanza_process_count"` // field 48
	MessageReceiveT2 string `wam:"message_receive_t2"` // field 49
	ReceivedPhoneNumberContactSize int64 `wam:"received_phone_number_contact_size"` // field 50
	ReceivedPhoneNumberWithUsernameContactSize int64 `wam:"received_phone_number_with_username_contact_size"` // field 51
	ReceivedUsernameContactSize int64 `wam:"received_username_contact_size"` // field 52
	PrivateAiFeatureName PRIVATEAIFEATURENAME `wam:"private_ai_feature_name"` // field 53
	EncryptionType ENCRYPTIONTYPECODE `wam:"encryption_type"` // field 54
	IsPq bool `wam:"is_pq"` // field 55
	TraceIdInt int64 `wam:"trace_id_int"` // field 56
	E2eSenderType E2EDEVICETYPE `wam:"e2e_sender_type"` // field 57
	ReceivedContactCardType string `wam:"received_contact_card_type"` // field 58
	ReceivedContactMetadataTypes string `wam:"received_contact_metadata_types"` // field 59
	StickerIsPremium bool `wam:"sticker_is_premium"` // field 60
	AfterReadDuration int64 `wam:"after_read_duration"` // field 61
	IsAfterRead bool `wam:"is_after_read"` // field 62
	SessionScope SESSIONSCOPETYPE `wam:"session_scope"` // field 63
	SenderPlatform PLATFORMTYPE `wam:"sender_platform"` // field 64
	OppositeHasUsername bool `wam:"opposite_has_username"` // field 65
	IsStickerAnnotation bool `wam:"is_sticker_annotation"` // field 66
}