const WamPtt = 458 // channel: regular

type PttEvent struct {
	PttResult PTTRESULTTYPE `wam:"ptt_result"` // field 1
	PttSource PTTSOURCETYPE `wam:"ptt_source"` // field 2
	PttSize string `wam:"ptt_size"` // field 3
	PttLock bool `wam:"ptt_lock"` // field 4
	PttDuration string `wam:"ptt_duration"` // field 5
	PttStop bool `wam:"ptt_stop"` // field 6
	PttDraftPlayCnt int64 `wam:"ptt_draft_play_cnt"` // field 7
	PttDraftSeekCnt int64 `wam:"ptt_draft_seek_cnt"` // field 8
	PttPauseCnt int64 `wam:"ptt_pause_cnt"` // field 9
	PttStopTapCnt int64 `wam:"ptt_stop_tap_cnt"` // field 10
	PttAvgNoiseLoudness string `wam:"ptt_avg_noise_loudness"` // field 11
	PttAvgNoiseLoudnessReduction string `wam:"ptt_avg_noise_loudness_reduction"` // field 12
	PttAvgSpeechLoudness string `wam:"ptt_avg_speech_loudness"` // field 13
	PttAvgSpeechLoudnessReduction string `wam:"ptt_avg_speech_loudness_reduction"` // field 14
	IsMetaAiThread bool `wam:"is_meta_ai_thread"` // field 15
	PttAudioEngine int64 `wam:"ptt_audio_engine"` // field 16
	PttAuddevRecorderAvgCbT string `wam:"ptt_auddev_recorder_avg_cb_t"` // field 17
	PttAuddevRecorderInitT string `wam:"ptt_auddev_recorder_init_t"` // field 18
	PttAuddevRecorderStartT string `wam:"ptt_auddev_recorder_start_t"` // field 19
	PttAuddevRecorderStopT string `wam:"ptt_auddev_recorder_stop_t"` // field 20
	PttRecorderCbBucketGte20msPct string `wam:"ptt_recorder_cb_bucket_gte20ms_pct"` // field 21
	PttRecorderCbBucketLt10msPct string `wam:"ptt_recorder_cb_bucket_lt10ms_pct"` // field 22
	PttRecorderCbBucketLt15msPct string `wam:"ptt_recorder_cb_bucket_lt15ms_pct"` // field 23
	PttRecorderCbBucketLt20msPct string `wam:"ptt_recorder_cb_bucket_lt20ms_pct"` // field 24
	PttRecorderCbBucketLt5msPct string `wam:"ptt_recorder_cb_bucket_lt5ms_pct"` // field 25
	PttRecorderNoiseDurationMs string `wam:"ptt_recorder_noise_duration_ms"` // field 26
	PttRecorderSpeechDurationMs string `wam:"ptt_recorder_speech_duration_ms"` // field 27
	PttOggPageWriteBucketGte10msPct string `wam:"ptt_ogg_page_write_bucket_gte10ms_pct"` // field 38
	PttOggPageWriteBucketLt10msPct string `wam:"ptt_ogg_page_write_bucket_lt10ms_pct"` // field 39
	PttOggPageWriteBucketLt2msPct string `wam:"ptt_ogg_page_write_bucket_lt2ms_pct"` // field 40
	PttOggPageWriteBucketLt4msPct string `wam:"ptt_ogg_page_write_bucket_lt4ms_pct"` // field 41
	PttOggPageWriteBucketLt6msPct string `wam:"ptt_ogg_page_write_bucket_lt6ms_pct"` // field 42
	PttOggPageWriteBucketLt8msPct string `wam:"ptt_ogg_page_write_bucket_lt8ms_pct"` // field 43
	PttOpusEncodeBucketGte10msPct string `wam:"ptt_opus_encode_bucket_gte10ms_pct"` // field 44
	PttOpusEncodeBucketLt10msPct string `wam:"ptt_opus_encode_bucket_lt10ms_pct"` // field 45
	PttOpusEncodeBucketLt2msPct string `wam:"ptt_opus_encode_bucket_lt2ms_pct"` // field 46
	PttOpusEncodeBucketLt4msPct string `wam:"ptt_opus_encode_bucket_lt4ms_pct"` // field 47
	PttOpusEncodeBucketLt6msPct string `wam:"ptt_opus_encode_bucket_lt6ms_pct"` // field 48
	PttOpusEncodeBucketLt8msPct string `wam:"ptt_opus_encode_bucket_lt8ms_pct"` // field 49
	PttIntensityAggregateValue string `wam:"ptt_intensity_aggregate_value"` // field 50
	PttWaveformResult PTTWAVEFORMRESULT `wam:"ptt_waveform_result"` // field 51
	AudioDriverRestartCount int64 `wam:"audio_driver_restart_count"` // field 52
	AudioDriverRestartReason int64 `wam:"audio_driver_restart_reason"` // field 53
	DeviceAgcState DEVICEAGCSTATETYPE `wam:"device_agc_state"` // field 54
	DeviceNsState DEVICENSSTATETYPE `wam:"device_ns_state"` // field 55
	PttCaptureSampleRateEffectiveHz int64 `wam:"ptt_capture_sample_rate_effective_hz"` // field 56
	PttCaptureSampleRateRequestedHz int64 `wam:"ptt_capture_sample_rate_requested_hz"` // field 57
}