const WamThreadInteractionDataBiz = 6464 // channel: regular

type ThreadInteractionDataBizEvent struct {
	AwayMsgsSent int64 `wam:"away_msgs_sent"` // field 1
	BizCatalogType BIZCATALOGTYPE `wam:"biz_catalog_type"` // field 2
	BizConversationDepth int64 `wam:"biz_conversation_depth"` // field 3
	CartViews int64 `wam:"cart_views"` // field 4
	ChatOrigins CHATORIGINSTYPE `wam:"chat_origins"` // field 5
	CollectionInquiriesSent int64 `wam:"collection_inquiries_sent"` // field 6
	CommerceMsgsReceived int64 `wam:"commerce_msgs_received"` // field 7
	CommerceMsgsSent int64 `wam:"commerce_msgs_sent"` // field 8
	EntryPointConversionApp string `wam:"entry_point_conversion_app"` // field 9
	EntryPointConversionSource string `wam:"entry_point_conversion_source"` // field 10
	FirstResponseTime int64 `wam:"first_response_time"` // field 11
	GroupContainsBiz bool `wam:"group_contains_biz"` // field 13
	IsCommerceViewed bool `wam:"is_commerce_viewed"` // field 14
	IsCtaOnPdpClicked bool `wam:"is_cta_on_pdp_clicked"` // field 15
	IsLabelled bool `wam:"is_labelled"` // field 16
	IsUser1pBizBotChat bool `wam:"is_user1p_biz_bot_chat"` // field 17
	IsUser3pBotChat bool `wam:"is_user3p_bot_chat"` // field 18
	IsUserAgent bool `wam:"is_user_agent"` // field 19
	IsUserCreatedAgent bool `wam:"is_user_created_agent"` // field 20
	LabelledMsgs int64 `wam:"labelled_msgs"` // field 21
	OppositePartyHasBusinessIntent bool `wam:"opposite_party_has_business_intent"` // field 22
	OrdersSent int64 `wam:"orders_sent"` // field 23
	PdpInquiriesSent int64 `wam:"pdp_inquiries_sent"` // field 24
	PdpViews int64 `wam:"pdp_views"` // field 25
	QuickRepliesSent int64 `wam:"quick_replies_sent"` // field 26
	SmbMarketingMessagesReactionsSent int64 `wam:"smb_marketing_messages_reactions_sent"` // field 27
	SmbMarketingMessagesRepliesSent int64 `wam:"smb_marketing_messages_replies_sent"` // field 28
	SmbMarketingMessagesSpamReports int64 `wam:"smb_marketing_messages_spam_reports"` // field 29
	SmbMarketingMsgsReceived int64 `wam:"smb_marketing_msgs_received"` // field 30
	SmbMarketingMsgsSent int64 `wam:"smb_marketing_msgs_sent"` // field 31
	ThreadDs string `wam:"thread_ds"` // field 32
	ThreadId string `wam:"thread_id"` // field 33
	UserHasBusinessIntent bool `wam:"user_has_business_intent"` // field 35
	IsOppositePartyInitiated bool `wam:"is_opposite_party_initiated"` // field 36
	LocationsSent int64 `wam:"locations_sent"` // field 37
	ThreadIdByLid string `wam:"thread_id_by_lid"` // field 38
	ThreadCreationDate string `wam:"thread_creation_date"` // field 39
	OppositePartyHasBadge bool `wam:"opposite_party_has_badge"` // field 40
	FmxNotMvBottomSheetDismissedCount int64 `wam:"fmx_not_mv_bottom_sheet_dismissed_count"` // field 41
	FmxNotMvBottomSheetGetMvButtonClicks int64 `wam:"fmx_not_mv_bottom_sheet_get_mv_button_clicks"` // field 42
	FmxNotMvBottomSheetGetMvButtonImpressions int64 `wam:"fmx_not_mv_bottom_sheet_get_mv_button_impressions"` // field 43
	FmxNotMvBottomSheetImpressions int64 `wam:"fmx_not_mv_bottom_sheet_impressions"` // field 44
	FmxNotMvBottomSheetLearnMoreButtonClicks int64 `wam:"fmx_not_mv_bottom_sheet_learn_more_button_clicks"` // field 45
	FmxNotMvClicks int64 `wam:"fmx_not_mv_clicks"` // field 46
	IsBizMvFrictionEligible bool `wam:"is_biz_mv_friction_eligible"` // field 47
	NotMvImpressions int64 `wam:"not_mv_impressions"` // field 48
	MatchedMessagesMarkedAsReadWithDeltaTime string `wam:"matched_messages_marked_as_read_with_delta_time"` // field 49
	MatchedMessagesReadWithDeltaTime string `wam:"matched_messages_read_with_delta_time"` // field 50
	AutoReplyFromIcebreakerSent int64 `wam:"auto_reply_from_icebreaker_sent"` // field 51
	BizAiSuggestedRepliesSeen int64 `wam:"biz_ai_suggested_replies_seen"` // field 52
	BizAiSuggestedRepliesSentWithEdits int64 `wam:"biz_ai_suggested_replies_sent_with_edits"` // field 53
	BizAiSuggestedRepliesSentWithoutEdits int64 `wam:"biz_ai_suggested_replies_sent_without_edits"` // field 54
}