type ACTIVETIMEAFTERPAIRING int

const (
	ACTIVETIMEAFTERPAIRINGMINS10 ACTIVETIMEAFTERPAIRING = 1
	ACTIVETIMEAFTERPAIRINGMINS20 ACTIVETIMEAFTERPAIRING = 2
	ACTIVETIMEAFTERPAIRINGMINS40 ACTIVETIMEAFTERPAIRING = 3
	ACTIVETIMEAFTERPAIRINGMINS60 ACTIVETIMEAFTERPAIRING = 4
	ACTIVETIMEAFTERPAIRINGMINS5 ACTIVETIMEAFTERPAIRING = 5
)