type ACTIONCODE int

const (
	ACTIONCODEOPENMEDIAHUB ACTIONCODE = 1
	ACTIONCODESEARCH ACTIONCODE = 2
	ACTIONCODELIST ACTIONCODE = 3
	ACTIONCODEICON ACTIONCODE = 4
	ACTIONCODESCROLL ACTIONCODE = 5
	ACTIONCODECLICK ACTIONCODE = 6
	ACTIONCODECLOSEMEDIAHUB ACTIONCODE = 7
	ACTIONCODEREPLY ACTIONCODE = 8
	ACTIONCODEFORWARD ACTIONCODE = 9
	ACTIONCODEDOWNLOAD ACTIONCODE = 10
	ACTIONCODESTAR ACTIONCODE = 11
	ACTIONCODEDELETE ACTIONCODE = 12
	ACTIONCODEOPEN ACTIONCODE = 13
	ACTIONCODEGOTOMESSAGE ACTIONCODE = 14
	ACTIONCODEMULTISELECT ACTIONCODE = 15
	ACTIONCODESORT ACTIONCODE = 16
	ACTIONCODEOPENMENU ACTIONCODE = 17
	ACTIONCODEFILTER ACTIONCODE = 18
)