type ACTIONENTRYPOINT int

const (
	ACTIONENTRYPOINTCHATINFO ACTIONENTRYPOINT = 0
	ACTIONENTRYPOINTCHATCONTEXTMENU ACTIONENTRYPOINT = 1
	ACTIONENTRYPOINTNOTIFICATIONS ACTIONENTRYPOINT = 2
	ACTIONENTRYPOINTCONTACTS ACTIONENTRYPOINT = 3
	ACTIONENTRYPOINTCHATLIST ACTIONENTRYPOINT = 4
	ACTIONENTRYPOINTUNKNOWN ACTIONENTRYPOINT = 5
	ACTIONENTRYPOINTPRIVATEREPLY ACTIONENTRYPOINT = 6
	ACTIONENTRYPOINTSTATUSREPLY ACTIONENTRYPOINT = 7
	ACTIONENTRYPOINTSEARCH ACTIONENTRYPOINT = 8
	ACTIONENTRYPOINTDIRECTMESSAGE ACTIONENTRYPOINT = 9
	ACTIONENTRYPOINTPRIVACYSETTINGS ACTIONENTRYPOINT = 10
	ACTIONENTRYPOINTCHATLONGPRESSOPTIONS ACTIONENTRYPOINT = 11
	ACTIONENTRYPOINTCHATMOREOPTIONS ACTIONENTRYPOINT = 12
	ACTIONENTRYPOINTSIDEBAR ACTIONENTRYPOINT = 13
)