type ACTIONTHREADTYPETYPE int

const (
	ACTIONTHREADTYPETYPEGROUPCHAT ACTIONTHREADTYPETYPE = 1
	ACTIONTHREADTYPETYPEP2PTHREAD ACTIONTHREADTYPETYPE = 2
	ACTIONTHREADTYPETYPEMESSAGEYOURSELF ACTIONTHREADTYPETYPE = 3
	ACTIONTHREADTYPETYPEMETAAI ACTIONTHREADTYPETYPE = 4
	ACTIONTHREADTYPETYPETOCHARACTER ACTIONTHREADTYPETYPE = 5
	ACTIONTHREADTYPETYPETOUGC ACTIONTHREADTYPETYPE = 6
	ACTIONTHREADTYPETYPEARSURFACE ACTIONTHREADTYPETYPE = 7
)