type ADDCONTACTACTIONTYPE int

const (
	ADDCONTACTACTIONTYPEOPEN ADDCONTACTACTIONTYPE = 0
	ADDCONTACTACTIONTYPESAVE ADDCONTACTACTIONTYPE = 1
	ADDCONTACTACTIONTYPECANCEL ADDCONTACTACTIONTYPE = 2
	ADDCONTACTACTIONTYPEDELETE ADDCONTACTACTIONTYPE = 3
	ADDCONTACTACTIONTYPECREATEDUPLICATE ADDCONTACTACTIONTYPE = 4
	ADDCONTACTACTIONTYPEPINSUBMIT ADDCONTACTACTIONTYPE = 5
)