type AGENTENGAGEMENTENUMTYPE int

const (
	AGENTENGAGEMENTENUMTYPEDIRECTCHAT AGENTENGAGEMENTENUMTYPE = 0
	AGENTENGAGEMENTENUMTYPEINVOKED AGENTENGAGEMENTENUMTYPE = 1
	AGENTENGAGEMENTENUMTYPEMEMBER AGENTENGAGEMENTENUMTYPE = 2
)