type APPEXITREASON int

const (
	APPEXITREASONUNKNOWN APPEXITREASON = 0
	APPEXITREASONEXITSELF APPEXITREASON = 1
	APPEXITREASONSIGNALED APPEXITREASON = 2
	APPEXITREASONLOWMEMORY APPEXITREASON = 3
	APPEXITREASONCRASH APPEXITREASON = 4
	APPEXITREASONCRASHNATIVE APPEXITREASON = 5
	APPEXITREASONANR APPEXITREASON = 6
	APPEXITREASONINITIALIZATIONFAILURE APPEXITREASON = 7
	APPEXITREASONPERMISSIONCHANGE APPEXITREASON = 8
	APPEXITREASONEXCESSIVERESOURCEUSAGE APPEXITREASON = 9
	APPEXITREASONUSERREQUESTED APPEXITREASON = 10
	APPEXITREASONUSERSTOPPED APPEXITREASON = 11
	APPEXITREASONDEPENDENCYDIED APPEXITREASON = 12
	APPEXITREASONOTHER APPEXITREASON = 13
	APPEXITREASONFREEZER APPEXITREASON = 14
	APPEXITREASONPACKAGESTATECHANGE APPEXITREASON = 15
	APPEXITREASONPACKAGEUPDATED APPEXITREASON = 16
	APPEXITREASONANDROIDNEWVALUES APPEXITREASON = 200
)