type APPLAUNCHDESTINATIONTYPE int

const (
	APPLAUNCHDESTINATIONTYPECHATLIST APPLAUNCHDESTINATIONTYPE = 1
	APPLAUNCHDESTINATIONTYPECHAT APPLAUNCHDESTINATIONTYPE = 2
	APPLAUNCHDESTINATIONTYPESHARE APPLAUNCHDESTINATIONTYPE = 3
	APPLAUNCHDESTINATIONTYPECALL APPLAUNCHDESTINATIONTYPE = 4
	APPLAUNCHDESTINATIONTYPECHANNEL APPLAUNCHDESTINATIONTYPE = 5
)