type ATTACHMENTTRAYACTIONTYPE int

const (
	ATTACHMENTTRAYACTIONTYPECLICK ATTACHMENTTRAYACTIONTYPE = 1
	ATTACHMENTTRAYACTIONTYPESEND ATTACHMENTTRAYACTIONTYPE = 2
	ATTACHMENTTRAYACTIONTYPECANCEL ATTACHMENTTRAYACTIONTYPE = 3
)