type AUDIOENGINETYPE int

const (
	AUDIOENGINETYPEJNI AUDIOENGINETYPE = 1
	AUDIOENGINETYPEOPENSLES AUDIOENGINETYPE = 2
	AUDIOENGINETYPEOBOEOPENSL AUDIOENGINETYPE = 3
	AUDIOENGINETYPEOBOEUNSPECIFIED AUDIOENGINETYPE = 4
	AUDIOENGINETYPEJNIINOBOEOPENSLOUT AUDIOENGINETYPE = 5
	AUDIOENGINETYPEJNIINOBOEUNSPECIFIEDOUT AUDIOENGINETYPE = 6
)