type AUDIENCETYPES string

const (
	AUDIENCETYPESCUSTOM AUDIENCETYPES = "CUSTOM"
	AUDIENCETYPESFRIENDS AUDIENCETYPES = "FRIENDS"
	AUDIENCETYPESPUBLIC AUDIENCETYPES = "PUBLIC"
	AUDIENCETYPESUNSET AUDIENCETYPES = "UNSET"
)