type BANNEROPERATIONS int

const (
	BANNEROPERATIONSSHOWN BANNEROPERATIONS = 1
	BANNEROPERATIONSCLICK BANNEROPERATIONS = 2
	BANNEROPERATIONSDISMISS BANNEROPERATIONS = 3
	BANNEROPERATIONSELIGIBLE BANNEROPERATIONS = 4
	BANNEROPERATIONSREVOKED BANNEROPERATIONS = 5
	BANNEROPERATIONSRENDERED BANNEROPERATIONS = 6
)