type BLOCKREASON int

const (
	BLOCKREASONOTHER BLOCKREASON = 0
	BLOCKREASONNOLONGERNEEDED BLOCKREASON = 1
	BLOCKREASONNOSIGNUP BLOCKREASON = 2
	BLOCKREASONSPAM BLOCKREASON = 3
	BLOCKREASONOFFENSIVEMESSAGES BLOCKREASON = 4
	BLOCKREASONOTPDIDNOTREQUEST BLOCKREASON = 5
	BLOCKREASONSCAMORFRAUD BLOCKREASON = 6
	BLOCKREASONDONTRECOGNIZE BLOCKREASON = 7
)