type BOTDISCOVERYPATHTYPE int

const (
	BOTDISCOVERYPATHTYPECURATEDDISPLAY BOTDISCOVERYPATHTYPE = 1
	BOTDISCOVERYPATHTYPESEARCH BOTDISCOVERYPATHTYPE = 2
	BOTDISCOVERYPATHTYPEVIEWALL BOTDISCOVERYPATHTYPE = 3
	BOTDISCOVERYPATHTYPEDEEPLINKUSERSHARED BOTDISCOVERYPATHTYPE = 4
	BOTDISCOVERYPATHTYPEINFINITESCROLL BOTDISCOVERYPATHTYPE = 5
)