type BUSINESSTOOLSITEMTYPE int

const (
	BUSINESSTOOLSITEMTYPEOVERFLOW BUSINESSTOOLSITEMTYPE = 0
	BUSINESSTOOLSITEMTYPEPROFILE BUSINESSTOOLSITEMTYPE = 1
	BUSINESSTOOLSITEMTYPECATALOG BUSINESSTOOLSITEMTYPE = 2
	BUSINESSTOOLSITEMTYPEAWAYMESSAGE BUSINESSTOOLSITEMTYPE = 3
	BUSINESSTOOLSITEMTYPEGREETINGMESSAGE BUSINESSTOOLSITEMTYPE = 4
	BUSINESSTOOLSITEMTYPEQUICKREPLIES BUSINESSTOOLSITEMTYPE = 5
	BUSINESSTOOLSITEMTYPELABELS BUSINESSTOOLSITEMTYPE = 6
	BUSINESSTOOLSITEMTYPELINKEDACCOUNTS BUSINESSTOOLSITEMTYPE = 7
	BUSINESSTOOLSITEMTYPESHORTLINK BUSINESSTOOLSITEMTYPE = 8
	BUSINESSTOOLSITEMTYPESTATISTICS BUSINESSTOOLSITEMTYPE = 9
	BUSINESSTOOLSITEMTYPECREATEACCOUNTLINK BUSINESSTOOLSITEMTYPE = 10
	BUSINESSTOOLSITEMTYPEMANAGECTA BUSINESSTOOLSITEMTYPE = 11
	BUSINESSTOOLSITEMTYPECREATEAD BUSINESSTOOLSITEMTYPE = 12
	BUSINESSTOOLSITEMTYPECONTINUEPROMPT BUSINESSTOOLSITEMTYPE = 13
	BUSINESSTOOLSITEMTYPEADVERTISELISTITEM BUSINESSTOOLSITEMTYPE = 14
	BUSINESSTOOLSITEMTYPESHOPS BUSINESSTOOLSITEMTYPE = 15
	BUSINESSTOOLSITEMTYPEDISABLEDCATALOG BUSINESSTOOLSITEMTYPE = 16
	BUSINESSTOOLSITEMTYPEBANNEDSHOP BUSINESSTOOLSITEMTYPE = 17
	BUSINESSTOOLSITEMTYPEPREMIUMTOOLS BUSINESSTOOLSITEMTYPE = 18
	BUSINESSTOOLSITEMTYPEBUSINESSDIRECTORY BUSINESSTOOLSITEMTYPE = 19
	BUSINESSTOOLSITEMTYPEMANAGEADS BUSINESSTOOLSITEMTYPE = 20
	BUSINESSTOOLSITEMTYPEMETAVERIFIED BUSINESSTOOLSITEMTYPE = 21
	BUSINESSTOOLSITEMTYPEAIFROMMETA BUSINESSTOOLSITEMTYPE = 22
	BUSINESSTOOLSITEMTYPEORDERS BUSINESSTOOLSITEMTYPE = 23
	BUSINESSTOOLSITEMTYPEMARKETINGMESSAGES BUSINESSTOOLSITEMTYPE = 24
	BUSINESSTOOLSITEMTYPEBUSINESSBROADCAST BUSINESSTOOLSITEMTYPE = 25
	BUSINESSTOOLSITEMTYPEPAYMENTSHOME BUSINESSTOOLSITEMTYPE = 26
	BUSINESSTOOLSITEMTYPEMISSEDCALLFOLLOWUP BUSINESSTOOLSITEMTYPE = 27
)