type CALLTERMREASON int

const (
	CALLTERMREASONENDEDBYUSER CALLTERMREASON = 1
	CALLTERMREASONTIMEOUT CALLTERMREASON = 2
	CALLTERMREASONRECONNECTING CALLTERMREASON = 3
	CALLTERMREASONENDEDBYSELF CALLTERMREASON = 4
	CALLTERMREASONENDEDBYPEER CALLTERMREASON = 5
	CALLTERMREASONVIDEOENCODERFATALERROR CALLTERMREASON = 6
	CALLTERMREASONVIDEODECODERFATALERROR CALLTERMREASON = 7
	CALLTERMREASONAUDIORECORDFATALERROR CALLTERMREASON = 8
	CALLTERMREASONCRASH CALLTERMREASON = 9
	CALLTERMREASONDETECTIDENTITYCHANGE CALLTERMREASON = 10
	CALLTERMREASONUSERINVISIBLE CALLTERMREASON = 11
	CALLTERMREASONRELAYBINDFAILED CALLTERMREASON = 12
	CALLTERMREASONSETUPFAILED CALLTERMREASON = 13
	CALLTERMREASONACCEPTEDELSEWHERE CALLTERMREASON = 14
	CALLTERMREASONREJECTEDELSEWHERE CALLTERMREASON = 15
	CALLTERMREASONGROUPCALLENDED CALLTERMREASON = 16
	CALLTERMREASONCALLISFULL CALLTERMREASON = 17
	CALLTERMREASONPHONEPERMISSIONDENIED CALLTERMREASON = 18
	CALLTERMREASONUSERREMOVED CALLTERMREASON = 19
	CALLTERMREASONHEARTBEATTERMINATE CALLTERMREASON = 20
	CALLTERMREASONREMOTEDISCONNECT CALLTERMREASON = 21
	CALLTERMREASONCALLERBLOCKED CALLTERMREASON = 22
	CALLTERMREASONDNDMODE CALLTERMREASON = 23
	CALLTERMREASONMICROPHONEPERMISSIONDENIED CALLTERMREASON = 24
	CALLTERMREASONCAMERAPERMISSIONDENIED CALLTERMREASON = 25
	CALLTERMREASONMEDIATXRXTIMEOUT CALLTERMREASON = 26
	CALLTERMREASONRINGINGTIMEOUT CALLTERMREASON = 27
	CALLTERMREASONCALLISPROTECTED CALLTERMREASON = 28
	CALLTERMREASONMEDIARXTIMEOUT CALLTERMREASON = 29
	CALLTERMREASONMEDIATXTIMEOUT CALLTERMREASON = 30
	CALLTERMREASONVCLONELYSTATETIMEOUT CALLTERMREASON = 31
	CALLTERMREASONWAITINGROOMDENIED CALLTERMREASON = 32
	CALLTERMREASONWAITINGROOMTIMEOUT CALLTERMREASON = 33
	CALLTERMREASONDEVICESWITCH CALLTERMREASON = 34
	CALLTERMREASONVIDEOPREVIEWERROR CALLTERMREASON = 35
	CALLTERMREASONVIDEOSTREAMCREATEERROR CALLTERMREASON = 36
	CALLTERMREASONVIDEOPORTCREATEERROR CALLTERMREASON = 37
	CALLTERMREASONFAILEDTOSETVIDEODISPLAYSURFACE CALLTERMREASON = 38
	CALLTERMREASONFATALNACK CALLTERMREASON = 39
)