type CALLTRANSPORTTYPE int

const (
	CALLTRANSPORTTYPEUNKNOWN CALLTRANSPORTTYPE = 0
	CALLTRANSPORTTYPEP2P CALLTRANSPORTTYPE = 1
	CALLTRANSPORTTYPEUDPRELAY CALLTRANSPORTTYPE = 2
	CALLTRANSPORTTYPETCPRELAY CALLTRANSPORTTYPE = 3
	CALLTRANSPORTTYPEMIXED CALLTRANSPORTTYPE = 4
)