type CALLSTABSOURCE int

const (
	CALLSTABSOURCENOTIFICATION CALLSTABSOURCE = 1
	CALLSTABSOURCESWITCH CALLSTABSOURCE = 2
	CALLSTABSOURCELAUNCH CALLSTABSOURCE = 3
	CALLSTABSOURCENONE CALLSTABSOURCE = 4
	CALLSTABSOURCEOSCALLLOG CALLSTABSOURCE = 5
)