type CAMERASTARTMODEPARAMS int

const (
	CAMERASTARTMODEPARAMSDEFAULT CAMERASTARTMODEPARAMS = 0
	CAMERASTARTMODEPARAMSCONSERVATIVE CAMERASTARTMODEPARAMS = 1
	CAMERASTARTMODEPARAMSSTRICT CAMERASTARTMODEPARAMS = 2
	CAMERASTARTMODEPARAMSERROR CAMERASTARTMODEPARAMS = 11
)