type CHANNELLINKSHARESCREEN int

const (
	CHANNELLINKSHARESCREENCONTEXTCARD CHANNELLINKSHARESCREEN = 1
	CHANNELLINKSHARESCREENCHANNELINFO CHANNELLINKSHARESCREEN = 2
	CHANNELLINKSHARESCREENCHANNELTHREAD CHANNELLINKSHARESCREEN = 3
	CHANNELLINKSHARESCREENSHARELINKSCREEN CHANNELLINKSHARESCREEN = 4
	CHANNELLINKSHARESCREENUPDATESTAB CHANNELLINKSHARESCREEN = 5
	CHANNELLINKSHARESCREENQRCODESCREEN CHANNELLINKSHARESCREEN = 6
)