type CHANNELUSERTYPE int

const (
	CHANNELUSERTYPEOWNER CHANNELUSERTYPE = 1
	CHANNELUSERTYPEADMIN CHANNELUSERTYPE = 2
	CHANNELUSERTYPEFOLLOWER CHANNELUSERTYPE = 3
	CHANNELUSERTYPEGUEST CHANNELUSERTYPE = 4
)