type CHATACTIONTYPE int

const (
	CHATACTIONTYPEMUTE CHATACTIONTYPE = 1
	CHATACTIONTYPEUNMUTE CHATACTIONTYPE = 2
	CHATACTIONTYPEARCHIVE CHATACTIONTYPE = 3
	CHATACTIONTYPECLEAR CHATACTIONTYPE = 4
	CHATACTIONTYPEEXITGROUP CHATACTIONTYPE = 5
	CHATACTIONTYPEDELETE CHATACTIONTYPE = 6
	CHATACTIONTYPEPIN CHATACTIONTYPE = 7
	CHATACTIONTYPEUNREAD CHATACTIONTYPE = 8
	CHATACTIONTYPEREAD CHATACTIONTYPE = 9
	CHATACTIONTYPESUSPENDCHATDELETE CHATACTIONTYPE = 10
)