type CHATASSIGNMENTACTIONTYPE int

const (
	CHATASSIGNMENTACTIONTYPEACTIONASSIGNED CHATASSIGNMENTACTIONTYPE = 0
	CHATASSIGNMENTACTIONTYPEACTIONUNASSIGNED CHATASSIGNMENTACTIONTYPE = 1
	CHATASSIGNMENTACTIONTYPEACTIONREASSIGNED CHATASSIGNMENTACTIONTYPE = 2
)