type CHATASSIGNMENTCHATTYPE int

const (
	CHATASSIGNMENTCHATTYPEINDIVIDUAL CHATASSIGNMENTCHATTYPE = 0
	CHATASSIGNMENTCHATTYPEGROUP CHATASSIGNMENTCHATTYPE = 1
	CHATASSIGNMENTCHATTYPECOMMUNITY CHATASSIGNMENTCHATTYPE = 2
	CHATASSIGNMENTCHATTYPECHANNEL CHATASSIGNMENTCHATTYPE = 3
)