type CHATWALLPAPERENTRYTYPE int

const (
	CHATWALLPAPERENTRYTYPEONETOONE CHATWALLPAPERENTRYTYPE = 1
	CHATWALLPAPERENTRYTYPEGROUP CHATWALLPAPERENTRYTYPE = 2
	CHATWALLPAPERENTRYTYPEAPPWIDE CHATWALLPAPERENTRYTYPE = 3
	CHATWALLPAPERENTRYTYPEAPPTHEME CHATWALLPAPERENTRYTYPE = 4
	CHATWALLPAPERENTRYTYPELISTTHEME CHATWALLPAPERENTRYTYPE = 5
)