type CHATACTIONCHATTYPE int

const (
	CHATACTIONCHATTYPEINDIVIDUAL CHATACTIONCHATTYPE = 1
	CHATACTIONCHATTYPEGROUP CHATACTIONCHATTYPE = 2
	CHATACTIONCHATTYPEBUSINESS CHATACTIONCHATTYPE = 3
	CHATACTIONCHATTYPEBROADCASTLIST CHATACTIONCHATTYPE = 4
	CHATACTIONCHATTYPECHANNEL CHATACTIONCHATTYPE = 5
)