type CHATLOCKACTIONTYPE int

const (
	CHATLOCKACTIONTYPECHATINFOIMPRESSION CHATLOCKACTIONTYPE = 0
	CHATLOCKACTIONTYPELOCKCHATSCREENIMPRESSION CHATLOCKACTIONTYPE = 1
	CHATLOCKACTIONTYPEAUTHINITIATED CHATLOCKACTIONTYPE = 2
	CHATLOCKACTIONTYPEAUTHSUCCEEDED CHATLOCKACTIONTYPE = 3
	CHATLOCKACTIONTYPESETUPAUTHIMPRESSION CHATLOCKACTIONTYPE = 4
	CHATLOCKACTIONTYPEADDCHATLOCK CHATLOCKACTIONTYPE = 5
	CHATLOCKACTIONTYPEREMOVECHATLOCK CHATLOCKACTIONTYPE = 6
	CHATLOCKACTIONTYPECLEARANDUNLOCKIMPRESSION CHATLOCKACTIONTYPE = 7
	CHATLOCKACTIONTYPECLEARANDUNLOCKSUCCESS CHATLOCKACTIONTYPE = 8
	CHATLOCKACTIONTYPECLEARANDUNLOCKFAILURE CHATLOCKACTIONTYPE = 9
	CHATLOCKACTIONTYPEAUTHFAILURE CHATLOCKACTIONTYPE = 10
	CHATLOCKACTIONTYPEBOTTOMSHEETIMPRESSION CHATLOCKACTIONTYPE = 11
	CHATLOCKACTIONTYPEBOTTOMSHEETCONTINUECLICK CHATLOCKACTIONTYPE = 12
	CHATLOCKACTIONTYPEBOTTOMSHEETLEARNMORECLICK CHATLOCKACTIONTYPE = 13
	CHATLOCKACTIONTYPEFOLDEROPEN CHATLOCKACTIONTYPE = 14
	CHATLOCKACTIONTYPEFORGOTSECRETCODE CHATLOCKACTIONTYPE = 15
	CHATLOCKACTIONTYPEUNLOCKANDCLEARWARNING CHATLOCKACTIONTYPE = 16
	CHATLOCKACTIONTYPEUSESECRETCODEAUTH CHATLOCKACTIONTYPE = 17
)