type COLLECTION int

const (
	COLLECTIONREGULAR COLLECTION = 1
	COLLECTIONREGULARLOW COLLECTION = 2
	COLLECTIONREGULARHIGH COLLECTION = 3
	COLLECTIONCRITICALBLOCK COLLECTION = 4
	COLLECTIONCRITICALUNBLOCKLOW COLLECTION = 5
)