type CONNECTIONORIGINTYPE int

const (
	CONNECTIONORIGINTYPEPERSON CONNECTIONORIGINTYPE = 1
	CONNECTIONORIGINTYPEPUSH CONNECTIONORIGINTYPE = 2
	CONNECTIONORIGINTYPEOTHER CONNECTIONORIGINTYPE = 3
	CONNECTIONORIGINTYPEBACKOFF CONNECTIONORIGINTYPE = 4
)