type CONSUMERBIZACTIONTYPEENUM int

const (
	CONSUMERBIZACTIONTYPEENUMIMPRESSION CONSUMERBIZACTIONTYPEENUM = 0
	CONSUMERBIZACTIONTYPEENUMTAP CONSUMERBIZACTIONTYPEENUM = 1
	CONSUMERBIZACTIONTYPEENUMSCROLL CONSUMERBIZACTIONTYPEENUM = 2
	CONSUMERBIZACTIONTYPEENUMLONGPRESS CONSUMERBIZACTIONTYPEENUM = 3
	CONSUMERBIZACTIONTYPEENUMSWIPE CONSUMERBIZACTIONTYPEENUM = 4
	CONSUMERBIZACTIONTYPEENUMCLICK CONSUMERBIZACTIONTYPEENUM = 5
	CONSUMERBIZACTIONTYPEENUMVIEW CONSUMERBIZACTIONTYPEENUM = 6
	CONSUMERBIZACTIONTYPEENUMOPENCHAT CONSUMERBIZACTIONTYPEENUM = 7
)