type CONTACTSEARCHENTRYPOINT int

const (
	CONTACTSEARCHENTRYPOINTNEWCHAT CONTACTSEARCHENTRYPOINT = 1
	CONTACTSEARCHENTRYPOINTNEWGROUP CONTACTSEARCHENTRYPOINT = 2
	CONTACTSEARCHENTRYPOINTNEWCALL CONTACTSEARCHENTRYPOINT = 3
	CONTACTSEARCHENTRYPOINTADDTOGROUP CONTACTSEARCHENTRYPOINT = 4
	CONTACTSEARCHENTRYPOINTCHATSLISTGLOBALSEARCH CONTACTSEARCHENTRYPOINT = 5
	CONTACTSEARCHENTRYPOINTCALLSTABGLOBALSEARCH CONTACTSEARCHENTRYPOINT = 6
	CONTACTSEARCHENTRYPOINTEVENTINVITE CONTACTSEARCHENTRYPOINT = 7
)