type CONTACTSYNCSOURCE int

const (
	CONTACTSYNCSOURCECONTACTFORM CONTACTSYNCSOURCE = 1
	CONTACTSYNCSOURCECTWAOPENDEEPLINK CONTACTSYNCSOURCE = 2
	CONTACTSYNCSOURCECTWAPOSTDEEPLINK CONTACTSYNCSOURCE = 3
)