type CRASHTYPE int

const (
	CRASHTYPECRASH CRASHTYPE = 0
	CRASHTYPEOOM CRASHTYPE = 1
	CRASHTYPEMAINTHREADSTALL3SECONDS CRASHTYPE = 15
	CRASHTYPEMAINTHREADSTALL5SECONDS CRASHTYPE = 21
	CRASHTYPEMAINTHREADSTALL30SECONDS CRASHTYPE = 2
	CRASHTYPEMAINTHREADSTALL60SECONDS CRASHTYPE = 16
	CRASHTYPEMAINTHREADSTALLPOKED CRASHTYPE = 17
	CRASHTYPEMAINTHREADSTALLDEBUG CRASHTYPE = 3
	CRASHTYPEAUDIOTRANSCODINGERROR CRASHTYPE = 4
	CRASHTYPEVIDEOTRANSCODINGERROR CRASHTYPE = 5
	CRASHTYPEANR CRASHTYPE = 6
	CRASHTYPECRITICALEVENT CRASHTYPE = 7
	CRASHTYPEUNHANDLEDEXCEPTION CRASHTYPE = 8
	CRASHTYPEAPPCRASH CRASHTYPE = 9
	CRASHTYPENATIVECRASH CRASHTYPE = 10
	CRASHTYPEUFAD CRASHTYPE = 11
	CRASHTYPEUXBREAKINGEXCEPTION CRASHTYPE = 13
	CRASHTYPEUXGRACEFULRECOVERYEXCEPTION CRASHTYPE = 14
	CRASHTYPEWEBUICOMPONENTFAILURE CRASHTYPE = 18
	CRASHTYPEWEBBROKENUSEREXPERIENCE CRASHTYPE = 19
	CRASHTYPEWEBFORCEDLOGOUT CRASHTYPE = 20
	CRASHTYPETHREADPOOLNOTRESPONDING CRASHTYPE = 22
	CRASHTYPEDISPATCHERNOTRESPONDING CRASHTYPE = 23
	CRASHTYPEMSCRASH CRASHTYPE = 24
	CRASHTYPEMAINTHREADSTALL CRASHTYPE = 25
)