type CRASHAPPLICATIONSTATE int

const (
	CRASHAPPLICATIONSTATEFOREGROUND CRASHAPPLICATIONSTATE = 1
	CRASHAPPLICATIONSTATEBACKGROUND CRASHAPPLICATIONSTATE = 2
	CRASHAPPLICATIONSTATEAPPINIT CRASHAPPLICATIONSTATE = 3
	CRASHAPPLICATIONSTATEVISIBLE CRASHAPPLICATIONSTATE = 4
)