type CTAFALLBACKREASON int

const (
	CTAFALLBACKREASONNOOTPREQUESTRECEIVED CTAFALLBACKREASON = 0
	CTAFALLBACKREASONOTPREQUESTEXPIRED CTAFALLBACKREASON = 1
	CTAFALLBACKREASONHASHMISMATCH CTAFALLBACKREASON = 2
	CTAFALLBACKREASONNOACTIVITYLISTENINGONTHIRDPARTYAPP CTAFALLBACKREASON = 3
	CTAFALLBACKREASONOTHER CTAFALLBACKREASON = 4
	CTAFALLBACKREASONNOPACKAGENAMEONMESSAGE CTAFALLBACKREASON = 5
	CTAFALLBACKREASONNOCTADISPLAYNAME CTAFALLBACKREASON = 6
	CTAFALLBACKREASONINCOMPATIBLEOSVERSION CTAFALLBACKREASON = 7
	CTAFALLBACKREASONNORETRIEVERBUTTON CTAFALLBACKREASON = 8
	CTAFALLBACKREASONFEATUREDISABLED CTAFALLBACKREASON = 9
	CTAFALLBACKREASONAMBIGUOUSDELIVERYDESTINATION CTAFALLBACKREASON = 10
)