type CTWAADACCOUNTTYPE int

const (
	CTWAADACCOUNTTYPECTWAFBPAGELINKEDACCOUNT CTWAADACCOUNTTYPE = 0
	CTWAADACCOUNTTYPECTWAFBPAGELESSACCOUNT CTWAADACCOUNTTYPE = 1
	CTWAADACCOUNTTYPECTWAWAADACCOUNT CTWAADACCOUNTTYPE = 2
)