type DEFAULTPROTOCOLTARGETTYPE int

const (
	DEFAULTPROTOCOLTARGETTYPELID DEFAULTPROTOCOLTARGETTYPE = 0
	DEFAULTPROTOCOLTARGETTYPEPHONE DEFAULTPROTOCOLTARGETTYPE = 1
	DEFAULTPROTOCOLTARGETTYPENONE DEFAULTPROTOCOLTARGETTYPE = 2
)