type DISCLOSUREEVENTTYPE int

const (
	DISCLOSUREEVENTTYPECTAURLCLICK DISCLOSUREEVENTTYPE = 0
	DISCLOSUREEVENTTYPEBODYURLCLICK DISCLOSUREEVENTTYPE = 1
	DISCLOSUREEVENTTYPEBODYURLLONGPRESS DISCLOSUREEVENTTYPE = 2
	DISCLOSUREEVENTTYPEDISCLOSUREINFOCLICK DISCLOSUREEVENTTYPE = 3
	DISCLOSUREEVENTTYPEOPENCHATWITHUNREADMM DISCLOSUREEVENTTYPE = 4
	DISCLOSUREEVENTTYPECTAAPPCLICK DISCLOSUREEVENTTYPE = 5
)