type DISCLOSURETYPE int

const (
	DISCLOSURETYPENONBLOCKING DISCLOSURETYPE = 0
	DISCLOSURETYPEBLOCKING DISCLOSURETYPE = 1
	DISCLOSURETYPEINFO DISCLOSURETYPE = 2
	DISCLOSURETYPEINTHREADBLOCKING DISCLOSURETYPE = 3
	DISCLOSURETYPEINTHREADBLOCKINGWITHBACK DISCLOSURETYPE = 4
)