type DISCLOSURECONTEXTTYPE int

const (
	DISCLOSURECONTEXTTYPEPREFILLTEXT DISCLOSURECONTEXTTYPE = 0
	DISCLOSURECONTEXTTYPEEMPTYPREFILLTEXT DISCLOSURECONTEXTTYPE = 1
	DISCLOSURECONTEXTTYPEICEBREAKERS DISCLOSURECONTEXTTYPE = 2
	DISCLOSURECONTEXTTYPENOTAPPLICABLE DISCLOSURECONTEXTTYPE = 3
)