type DNSRESOLUTIONMETHODTYPE int

const (
	DNSRESOLUTIONMETHODTYPESYSTEM DNSRESOLUTIONMETHODTYPE = 1
	DNSRESOLUTIONMETHODTYPEGOOGLE DNSRESOLUTIONMETHODTYPE = 2
	DNSRESOLUTIONMETHODTYPEHARDCODED DNSRESOLUTIONMETHODTYPE = 3
	DNSRESOLUTIONMETHODTYPENODNS DNSRESOLUTIONMETHODTYPE = 4
	DNSRESOLUTIONMETHODTYPEMNS DNSRESOLUTIONMETHODTYPE = 5
	DNSRESOLUTIONMETHODTYPESOCKSPROXY DNSRESOLUTIONMETHODTYPE = 6
	DNSRESOLUTIONMETHODTYPEMNSSECONDARY DNSRESOLUTIONMETHODTYPE = 7
)