type DOWNLOADORIGINTYPE int

const (
	DOWNLOADORIGINTYPECHATPERSONAL DOWNLOADORIGINTYPE = 1
	DOWNLOADORIGINTYPECHATGROUP DOWNLOADORIGINTYPE = 2
	DOWNLOADORIGINTYPESTATUSUSER DOWNLOADORIGINTYPE = 3
	DOWNLOADORIGINTYPESTATUSADS DOWNLOADORIGINTYPE = 4
	DOWNLOADORIGINTYPEPRODUCTCATALOG DOWNLOADORIGINTYPE = 5
	DOWNLOADORIGINTYPEGDPR DOWNLOADORIGINTYPE = 6
	DOWNLOADORIGINTYPESTICKERPICKER DOWNLOADORIGINTYPE = 7
	DOWNLOADORIGINTYPEPROFILEPICTURE DOWNLOADORIGINTYPE = 8
	DOWNLOADORIGINTYPEBLOKS DOWNLOADORIGINTYPE = 9
	DOWNLOADORIGINTYPEP2B DOWNLOADORIGINTYPE = 10
	DOWNLOADORIGINTYPEMESSAGEHISTORYSYNC DOWNLOADORIGINTYPE = 11
	DOWNLOADORIGINTYPECOMMUNITY DOWNLOADORIGINTYPE = 12
	DOWNLOADORIGINTYPECHANNEL DOWNLOADORIGINTYPE = 13
	DOWNLOADORIGINTYPEBROADCAST DOWNLOADORIGINTYPE = 14
	DOWNLOADORIGINTYPEINTEROP DOWNLOADORIGINTYPE = 15
	DOWNLOADORIGINTYPEWAMOSTATUS DOWNLOADORIGINTYPE = 16
	DOWNLOADORIGINTYPEWAMOBIZPROFILE DOWNLOADORIGINTYPE = 17
	DOWNLOADORIGINTYPEWAMOPREFERENCES DOWNLOADORIGINTYPE = 18
	DOWNLOADORIGINTYPERICHORDERSTATUS DOWNLOADORIGINTYPE = 19
	DOWNLOADORIGINTYPEWABACKUP DOWNLOADORIGINTYPE = 20
)