type E2ECIPHERTEXTTYPE int

const (
	E2ECIPHERTEXTTYPEMESSAGE E2ECIPHERTEXTTYPE = 0
	E2ECIPHERTEXTTYPEPREKEYMESSAGE E2ECIPHERTEXTTYPE = 1
	E2ECIPHERTEXTTYPESENDERKEYMESSAGE E2ECIPHERTEXTTYPE = 2
	E2ECIPHERTEXTTYPEMESSAGESECRETMESSAGE E2ECIPHERTEXTTYPE = 3
)