type E2EDEVICETYPE int

const (
	E2EDEVICETYPEMYPRIMARY E2EDEVICETYPE = 1
	E2EDEVICETYPEOTHERPRIMARY E2EDEVICETYPE = 2
	E2EDEVICETYPEMYCOMPANION E2EDEVICETYPE = 3
	E2EDEVICETYPEOTHERCOMPANION E2EDEVICETYPE = 4
	E2EDEVICETYPEMYHOSTEDCOMPANION E2EDEVICETYPE = 5
	E2EDEVICETYPEOTHERHOSTEDCOMPANION E2EDEVICETYPE = 6
	E2EDEVICETYPEMYCOEXV2 E2EDEVICETYPE = 7
	E2EDEVICETYPEOTHERCOEXV2 E2EDEVICETYPE = 8
)