type E2EDESTINATION int

const (
	E2EDESTINATIONINDIVIDUAL E2EDESTINATION = 0
	E2EDESTINATIONGROUP E2EDESTINATION = 1
	E2EDESTINATIONLIST E2EDESTINATION = 2
	E2EDESTINATIONSTATUS E2EDESTINATION = 3
	E2EDESTINATIONCHANNEL E2EDESTINATION = 4
	E2EDESTINATIONINTEROP E2EDESTINATION = 5
)