type EDITTYPE int

const (
	EDITTYPENOTEDITED EDITTYPE = 0
	EDITTYPEEDITED EDITTYPE = 1
	EDITTYPESENDERREVOKE EDITTYPE = 2
	EDITTYPEADMINREVOKE EDITTYPE = 3
	EDITTYPEADMINEDIT EDITTYPE = 4
	EDITTYPEPIN EDITTYPE = 5
)