type EDITPROFILEACTION int

const (
	EDITPROFILEACTIONACTIONOPEN EDITPROFILEACTION = 1
	EDITPROFILEACTIONACTIONSAVE EDITPROFILEACTION = 2
	EDITPROFILEACTIONACTIONDISCARD EDITPROFILEACTION = 3
	EDITPROFILEACTIONACTIONPROFILEFIELDOPEN EDITPROFILEACTION = 4
	EDITPROFILEACTIONACTIONPROFILEFIELDSAVE EDITPROFILEACTION = 5
	EDITPROFILEACTIONACTIONPROFILEFIELDDISCARD EDITPROFILEACTION = 6
	EDITPROFILEACTIONACTIONFACEBOOKENABLED EDITPROFILEACTION = 7
	EDITPROFILEACTIONACTIONFACEBOOKDISABLED EDITPROFILEACTION = 8
	EDITPROFILEACTIONACTIONINSTAGRAMENABLED EDITPROFILEACTION = 9
	EDITPROFILEACTIONACTIONINSTAGRAMDISABLED EDITPROFILEACTION = 10
	EDITPROFILEACTIONACTIONFBIGPOPSHOWN EDITPROFILEACTION = 11
	EDITPROFILEACTIONACTIONEDITCOVERPHOTOCLICK EDITPROFILEACTION = 12
	EDITPROFILEACTIONACTIONREMOVECOVERPHOTO EDITPROFILEACTION = 13
	EDITPROFILEACTIONUPGRADETOCUSTOMLINKCLICK EDITPROFILEACTION = 14
	EDITPROFILEACTIONDIALOGBOXGEOCODEIMPRESSION EDITPROFILEACTION = 15
	EDITPROFILEACTIONDIALOGBOXGEOCODEACCEPT EDITPROFILEACTION = 16
	EDITPROFILEACTIONDIALOGBOXGEOCODEREVOKE EDITPROFILEACTION = 17
)