type ENCRYPTIONTYPECODE int

const (
	ENCRYPTIONTYPECODEE2EE ENCRYPTIONTYPECODE = 1
	ENCRYPTIONTYPECODECOEX ENCRYPTIONTYPECODE = 2
	ENCRYPTIONTYPECODESELFCOEX ENCRYPTIONTYPECODE = 3
	ENCRYPTIONTYPECODECAPI ENCRYPTIONTYPECODE = 4
	ENCRYPTIONTYPECODEBSP ENCRYPTIONTYPECODE = 5
	ENCRYPTIONTYPECODEGUEST ENCRYPTIONTYPECODE = 6
	ENCRYPTIONTYPECODETEE ENCRYPTIONTYPECODE = 7
	ENCRYPTIONTYPECODEBOT ENCRYPTIONTYPECODE = 8
	ENCRYPTIONTYPECODEBOTGROUP ENCRYPTIONTYPECODE = 9
	ENCRYPTIONTYPECODECOEXV2 ENCRYPTIONTYPECODE = 10
	ENCRYPTIONTYPECODESELFCOEXV2 ENCRYPTIONTYPECODE = 11
)