type ENFORCEMENTTYPE int

const (
	ENFORCEMENTTYPECHS ENFORCEMENTTYPE = 0
	ENFORCEMENTTYPECHSI ENFORCEMENTTYPE = 1
	ENFORCEMENTTYPECHGS ENFORCEMENTTYPE = 2
	ENFORCEMENTTYPECHGSI ENFORCEMENTTYPE = 3
	ENFORCEMENTTYPECHHCH ENFORCEMENTTYPE = 4
	ENFORCEMENTTYPECHPPD ENFORCEMENTTYPE = 5
	ENFORCEMENTTYPECHHAP ENFORCEMENTTYPE = 6
)