type ENUMDELIVERYNOOPTIMIZATION string

const (
	ENUMDELIVERYNOOPTIMIZATIONDelivery ENUMDELIVERYNOOPTIMIZATION = "delivery"
	ENUMDELIVERYNOOPTIMIZATIONNoOptimization ENUMDELIVERYNOOPTIMIZATION = "no_optimization"
)