type ENUMFAILUREINITSUCCESS string

const (
	ENUMFAILUREINITSUCCESSFAILURE ENUMFAILUREINITSUCCESS = "FAILURE"
	ENUMFAILUREINITSUCCESSINIT ENUMFAILUREINITSUCCESS = "INIT"
	ENUMFAILUREINITSUCCESSSUCCESS ENUMFAILUREINITSUCCESS = "SUCCESS"
)