type ENUMALLOWBYPASSDENYERROR string

const (
	ENUMALLOWBYPASSDENYERRORAllow ENUMALLOWBYPASSDENYERROR = "allow"
	ENUMALLOWBYPASSDENYERRORBypass ENUMALLOWBYPASSDENYERROR = "bypass"
	ENUMALLOWBYPASSDENYERRORDeny ENUMALLOWBYPASSDENYERROR = "deny"
	ENUMALLOWBYPASSDENYERRORError ENUMALLOWBYPASSDENYERROR = "error"
)