type ENUMMOBILENUMBERNUMERICID string

const (
	ENUMMOBILENUMBERNUMERICIDMobileNumber ENUMMOBILENUMBERNUMERICID = "mobile_number"
	ENUMMOBILENUMBERNUMERICIDNumericId ENUMMOBILENUMBERNUMERICID = "numeric_id"
)