type ENUMHIGHLOWUNKNOWN string

const (
	ENUMHIGHLOWUNKNOWNHigh ENUMHIGHLOWUNKNOWN = "high"
	ENUMHIGHLOWUNKNOWNLow ENUMHIGHLOWUNKNOWN = "low"
	ENUMHIGHLOWUNKNOWNUnknown ENUMHIGHLOWUNKNOWN = "unknown"
)