type ENUMACTIVEELIGIBLEINELIGIBLE string

const (
	ENUMACTIVEELIGIBLEINELIGIBLEActive ENUMACTIVEELIGIBLEINELIGIBLE = "active"
	ENUMACTIVEELIGIBLEINELIGIBLEEligible ENUMACTIVEELIGIBLEINELIGIBLE = "eligible"
	ENUMACTIVEELIGIBLEINELIGIBLEIneligible ENUMACTIVEELIGIBLEINELIGIBLE = "ineligible"
)