type ENUMINTEGRITYNOTCLEAREDOK string

const (
	ENUMINTEGRITYNOTCLEAREDOKINTEGRITYNOTCLEARED ENUMINTEGRITYNOTCLEAREDOK = "INTEGRITY_NOT_CLEARED"
	ENUMINTEGRITYNOTCLEAREDOKOK ENUMINTEGRITYNOTCLEAREDOK = "OK"
)