type ENUMHIGHHIGHFORCELOW string

const (
	ENUMHIGHHIGHFORCELOWHigh ENUMHIGHHIGHFORCELOW = "high"
	ENUMHIGHHIGHFORCELOWHighForce ENUMHIGHHIGHFORCELOW = "high_force"
	ENUMHIGHHIGHFORCELOWLow ENUMHIGHHIGHFORCELOW = "low"
)