type ENUME2EEMIGRATIONREGULARRTC string

const (
	ENUME2EEMIGRATIONREGULARRTCE2eeMigration ENUME2EEMIGRATIONREGULARRTC = "e2ee_migration"
	ENUME2EEMIGRATIONREGULARRTCRegular ENUME2EEMIGRATIONREGULARRTC = "regular"
	ENUME2EEMIGRATIONREGULARRTCRtc ENUME2EEMIGRATIONREGULARRTC = "rtc"
)