type ENUMDELIVERYINACTIVEPLAYEDREAD string

const (
	ENUMDELIVERYINACTIVEPLAYEDREADDelivery ENUMDELIVERYINACTIVEPLAYEDREAD = "delivery"
	ENUMDELIVERYINACTIVEPLAYEDREADInactive ENUMDELIVERYINACTIVEPLAYEDREAD = "inactive"
	ENUMDELIVERYINACTIVEPLAYEDREADPlayed ENUMDELIVERYINACTIVEPLAYEDREAD = "played"
	ENUMDELIVERYINACTIVEPLAYEDREADRead ENUMDELIVERYINACTIVEPLAYEDREAD = "read"
)