type ENUMBASICNONEWITHCHATSTATE string

const (
	ENUMBASICNONEWITHCHATSTATEBasic ENUMBASICNONEWITHCHATSTATE = "basic"
	ENUMBASICNONEWITHCHATSTATENone ENUMBASICNONEWITHCHATSTATE = "none"
	ENUMBASICNONEWITHCHATSTATEWithChatState ENUMBASICNONEWITHCHATSTATE = "with_chat_state"
)