type ENUMFIRSTFULLINNERLAST string

const (
	ENUMFIRSTFULLINNERLASTFirst ENUMFIRSTFULLINNERLAST = "first"
	ENUMFIRSTFULLINNERLASTFull ENUMFIRSTFULLINNERLAST = "full"
	ENUMFIRSTFULLINNERLASTInner ENUMFIRSTFULLINNERLAST = "inner"
	ENUMFIRSTFULLINNERLASTLast ENUMFIRSTFULLINNERLAST = "last"
)