type ENUMALLCONTACTSKNOWN string

const (
	ENUMALLCONTACTSKNOWNAll ENUMALLCONTACTSKNOWN = "all"
	ENUMALLCONTACTSKNOWNContacts ENUMALLCONTACTSKNOWN = "contacts"
	ENUMALLCONTACTSKNOWNKnown ENUMALLCONTACTSKNOWN = "known"
)