type ENUMDOCUMENTIMAGEMIXEDVIDEO string

const (
	ENUMDOCUMENTIMAGEMIXEDVIDEODocument ENUMDOCUMENTIMAGEMIXEDVIDEO = "document"
	ENUMDOCUMENTIMAGEMIXEDVIDEOImage ENUMDOCUMENTIMAGEMIXEDVIDEO = "image"
	ENUMDOCUMENTIMAGEMIXEDVIDEOMixed ENUMDOCUMENTIMAGEMIXEDVIDEO = "mixed"
	ENUMDOCUMENTIMAGEMIXEDVIDEOVideo ENUMDOCUMENTIMAGEMIXEDVIDEO = "video"
)