type ENUMELIGIBLELOCKEDTRUE string

const (
	ENUMELIGIBLELOCKEDTRUEEligible ENUMELIGIBLELOCKEDTRUE = "eligible"
	ENUMELIGIBLELOCKEDTRUELocked ENUMELIGIBLELOCKEDTRUE = "locked"
	ENUMELIGIBLELOCKEDTRUETrue ENUMELIGIBLELOCKEDTRUE = "true"
)