type ENUMALLCATEGORYFEATURED string

const (
	ENUMALLCATEGORYFEATUREDAll ENUMALLCATEGORYFEATURED = "all"
	ENUMALLCATEGORYFEATUREDCategory ENUMALLCATEGORYFEATURED = "category"
	ENUMALLCATEGORYFEATUREDFeatured ENUMALLCATEGORYFEATURED = "featured"
)