type ENUMPASSPENDINGTIMELOCK string

const (
	ENUMPASSPENDINGTIMELOCKPass ENUMPASSPENDINGTIMELOCK = "pass"
	ENUMPASSPENDINGTIMELOCKPending ENUMPASSPENDINGTIMELOCK = "pending"
	ENUMPASSPENDINGTIMELOCKTimelock ENUMPASSPENDINGTIMELOCK = "timelock"
)