type ENUMAUDIOGIFIMAGEVIDEO string

const (
	ENUMAUDIOGIFIMAGEVIDEOAudio ENUMAUDIOGIFIMAGEVIDEO = "audio"
	ENUMAUDIOGIFIMAGEVIDEOGif ENUMAUDIOGIFIMAGEVIDEO = "gif"
	ENUMAUDIOGIFIMAGEVIDEOImage ENUMAUDIOGIFIMAGEVIDEO = "image"
	ENUMAUDIOGIFIMAGEVIDEOVideo ENUMAUDIOGIFIMAGEVIDEO = "video"
)