type ENUMFAILEDPENDINGVERIFIED string

const (
	ENUMFAILEDPENDINGVERIFIEDFAILED ENUMFAILEDPENDINGVERIFIED = "FAILED"
	ENUMFAILEDPENDINGVERIFIEDPENDING ENUMFAILEDPENDINGVERIFIED = "PENDING"
	ENUMFAILEDPENDINGVERIFIEDVERIFIED ENUMFAILEDPENDINGVERIFIED = "VERIFIED"
)