type ENUMCREATIONEDITRESPONSE string

const (
	ENUMCREATIONEDITRESPONSECreation ENUMCREATIONEDITRESPONSE = "creation"
	ENUMCREATIONEDITRESPONSEEdit ENUMCREATIONEDITRESPONSE = "edit"
	ENUMCREATIONEDITRESPONSEResponse ENUMCREATIONEDITRESPONSE = "response"
)