type ENUMDISCOVERABLEHIDDENUNDEFINED string

const (
	ENUMDISCOVERABLEHIDDENUNDEFINEDDISCOVERABLE ENUMDISCOVERABLEHIDDENUNDEFINED = "DISCOVERABLE"
	ENUMDISCOVERABLEHIDDENUNDEFINEDHIDDEN ENUMDISCOVERABLEHIDDENUNDEFINED = "HIDDEN"
	ENUMDISCOVERABLEHIDDENUNDEFINEDUNDEFINED ENUMDISCOVERABLEHIDDENUNDEFINED = "UNDEFINED"
)