type ENUMFALSENOTSETTRUE string

const (
	ENUMFALSENOTSETTRUEFalse ENUMFALSENOTSETTRUE = "false"
	ENUMFALSENOTSETTRUENotset ENUMFALSENOTSETTRUE = "notset"
	ENUMFALSENOTSETTRUETrue ENUMFALSENOTSETTRUE = "true"
)