type ENUM1PPARTIAL3PFULLUNKNOWN string

const (
	ENUM1PPARTIAL3PFULLUNKNOWN1pPartial ENUM1PPARTIAL3PFULLUNKNOWN = "1p_partial"
	ENUM1PPARTIAL3PFULLUNKNOWN3pFull ENUM1PPARTIAL3PFULLUNKNOWN = "3p_full"
	ENUM1PPARTIAL3PFULLUNKNOWNUnknown ENUM1PPARTIAL3PFULLUNKNOWN = "unknown"
)