type EXPIRYREASON int

const (
	EXPIRYREASONUSERLEAVE EXPIRYREASON = 1
	EXPIRYREASONDEVICEUNPAIR EXPIRYREASON = 2
	EXPIRYREASONIDENTITYCHANGE EXPIRYREASON = 3
	EXPIRYREASONAUDIENCECHANGE EXPIRYREASON = 4
	EXPIRYREASONPERIODICROTATION EXPIRYREASON = 5
	EXPIRYREASONKEYCORRUPTION EXPIRYREASON = 6
	EXPIRYREASONPEERCOMPANIONUNPAIR EXPIRYREASON = 7
	EXPIRYREASONOTHERDEVICEUNPAIR EXPIRYREASON = 8
)