type FORWARDORIGIN int

const (
	FORWARDORIGINUNKNOWN FORWARDORIGIN = 1
	FORWARDORIGINCHAT FORWARDORIGIN = 2
	FORWARDORIGINSTATUS FORWARDORIGIN = 3
	FORWARDORIGINCHANNELS FORWARDORIGIN = 4
	FORWARDORIGINMETAAI FORWARDORIGIN = 5
)