type GALLERYPERMISSIONSTATE int

const (
	GALLERYPERMISSIONSTATEFULL GALLERYPERMISSIONSTATE = 1
	GALLERYPERMISSIONSTATEPARTIAL GALLERYPERMISSIONSTATE = 2
	GALLERYPERMISSIONSTATENONE GALLERYPERMISSIONSTATE = 3
)