type GCINITIATIONTYPE int

const (
	GCINITIATIONTYPEONEONONETOGCUPGRADE GCINITIATIONTYPE = 0
	GCINITIATIONTYPEADHOC GCINITIATIONTYPE = 1
	GCINITIATIONTYPELINKED GCINITIATIONTYPE = 2
	GCINITIATIONTYPECALLLINK GCINITIATIONTYPE = 3
	GCINITIATIONTYPEVOICECHAT GCINITIATIONTYPE = 4
)