type GCREKEYMASTERERROR int

const (
	GCREKEYMASTERERRORNONE GCREKEYMASTERERROR = 0
	GCREKEYMASTERERRORFAILEDTOGENERATENEWE2EEKEYS GCREKEYMASTERERROR = 1
	GCREKEYMASTERERRORFAILEDTOUPDATEPARTICIPANTKEYS GCREKEYMASTERERROR = 2
)