type GENAIEXITPOINT int

const (
	GENAIEXITPOINTCANCELFULLSHEET GENAIEXITPOINT = 1
	GENAIEXITPOINTCANCELHALFSHEET GENAIEXITPOINT = 2
	GENAIEXITPOINTDISMISSFULLSHEET GENAIEXITPOINT = 3
	GENAIEXITPOINTDISMISSHALFSHEET GENAIEXITPOINT = 4
	GENAIEXITPOINTINACTIVITYFULLSHEET GENAIEXITPOINT = 5
	GENAIEXITPOINTINACTIVITYHALFSHEET GENAIEXITPOINT = 6
	GENAIEXITPOINTKEYBOARDFULLSHEET GENAIEXITPOINT = 7
	GENAIEXITPOINTKEYBOARDHALFSHEET GENAIEXITPOINT = 8
	GENAIEXITPOINTCAMERAFULLSHEET GENAIEXITPOINT = 9
	GENAIEXITPOINTCAMERAHALFSHEET GENAIEXITPOINT = 10
	GENAIEXITPOINTBACKGROUNDEDFULLSHEET GENAIEXITPOINT = 11
	GENAIEXITPOINTBACKGROUNDEDHALFSHEET GENAIEXITPOINT = 12
	GENAIEXITPOINTHALFSHEETDIRECTTOSETTING GENAIEXITPOINT = 13
	GENAIEXITPOINTFULLSHEETDIRECTTOSETTING GENAIEXITPOINT = 14
	GENAIEXITPOINTEXITMMSURFACE GENAIEXITPOINT = 15
	GENAIEXITPOINTCOMPOSERTRANSITION GENAIEXITPOINT = 16
)