type GROUPTYPECLIENT int

const (
	GROUPTYPECLIENTREGULARGROUP GROUPTYPECLIENT = 1
	GROUPTYPECLIENTSUBGROUP GROUPTYPECLIENT = 2
	GROUPTYPECLIENTDEFAULTSUBGROUP GROUPTYPECLIENT = 3
	GROUPTYPECLIENTPARENTGROUP GROUPTYPECLIENT = 4
)