type GROUPSTATUSSIZEBUCKET int

const (
	GROUPSTATUSSIZEBUCKETEMPTYGROUP GROUPSTATUSSIZEBUCKET = 1
	GROUPSTATUSSIZEBUCKETXSMALL GROUPSTATUSSIZEBUCKET = 2
	GROUPSTATUSSIZEBUCKETSMALL GROUPSTATUSSIZEBUCKET = 3
	GROUPSTATUSSIZEBUCKETMEDIUM GROUPSTATUSSIZEBUCKET = 4
	GROUPSTATUSSIZEBUCKETLARGE GROUPSTATUSSIZEBUCKET = 5
)