type HATCHACTIONTYPE int

const (
	HATCHACTIONTYPEREQUESTWELCOMEMSGSENT HATCHACTIONTYPE = 1
	HATCHACTIONTYPETAPUNLINKBUTTON HATCHACTIONTYPE = 2
	HATCHACTIONTYPEUNLINKSUCCESS HATCHACTIONTYPE = 3
	HATCHACTIONTYPEWAREADWRITEACCESSIMPRESSION HATCHACTIONTYPE = 4
	HATCHACTIONTYPETAPWAREADWRITEACCESS HATCHACTIONTYPE = 5
	HATCHACTIONTYPEWAREADWRITEACCESSLINKSUCCESS HATCHACTIONTYPE = 6
	HATCHACTIONTYPEHITLBOTTOMSHEETIMPRESSION HATCHACTIONTYPE = 7
	HATCHACTIONTYPEHITLDETAILIMPRESSION HATCHACTIONTYPE = 8
	HATCHACTIONTYPEHITLALLOWONCETAP HATCHACTIONTYPE = 9
	HATCHACTIONTYPEHITLALWAYSALLOWTAP HATCHACTIONTYPE = 10
	HATCHACTIONTYPEHITLDENYTAP HATCHACTIONTYPE = 11
)