type HIGHLIGHTGROUPTYPE int

const (
	HIGHLIGHTGROUPTYPEUNKNOWN HIGHLIGHTGROUPTYPE = 0
	HIGHLIGHTGROUPTYPESINGLE HIGHLIGHTGROUPTYPE = 1
	HIGHLIGHTGROUPTYPECREATOR HIGHLIGHTGROUPTYPE = 2
	HIGHLIGHTGROUPTYPEADMIN HIGHLIGHTGROUPTYPE = 3
	HIGHLIGHTGROUPTYPESAVEDCONTACTS HIGHLIGHTGROUPTYPE = 4
	HIGHLIGHTGROUPTYPEPARTICIPANTS HIGHLIGHTGROUPTYPE = 5
	HIGHLIGHTGROUPTYPEMORE HIGHLIGHTGROUPTYPE = 6
)