type IMAGINEACTIONTHREADTYPE int

const (
	IMAGINEACTIONTHREADTYPEGROUPCHAT IMAGINEACTIONTHREADTYPE = 1
	IMAGINEACTIONTHREADTYPEP2PTHREAD IMAGINEACTIONTHREADTYPE = 2
	IMAGINEACTIONTHREADTYPEMESSAGEYOURSELF IMAGINEACTIONTHREADTYPE = 3
	IMAGINEACTIONTHREADTYPEMETAAI IMAGINEACTIONTHREADTYPE = 4
	IMAGINEACTIONTHREADTYPETOCHARACTER IMAGINEACTIONTHREADTYPE = 5
	IMAGINEACTIONTHREADTYPETOUGC IMAGINEACTIONTHREADTYPE = 6
	IMAGINEACTIONTHREADTYPESTATUS IMAGINEACTIONTHREADTYPE = 7
	IMAGINEACTIONTHREADTYPEARSURFACE IMAGINEACTIONTHREADTYPE = 8
)