type INITBWESOURCE int

const (
	INITBWESOURCEDEFAULT INITBWESOURCE = 0
	INITBWESOURCEPROBINGROTTTORELAY INITBWESOURCE = 1
	INITBWESOURCEPROBINGE2EPEERRX INITBWESOURCE = 2
	INITBWESOURCEPROBINGE2ERX INITBWESOURCE = 3
	INITBWESOURCEHISRECENTPEERRX INITBWESOURCE = 4
	INITBWESOURCEHISRECENTRX INITBWESOURCE = 5
	INITBWESOURCEHISRECENTPROBINGROTTTORELAY INITBWESOURCE = 6
	INITBWESOURCEHISRECENTPROBINGE2EPEERRX INITBWESOURCE = 7
	INITBWESOURCEHISRECENTPROBINGE2ERX INITBWESOURCE = 8
	INITBWESOURCEONESIDEINITIALBANDWIDTHESTIMATION INITBWESOURCE = 9
)