type JIDDOMAINTYPE int

const (
	JIDDOMAINTYPESWHATSAPPNET JIDDOMAINTYPE = 0
	JIDDOMAINTYPECUS JIDDOMAINTYPE = 1
	JIDDOMAINTYPELID JIDDOMAINTYPE = 2
	JIDDOMAINTYPEMSGR JIDDOMAINTYPE = 3
	JIDDOMAINTYPEINTEROP JIDDOMAINTYPE = 4
	JIDDOMAINTYPEINTEROPMSGR JIDDOMAINTYPE = 5
	JIDDOMAINTYPEGUS JIDDOMAINTYPE = 6
	JIDDOMAINTYPEBOT JIDDOMAINTYPE = 7
	JIDDOMAINTYPEBROADCAST JIDDOMAINTYPE = 8
	JIDDOMAINTYPENEWSLETTER JIDDOMAINTYPE = 9
	JIDDOMAINTYPECALL JIDDOMAINTYPE = 10
	JIDDOMAINTYPEHPHONE JIDDOMAINTYPE = 11
	JIDDOMAINTYPENONEUS JIDDOMAINTYPE = 12
	JIDDOMAINTYPEERRORUS JIDDOMAINTYPE = 13
	JIDDOMAINTYPENONE JIDDOMAINTYPE = 14
)