type KICNUXACTIONNAMETYPE int

const (
	KICNUXACTIONNAMETYPEFIRSTDMNUXIMPRESSION KICNUXACTIONNAMETYPE = 1
	KICNUXACTIONNAMETYPEKICNUXIMPRESSION KICNUXACTIONNAMETYPE = 2
	KICNUXACTIONNAMETYPEKICNUXLEARNMORETAP KICNUXACTIONNAMETYPE = 3
	KICNUXACTIONNAMETYPEKICSYSTEMMESSAGEGENERATE KICNUXACTIONNAMETYPE = 4
)