type KICERRORCODETYPE int

const (
	KICERRORCODETYPENONE KICERRORCODETYPE = 1
	KICERRORCODETYPEMESSAGEMISSING KICERRORCODETYPE = 2
	KICERRORCODETYPEMESSAGEREVOKED KICERRORCODETYPE = 3
	KICERRORCODETYPESENDERUNKEPT KICERRORCODETYPE = 4
	KICERRORCODETYPEOLDERREQUEST KICERRORCODETYPE = 5
	KICERRORCODETYPEORPHANEXPIRED KICERRORCODETYPE = 6
	KICERRORCODETYPETIEBREAKIGNORED KICERRORCODETYPE = 7
	KICERRORCODETYPEMESSAGEEXPIRED KICERRORCODETYPE = 8
	KICERRORCODETYPENOPERMISSIONTOEDIT KICERRORCODETYPE = 9
	KICERRORCODETYPEMESSAGEFROMEXMEMBER KICERRORCODETYPE = 10
	KICERRORCODETYPEOFFLINE KICERRORCODETYPE = 11
	KICERRORCODETYPESENDERDISABLED KICERRORCODETYPE = 12
	KICERRORCODETYPEKEPTBEYONDEXPIRY KICERRORCODETYPE = 13
	KICERRORCODETYPENOTPARTOFTHEGROUP KICERRORCODETYPE = 14
	KICERRORCODETYPECONTACTBLOCKED KICERRORCODETYPE = 15
	KICERRORCODETYPEUNKNOWN KICERRORCODETYPE = 999
)