type KICENTRYPOINTTYPE int

const (
	KICENTRYPOINTTYPECHATINFO KICENTRYPOINTTYPE = 1
	KICENTRYPOINTTYPESEARCH KICENTRYPOINTTYPE = 2
	KICENTRYPOINTTYPECHAT KICENTRYPOINTTYPE = 3
	KICENTRYPOINTTYPEMEDIA KICENTRYPOINTTYPE = 4
	KICENTRYPOINTTYPEDOCS KICENTRYPOINTTYPE = 5
	KICENTRYPOINTTYPELINKS KICENTRYPOINTTYPE = 6
	KICENTRYPOINTTYPEPHOTOS KICENTRYPOINTTYPE = 7
	KICENTRYPOINTTYPEVIDEOS KICENTRYPOINTTYPE = 8
	KICENTRYPOINTTYPESTICKERS KICENTRYPOINTTYPE = 9
	KICENTRYPOINTTYPEALLMEDIA KICENTRYPOINTTYPE = 10
)