type LABELSYNCDIRECTIONTYPE int

const (
	LABELSYNCDIRECTIONTYPESENDER LABELSYNCDIRECTIONTYPE = 1
	LABELSYNCDIRECTIONTYPERECEIVER LABELSYNCDIRECTIONTYPE = 2
	LABELSYNCDIRECTIONTYPERETRY LABELSYNCDIRECTIONTYPE = 3
	LABELSYNCDIRECTIONTYPEBOOTSTRAPSENDER LABELSYNCDIRECTIONTYPE = 4
)