type LABELOPERATIONS int

const (
	LABELOPERATIONSADD LABELOPERATIONS = 1
	LABELOPERATIONSEDIT LABELOPERATIONS = 2
	LABELOPERATIONSDELETE LABELOPERATIONS = 3
	LABELOPERATIONSVIEW LABELOPERATIONS = 4
	LABELOPERATIONSCLICKPOSITIVE LABELOPERATIONS = 5
	LABELOPERATIONSCLICKNEGATIVE LABELOPERATIONS = 6
	LABELOPERATIONSUPDATELABELCOUNT LABELOPERATIONS = 7
	LABELOPERATIONSAUTOADDED LABELOPERATIONS = 8
	LABELOPERATIONSREORDER LABELOPERATIONS = 9
	LABELOPERATIONSRENAME LABELOPERATIONS = 10
	LABELOPERATIONSUPDATEMEMBERS LABELOPERATIONS = 11
	LABELOPERATIONSMUTE LABELOPERATIONS = 12
	LABELOPERATIONSUNMUTE LABELOPERATIONS = 13
	LABELOPERATIONSSUGGESTIONCLICKED LABELOPERATIONS = 14
	LABELOPERATIONSUPDATEDCOLOR LABELOPERATIONS = 15
	LABELOPERATIONSSWIPE LABELOPERATIONS = 16
)