type LIDMIGRATIONSTAGEENUM int

const (
	LIDMIGRATIONSTAGEENUMNOTMIGRATED LIDMIGRATIONSTAGEENUM = 1
	LIDMIGRATIONSTAGEENUMPEERMIGRATED LIDMIGRATIONSTAGEENUM = 2
	LIDMIGRATIONSTAGEENUMHISTORYMIGRATED LIDMIGRATIONSTAGEENUM = 3
)