type LIGHTWEIGHTREACTIONUNICODES string

const (
	LIGHTWEIGHTREACTIONUNICODESANGER LIGHTWEIGHTREACTIONUNICODES = "😡"
	LIGHTWEIGHTREACTIONUNICODESHAHA LIGHTWEIGHTREACTIONUNICODES = "😆"
	LIGHTWEIGHTREACTIONUNICODESLIKE LIGHTWEIGHTREACTIONUNICODES = "👍"
	LIGHTWEIGHTREACTIONUNICODESLOVE LIGHTWEIGHTREACTIONUNICODES = "❤\u{fe0f}"
	LIGHTWEIGHTREACTIONUNICODESSORRY LIGHTWEIGHTREACTIONUNICODES = "😢"
	LIGHTWEIGHTREACTIONUNICODESSUPPORT LIGHTWEIGHTREACTIONUNICODES = "🤗"
	LIGHTWEIGHTREACTIONUNICODESWOW LIGHTWEIGHTREACTIONUNICODES = "😮"
)