type LOGINPORTNUMBER int

const (
	LOGINPORTNUMBERP5222 LOGINPORTNUMBER = 1
	LOGINPORTNUMBERP443 LOGINPORTNUMBER = 2
	LOGINPORTNUMBERP80 LOGINPORTNUMBER = 3
	LOGINPORTNUMBERUNKNOWN LOGINPORTNUMBER = 4
)