type LOGINDNSRESOLVERTYPE int

const (
	LOGINDNSRESOLVERTYPESYSTEM LOGINDNSRESOLVERTYPE = 1
	LOGINDNSRESOLVERTYPEGOOGLE LOGINDNSRESOLVERTYPE = 2
	LOGINDNSRESOLVERTYPEHARDCODED LOGINDNSRESOLVERTYPE = 3
	LOGINDNSRESOLVERTYPENODNS LOGINDNSRESOLVERTYPE = 4
	LOGINDNSRESOLVERTYPEMNS LOGINDNSRESOLVERTYPE = 5
	LOGINDNSRESOLVERTYPESOCKSPROXY LOGINDNSRESOLVERTYPE = 6
	LOGINDNSRESOLVERTYPEMNSSECONDARY LOGINDNSRESOLVERTYPE = 7
)