type LOGOUTREASONTYPE int

const (
	LOGOUTREASONTYPEUNKNOWN LOGOUTREASONTYPE = 0
	LOGOUTREASONTYPENETWORKBLOCKED LOGOUTREASONTYPE = 1
	LOGOUTREASONTYPEWRITINGSTANZAERROR LOGOUTREASONTYPE = 2
	LOGOUTREASONTYPEREADINGSTANZAERRORIO LOGOUTREASONTYPE = 3
	LOGOUTREASONTYPEREADINGSTANZAREADINGISOVER LOGOUTREASONTYPE = 4
	LOGOUTREASONTYPEREADINGSTANZAERRORCORRUPTSTREAM LOGOUTREASONTYPE = 5
	LOGOUTREASONTYPEPUSHWITHSAMESESSIONID LOGOUTREASONTYPE = 6
	LOGOUTREASONTYPESCHEDULEDLOGOUT LOGOUTREASONTYPE = 7
	LOGOUTREASONTYPECLIENTPINGTIMEOUT LOGOUTREASONTYPE = 8
	LOGOUTREASONTYPERECEIPTTIMEOUT LOGOUTREASONTYPE = 9
	LOGOUTREASONTYPEACTIVECONNECTIONTIMEOUT LOGOUTREASONTYPE = 10
	LOGOUTREASONTYPENETWORKCHANGED LOGOUTREASONTYPE = 11
	LOGOUTREASONTYPESWITCHACCOUNT LOGOUTREASONTYPE = 12
	LOGOUTREASONTYPEDELETEACCOUNT LOGOUTREASONTYPE = 13
	LOGOUTREASONTYPECHANGENUMBER LOGOUTREASONTYPE = 14
	LOGOUTREASONTYPEMBSMIGRATION LOGOUTREASONTYPE = 15
	LOGOUTREASONTYPEREGISTRATIONRELATED LOGOUTREASONTYPE = 16
	LOGOUTREASONTYPEROADBLOCKEDDETAIL LOGOUTREASONTYPE = 17
	LOGOUTREASONTYPESERVERACKKICK LOGOUTREASONTYPE = 18
	LOGOUTREASONTYPESERVERPINGKICK LOGOUTREASONTYPE = 19
	LOGOUTREASONTYPECONNECTIONRESET LOGOUTREASONTYPE = 20
)