type LWIDEFAULTTARGETINGSPEC int

const (
	LWIDEFAULTTARGETINGSPECUNKOWN LWIDEFAULTTARGETINGSPEC = 1
	LWIDEFAULTTARGETINGSPECMATCHESTARGETINGSPEC LWIDEFAULTTARGETINGSPEC = 2
	LWIDEFAULTTARGETINGSPECDIFFERSFROMTARGETINGSPEC LWIDEFAULTTARGETINGSPEC = 3
)