type LWISURFACE int

const (
	LWISURFACEADDESIGN LWISURFACE = 1
	LWISURFACEFBWEBSSO LWISURFACE = 2
	LWISURFACELOGINACCOUNTSELECTION LWISURFACE = 3
	LWISURFACERESOLVEPAGEPERMISSION LWISURFACE = 4
	LWISURFACEACCOUNTMANAGEMENT LWISURFACE = 5
)