type LWICTWAADSTATUSTYPE int

const (
	LWICTWAADSTATUSTYPEACTIVE LWICTWAADSTATUSTYPE = 1
	LWICTWAADSTATUSTYPESCHEDULED LWICTWAADSTATUSTYPE = 2
	LWICTWAADSTATUSTYPEPAUSED LWICTWAADSTATUSTYPE = 3
	LWICTWAADSTATUSTYPENOTDELIVERING LWICTWAADSTATUSTYPE = 4
	LWICTWAADSTATUSTYPEREJECTED LWICTWAADSTATUSTYPE = 5
	LWICTWAADSTATUSTYPEFINISHED LWICTWAADSTATUSTYPE = 6
	LWICTWAADSTATUSTYPEINREVIEW LWICTWAADSTATUSTYPE = 7
	LWICTWAADSTATUSTYPECOMPLETED LWICTWAADSTATUSTYPE = 8
	LWICTWAADSTATUSTYPEEXTENDABLE LWICTWAADSTATUSTYPE = 9
	LWICTWAADSTATUSTYPEUNABLETOCREATE LWICTWAADSTATUSTYPE = 10
	LWICTWAADSTATUSTYPELIMITEDDELIVERY LWICTWAADSTATUSTYPE = 11
)