type LWIACTIONTYPE int

const (
	LWIACTIONTYPESTARTLOADING LWIACTIONTYPE = 1
	LWIACTIONTYPESTOPLOADING LWIACTIONTYPE = 2
	LWIACTIONTYPERESUMELOADING LWIACTIONTYPE = 3
	LWIACTIONTYPEERRORLOADING LWIACTIONTYPE = 4
	LWIACTIONTYPEPAUSELOADING LWIACTIONTYPE = 5
)