type MDCHATASSIGNMENTCHATTYPE int

const (
	MDCHATASSIGNMENTCHATTYPEGROUP MDCHATASSIGNMENTCHATTYPE = 0
	MDCHATASSIGNMENTCHATTYPEBROADCASTLIST MDCHATASSIGNMENTCHATTYPE = 1
	MDCHATASSIGNMENTCHATTYPEINDIVIDUAL MDCHATASSIGNMENTCHATTYPE = 2
	MDCHATASSIGNMENTCHATTYPECOMMUNITY MDCHATASSIGNMENTCHATTYPE = 3
	MDCHATASSIGNMENTCHATTYPECHANNEL MDCHATASSIGNMENTCHATTYPE = 4
	MDCHATASSIGNMENTCHATTYPEINTEROP MDCHATASSIGNMENTCHATTYPE = 5
)