type MEDIAAUTODOWNLOADQUALITY int

const (
	MEDIAAUTODOWNLOADQUALITYAUTO MEDIAAUTODOWNLOADQUALITY = 0
	MEDIAAUTODOWNLOADQUALITYSDQUALITY MEDIAAUTODOWNLOADQUALITY = 1
	MEDIAAUTODOWNLOADQUALITYHDQUALITY MEDIAAUTODOWNLOADQUALITY = 2
)