type MEDIASOURCE int

const (
	MEDIASOURCELOCALMEDIAGALLERY MEDIASOURCE = 1
	MEDIASOURCENEWMEDIACAMERA MEDIASOURCE = 2
	MEDIASOURCECATALOGMEDIA MEDIASOURCE = 3
	MEDIASOURCESTATUSMEDIA MEDIASOURCE = 4
	MEDIASOURCEBIZPROFILEIMAGE MEDIASOURCE = 5
	MEDIASOURCEFBMEDIA MEDIASOURCE = 6
	MEDIASOURCEIGMEDIA MEDIASOURCE = 7
)