type MESSAGECAPPINGACTIONTYPE int

const (
	MESSAGECAPPINGACTIONTYPECLICK MESSAGECAPPINGACTIONTYPE = 0
	MESSAGECAPPINGACTIONTYPEVIEW MESSAGECAPPINGACTIONTYPE = 1
	MESSAGECAPPINGACTIONTYPEAPI MESSAGECAPPINGACTIONTYPE = 2
	MESSAGECAPPINGACTIONTYPEENTER MESSAGECAPPINGACTIONTYPE = 3
	MESSAGECAPPINGACTIONTYPEDEBUG MESSAGECAPPINGACTIONTYPE = 4
)