type MESSAGEBIZTYPE int

const (
	MESSAGEBIZTYPENOTBIZMSG MESSAGEBIZTYPE = 0
	MESSAGEBIZTYPEAPIMARKETING MESSAGEBIZTYPE = 1
	MESSAGEBIZTYPEAPIUTILITY MESSAGEBIZTYPE = 2
	MESSAGEBIZTYPEOTHERAPIBIZMSG MESSAGEBIZTYPE = 3
	MESSAGEBIZTYPESMBBIZMSG MESSAGEBIZTYPE = 4
)