type MESSAGECHATTYPE int

const (
	MESSAGECHATTYPEOTHER MESSAGECHATTYPE = 0
	MESSAGECHATTYPEINDIVIDUAL MESSAGECHATTYPE = 1
	MESSAGECHATTYPEGROUP MESSAGECHATTYPE = 2
	MESSAGECHATTYPESTATUS MESSAGECHATTYPE = 3
	MESSAGECHATTYPEBROADCAST MESSAGECHATTYPE = 4
	MESSAGECHATTYPECHANNEL MESSAGECHATTYPE = 5
)