type MESSAGETYPE int

const (
	MESSAGETYPEINDIVIDUAL MESSAGETYPE = 1
	MESSAGETYPEGROUP MESSAGETYPE = 2
	MESSAGETYPEBROADCAST MESSAGETYPE = 3
	MESSAGETYPESTATUS MESSAGETYPE = 4
	MESSAGETYPECHANNEL MESSAGETYPE = 5
	MESSAGETYPEINTEROP MESSAGETYPE = 6
	MESSAGETYPEGREETING MESSAGETYPE = 7
	MESSAGETYPEMEDIAHUB MESSAGETYPE = 8
)