type METAAIACTIONENTRYPOINT int

const (
	METAAIACTIONENTRYPOINTTHREEDOTMENU METAAIACTIONENTRYPOINT = 1
	METAAIACTIONENTRYPOINTTHREADLISTVIEW METAAIACTIONENTRYPOINT = 2
	METAAIACTIONENTRYPOINTTOPNAV METAAIACTIONENTRYPOINT = 3
	METAAIACTIONENTRYPOINTCHATLIST METAAIACTIONENTRYPOINT = 4
	METAAIACTIONENTRYPOINTNAVIGATIONBARBUTTON METAAIACTIONENTRYPOINT = 5
	METAAIACTIONENTRYPOINTCONTINUECHATMODULE METAAIACTIONENTRYPOINT = 6
)