type MISMATCHORIGINTYPE int

const (
	MISMATCHORIGINTYPEINCOMINGGROUPMESSAGE MISMATCHORIGINTYPE = 1
	MISMATCHORIGINTYPEACKOUTGOINGMESSAGE MISMATCHORIGINTYPE = 2
	MISMATCHORIGINTYPEGROUPNOTIFICATION MISMATCHORIGINTYPE = 3
	MISMATCHORIGINTYPEGROUPPROFILEPICTURENOTIFICATION MISMATCHORIGINTYPE = 4
	MISMATCHORIGINTYPEIQRESPONSES MISMATCHORIGINTYPE = 5
)