type MULTIDEVICEACTIONTYPE int

const (
	MULTIDEVICEACTIONTYPELOGIN MULTIDEVICEACTIONTYPE = 0
	MULTIDEVICEACTIONTYPELOGOUT MULTIDEVICEACTIONTYPE = 1
	MULTIDEVICEACTIONTYPECUSTOMAGENTNAME MULTIDEVICEACTIONTYPE = 2
	MULTIDEVICEACTIONTYPEMESSAGEINFO MULTIDEVICEACTIONTYPE = 3
	MULTIDEVICEACTIONTYPEACTIVE MULTIDEVICEACTIONTYPE = 4
	MULTIDEVICEACTIONTYPEDELETE MULTIDEVICEACTIONTYPE = 5
)