type NAVDIRECTIONS string

const (
	NAVDIRECTIONSNEXTBUCKET NAVDIRECTIONS = "next-bucket"
	NAVDIRECTIONSNEXTCARD NAVDIRECTIONS = "next-card"
	NAVDIRECTIONSPREVBUCKET NAVDIRECTIONS = "prev-bucket"
	NAVDIRECTIONSPREVCARD NAVDIRECTIONS = "prev-card"
	NAVDIRECTIONSSTAYHERE NAVDIRECTIONS = "stay_here"
)