type NOTIFICATIONSOURCETYPE int

const (
	NOTIFICATIONSOURCETYPEPUSHTRIGGERED NOTIFICATIONSOURCETYPE = 1
	NOTIFICATIONSOURCETYPEMAINAPP NOTIFICATIONSOURCETYPE = 2
	NOTIFICATIONSOURCETYPEINAPP NOTIFICATIONSOURCETYPE = 3
	NOTIFICATIONSOURCETYPEVOIPPUSHTRIGGERED NOTIFICATIONSOURCETYPE = 4
	NOTIFICATIONSOURCETYPEMAINAPPFOREGROUND NOTIFICATIONSOURCETYPE = 5
)