type NOTIFICATIONSETTINGTYPE int

const (
	NOTIFICATIONSETTINGTYPEALLOWED NOTIFICATIONSETTINGTYPE = 1
	NOTIFICATIONSETTINGTYPEBLOCKED NOTIFICATIONSETTINGTYPE = 2
	NOTIFICATIONSETTINGTYPEUNKNOWN NOTIFICATIONSETTINGTYPE = 3
)