type OFFLINEPROCESSSTAGES int

const (
	OFFLINEPROCESSSTAGESPAGELOAD OFFLINEPROCESSSTAGES = 1
	OFFLINEPROCESSSTAGESSOCKETCONNECT OFFLINEPROCESSSTAGES = 2
	OFFLINEPROCESSSTAGESOFFLINEPREVIEW OFFLINEPROCESSSTAGES = 3
	OFFLINEPROCESSSTAGESPROCESSING OFFLINEPROCESSSTAGES = 4
	OFFLINEPROCESSSTAGESPROCESSCOMPLETE OFFLINEPROCESSSTAGES = 5
	OFFLINEPROCESSSTAGESPROCESSINTERRUPTED OFFLINEPROCESSSTAGES = 6
)