type OFFLINERESUMEMODES int

const (
	OFFLINERESUMEMODESRESUMEFROMRESTART OFFLINERESUMEMODES = 1
	OFFLINERESUMEMODESRESUMEFROMOPENTAB OFFLINERESUMEMODES = 2
	OFFLINERESUMEMODESUNKNOWN OFFLINERESUMEMODES = 3
	OFFLINERESUMEMODESCONNECTREASONUSER OFFLINERESUMEMODES = 4
	OFFLINERESUMEMODESCONNECTREASONPUSH OFFLINERESUMEMODES = 5
	OFFLINERESUMEMODESCONNECTREASONBACKOFF OFFLINERESUMEMODES = 6
)