type OPTIMISTICFLAGTYPE int

const (
	OPTIMISTICFLAGTYPENONE OPTIMISTICFLAGTYPE = 0
	OPTIMISTICFLAGTYPEOPTIMISTIC OPTIMISTICFLAGTYPE = 1
	OPTIMISTICFLAGTYPEOPTUSED OPTIMISTICFLAGTYPE = 2
	OPTIMISTICFLAGTYPEOPTTAKEOVER OPTIMISTICFLAGTYPE = 3
	OPTIMISTICFLAGTYPEOPTDISABLED OPTIMISTICFLAGTYPE = 4
)