type OPUSACTION int

const (
	OPUSACTIONOPUSNOTWORKING OPUSACTION = 0
	OPUSACTIONOPUSJOBRUN OPUSACTION = 1
	OPUSACTIONOPUSFALLBACKRUN OPUSACTION = 2
	OPUSACTIONOPUSMESSAGECLICKED OPUSACTION = 3
	OPUSACTIONOPUSJOBFAILED OPUSACTION = 4
	OPUSACTIONOPUSFALLBACKFAILED OPUSACTION = 5
	OPUSACTIONOPUSHOOKFAILED OPUSACTION = 6
)