type OTPEVENTSOURCE int

const (
	OTPEVENTSOURCENOTIFICATIONCTA OTPEVENTSOURCE = 0
	OTPEVENTSOURCENOTIFICATIONBODY OTPEVENTSOURCE = 1
	OTPEVENTSOURCECHATCTA OTPEVENTSOURCE = 2
	OTPEVENTSOURCEOTHER OTPEVENTSOURCE = 3
	OTPEVENTSOURCEOTPMESSAGE OTPEVENTSOURCE = 4
	OTPEVENTSOURCEOTPMESSAGEINFO OTPEVENTSOURCE = 5
	OTPEVENTSOURCEOTPCONFIGURATION OTPEVENTSOURCE = 6
	OTPEVENTSOURCEOTPREQUESTSENDER OTPEVENTSOURCE = 7
	OTPEVENTSOURCEOTPZEROTAPSENDER OTPEVENTSOURCE = 8
	OTPEVENTSOURCEOTPCONFOPTION OTPEVENTSOURCE = 9
)