type OVERALLMEDIAKEYREUSETYPE int

const (
	OVERALLMEDIAKEYREUSETYPENONENEWCONTENT OVERALLMEDIAKEYREUSETYPE = 1
	OVERALLMEDIAKEYREUSETYPENONEEXPIRED OVERALLMEDIAKEYREUSETYPE = 2
	OVERALLMEDIAKEYREUSETYPEREUSED OVERALLMEDIAKEYREUSETYPE = 3
	OVERALLMEDIAKEYREUSETYPENONEWASSTATUS OVERALLMEDIAKEYREUSETYPE = 4
)