type PAIREDMEDIATYPE int

const (
	PAIREDMEDIATYPESDPHOTO PAIREDMEDIATYPE = 0
	PAIREDMEDIATYPEHDPHOTO PAIREDMEDIATYPE = 1
	PAIREDMEDIATYPESDVIDEO PAIREDMEDIATYPE = 2
	PAIREDMEDIATYPEHDVIDEO PAIREDMEDIATYPE = 3
	PAIREDMEDIATYPEMOTIONPHOTOPARENT PAIREDMEDIATYPE = 4
	PAIREDMEDIATYPEMOTIONPHOTOCHILD PAIREDMEDIATYPE = 5
	PAIREDMEDIATYPEHEVCVIDEOPARENT PAIREDMEDIATYPE = 6
	PAIREDMEDIATYPEHEVCVIDEOCHILD PAIREDMEDIATYPE = 7
)