type PAYMENTACTIONTYPES int

const (
	PAYMENTACTIONTYPESVIEW PAYMENTACTIONTYPES = 0
	PAYMENTACTIONTYPESCLICK PAYMENTACTIONTYPES = 1
	PAYMENTACTIONTYPESENTER PAYMENTACTIONTYPES = 2
	PAYMENTACTIONTYPESAPI PAYMENTACTIONTYPES = 3
	PAYMENTACTIONTYPESSHOWERROR PAYMENTACTIONTYPES = 4
)