type PLACEHOLDERPOPULATIONTYPE int

const (
	PLACEHOLDERPOPULATIONTYPEOTHER PLACEHOLDERPOPULATIONTYPE = 0
	PLACEHOLDERPOPULATIONTYPERETRY PLACEHOLDERPOPULATIONTYPE = 1
	PLACEHOLDERPOPULATIONTYPEPEERMESSAGE PLACEHOLDERPOPULATIONTYPE = 2
	PLACEHOLDERPOPULATIONTYPERESEND PLACEHOLDERPOPULATIONTYPE = 3
)