type PNHACTIONTYPE int

const (
	PNHACTIONTYPESEEMASKEDPNATCHATCREATION PNHACTIONTYPE = 1
	PNHACTIONTYPEREQUESTDIALOGAPPEAR PNHACTIONTYPE = 2
	PNHACTIONTYPESENDREQUEST PNHACTIONTYPE = 3
	PNHACTIONTYPESHAREPNSHEETAPPEAR PNHACTIONTYPE = 4
	PNHACTIONTYPEDISMISS PNHACTIONTYPE = 5
	PNHACTIONTYPESHARENUMBER PNHACTIONTYPE = 6
)