type PNHENTRYPOINTTYPE int

const (
	PNHENTRYPOINTTYPECHATCREATION PNHENTRYPOINTTYPE = 1
	PNHENTRYPOINTTYPECHATINFOREQUEST PNHENTRYPOINTTYPE = 2
	PNHENTRYPOINTTYPEAUDIO PNHENTRYPOINTTYPE = 3
	PNHENTRYPOINTTYPEVIDEO PNHENTRYPOINTTYPE = 4
	PNHENTRYPOINTTYPEPNREQUEST PNHENTRYPOINTTYPE = 5
	PNHENTRYPOINTTYPESYSTEMMESSAGE PNHENTRYPOINTTYPE = 6
	PNHENTRYPOINTTYPECHATINFOPNVISIBILITY PNHENTRYPOINTTYPE = 7
)