type PRECISESIZEBUCKET int

const (
	PRECISESIZEBUCKETLT4 PRECISESIZEBUCKET = 1
	PRECISESIZEBUCKETLT8 PRECISESIZEBUCKET = 2
	PRECISESIZEBUCKETLT16 PRECISESIZEBUCKET = 3
	PRECISESIZEBUCKETLT32 PRECISESIZEBUCKET = 4
	PRECISESIZEBUCKETLT64 PRECISESIZEBUCKET = 5
	PRECISESIZEBUCKETLT128 PRECISESIZEBUCKET = 6
	PRECISESIZEBUCKETLT256 PRECISESIZEBUCKET = 7
	PRECISESIZEBUCKETLT512 PRECISESIZEBUCKET = 8
	PRECISESIZEBUCKETLT1000 PRECISESIZEBUCKET = 9
	PRECISESIZEBUCKETLT1500 PRECISESIZEBUCKET = 10
	PRECISESIZEBUCKETLT2000 PRECISESIZEBUCKET = 11
	PRECISESIZEBUCKETLT2500 PRECISESIZEBUCKET = 12
	PRECISESIZEBUCKETLT3000 PRECISESIZEBUCKET = 13
	PRECISESIZEBUCKETLT3500 PRECISESIZEBUCKET = 14
	PRECISESIZEBUCKETLT4000 PRECISESIZEBUCKET = 15
	PRECISESIZEBUCKETLT4500 PRECISESIZEBUCKET = 16
	PRECISESIZEBUCKETLT5000 PRECISESIZEBUCKET = 17
	PRECISESIZEBUCKETLARGESTBUCKET PRECISESIZEBUCKET = 18
)