type PRIVATEAIFEATURENAME int

const (
	PRIVATEAIFEATURENAMESUMMARIZATION PRIVATEAIFEATURENAME = 0
	PRIVATEAIFEATURENAMEWRITEWITHAI PRIVATEAIFEATURENAME = 1
	PRIVATEAIFEATURENAMEPSI PRIVATEAIFEATURENAME = 2
	PRIVATEAIFEATURENAMEQUICKRECAP PRIVATEAIFEATURENAME = 3
	PRIVATEAIFEATURENAMEINCOGNITO PRIVATEAIFEATURENAME = 4
	PRIVATEAIFEATURENAMESIDECHAT PRIVATEAIFEATURENAME = 5
	PRIVATEAIFEATURENAMEGROUPAI PRIVATEAIFEATURENAME = 6
	PRIVATEAIFEATURENAMEPSISEARCH PRIVATEAIFEATURENAME = 7
)