type PRIVACYTIPACTIONTYPE int

const (
	PRIVACYTIPACTIONTYPEVIEW PRIVACYTIPACTIONTYPE = 1
	PRIVACYTIPACTIONTYPECLICKPRIVACYTIP PRIVACYTIPACTIONTYPE = 2
	PRIVACYTIPACTIONTYPECLICKOK PRIVACYTIPACTIONTYPE = 3
	PRIVACYTIPACTIONTYPECLICKOUTSIDE PRIVACYTIPACTIONTYPE = 4
)