type PROFILEPICTURETYPE int

const (
	PROFILEPICTURETYPEPHOTOCAMERA PROFILEPICTURETYPE = 1
	PROFILEPICTURETYPEPHOTOUPLOAD PROFILEPICTURETYPE = 2
	PROFILEPICTURETYPEWEBSEARCH PROFILEPICTURETYPE = 3
	PROFILEPICTURETYPEEMOJI PROFILEPICTURETYPE = 4
	PROFILEPICTURETYPESTICKER PROFILEPICTURETYPE = 5
	PROFILEPICTURETYPEREMOVEPHOTO PROFILEPICTURETYPE = 6
)