type PROMPTTRIGGERPOINT int

const (
	PROMPTTRIGGERPOINTUSERINPUT PROMPTTRIGGERPOINT = 1
	PROMPTTRIGGERPOINTCONVERSATIONSTARTER PROMPTTRIGGERPOINT = 2
	PROMPTTRIGGERPOINTAIHOMEQP PROMPTTRIGGERPOINT = 3
)