type PTTPLAYERTYPE int

const (
	PTTPLAYERTYPEAUDIOQUEUE PTTPLAYERTYPE = 0
	PTTPLAYERTYPEAVPLAYER PTTPLAYERTYPE = 1
	PTTPLAYERTYPEAVAUDIOPLAYER PTTPLAYERTYPE = 2
	PTTPLAYERTYPEOPUSPLAYER PTTPLAYERTYPE = 3
	PTTPLAYERTYPEANDROIDPLAYER PTTPLAYERTYPE = 4
	PTTPLAYERTYPEEXOPLAYER PTTPLAYERTYPE = 5
	PTTPLAYERTYPEUWPPLAYER PTTPLAYERTYPE = 6
	PTTPLAYERTYPEVOIPPLAYER PTTPLAYERTYPE = 7
)