type PTTSTREAMTYPE int

const (
	PTTSTREAMTYPEUNKNOWN PTTSTREAMTYPE = 0
	PTTSTREAMTYPEAAC PTTSTREAMTYPE = 1
	PTTSTREAMTYPEMP3 PTTSTREAMTYPE = 2
	PTTSTREAMTYPEAMRNB PTTSTREAMTYPE = 3
	PTTSTREAMTYPEAMRWB PTTSTREAMTYPE = 4
	PTTSTREAMTYPEOPUS PTTSTREAMTYPE = 5
	PTTSTREAMTYPEMULTIPLETRACKS PTTSTREAMTYPE = 6
)