type QUERYTYPE int

const (
	QUERYTYPESTICKERSTOREDATA QUERYTYPE = 0
	QUERYTYPEPREVIEWIMAGEDOWNLOAD QUERYTYPE = 1
	QUERYTYPESTICKERPACKDATA QUERYTYPE = 2
	QUERYTYPESTICKERSEARCH QUERYTYPE = 3
	QUERYTYPEDISCOVERYPACK QUERYTYPE = 4
)