type QUICKREPLYACTION int

const (
	QUICKREPLYACTIONACTIONSETTINGSIMPRESSION QUICKREPLYACTION = 1
	QUICKREPLYACTIONACTIONSETTINGSADDCLICK QUICKREPLYACTION = 2
	QUICKREPLYACTIONACTIONSETTINGSADDABANDONED QUICKREPLYACTION = 3
	QUICKREPLYACTIONACTIONSETTINGSADDED QUICKREPLYACTION = 4
	QUICKREPLYACTIONACTIONSETTINGSDELETED QUICKREPLYACTION = 5
	QUICKREPLYACTIONACTIONCHATIMPRESSION QUICKREPLYACTION = 6
	QUICKREPLYACTIONACTIONCHATCLICK QUICKREPLYACTION = 7
	QUICKREPLYACTIONACTIONSETTINGSEDITED QUICKREPLYACTION = 8
	QUICKREPLYACTIONACTIONCHATINVALIDATTACHMENTS QUICKREPLYACTION = 9
	QUICKREPLYACTIONACTIONSETTINGSINVALIDATTACHMENTS QUICKREPLYACTION = 10
	QUICKREPLYACTIONACTIONSETTINGSMEDIATRANSCODE QUICKREPLYACTION = 11
	QUICKREPLYACTIONACTIONCHATCLICKCANCEL QUICKREPLYACTION = 12
	QUICKREPLYACTIONACTIONSMARTDEFAULTCLICK QUICKREPLYACTION = 13
	QUICKREPLYACTIONQUICKREPLYMESSAGESENT QUICKREPLYACTION = 14
)