type REACHABILITYSTATUS int

const (
	REACHABILITYSTATUSNOTREACHABLE REACHABILITYSTATUS = 0
	REACHABILITYSTATUSREACHABLEVIAWIFI REACHABILITYSTATUS = 1
	REACHABILITYSTATUSREACHABLEVIAWWAN REACHABILITYSTATUS = 2
	REACHABILITYSTATUSREACHABILITYUNKNOWN REACHABILITYSTATUS = 3
)