type REACHOUTTIMELOCKACTION int

const (
	REACHOUTTIMELOCKACTIONIMPRESSION REACHOUTTIMELOCKACTION = 1
	REACHOUTTIMELOCKACTIONSMBMMBBOPTIONIMPRESSION REACHOUTTIMELOCKACTION = 2
	REACHOUTTIMELOCKACTIONCLICKBUSINESSTOOLS REACHOUTTIMELOCKACTION = 3
)