type READSOURCE int

const (
	READSOURCEOTHER READSOURCE = 0
	READSOURCECHAT READSOURCE = 1
	READSOURCENOTIFICATION READSOURCE = 2
	READSOURCEMARKASREAD READSOURCE = 3
	READSOURCEMULTIDEVICESYNC READSOURCE = 4
)