type RECEIPTAGGREGATIONTYPE int

const (
	RECEIPTAGGREGATIONTYPENONE RECEIPTAGGREGATIONTYPE = 0
	RECEIPTAGGREGATIONTYPEMULTIMESSAGES RECEIPTAGGREGATIONTYPE = 1
	RECEIPTAGGREGATIONTYPEMULTIPARTICIPANTS RECEIPTAGGREGATIONTYPE = 2
	RECEIPTAGGREGATIONTYPEAGGREGATEBYID RECEIPTAGGREGATIONTYPE = 3
)