type REFERRERACTION int

const (
	REFERRERACTIONNULLSTATEASKMETAAI REFERRERACTION = 1
	REFERRERACTIONTYPEAHEADASKMETAAI REFERRERACTION = 2
	REFERRERACTIONNULLSTATEPAPERPLANE REFERRERACTION = 3
	REFERRERACTIONTYPEAHEADPAPERPLANE REFERRERACTION = 4
	REFERRERACTIONTYPEAHEADSEND REFERRERACTION = 5
	REFERRERACTIONFAVICON REFERRERACTION = 6
	REFERRERACTIONTHREADOPEN REFERRERACTION = 7
	REFERRERACTIONMYSTATUSOVERLFOWMENUOPTION REFERRERACTION = 8
	REFERRERACTIONAIWIDGET REFERRERACTION = 9
	REFERRERACTIONFABMMTAP REFERRERACTION = 10
	REFERRERACTIONNORESULTSTATEASKMETAAI REFERRERACTION = 11
	REFERRERACTIONMETAAITHREADLIST REFERRERACTION = 12
)