type RETRYREJECTREASON int

const (
	RETRYREJECTREASONOTHER RETRYREJECTREASON = 0
	RETRYREJECTREASONDOUBLECHECKMARK RETRYREJECTREASON = 1
	RETRYREJECTREASONIDENTITYCHANGE RETRYREJECTREASON = 2
	RETRYREJECTREASONMESSAGENOTEXIST RETRYREJECTREASON = 3
	RETRYREJECTREASONHIGHRETRYCOUNT RETRYREJECTREASON = 4
	RETRYREJECTREASONMESSAGEEXPIRED RETRYREJECTREASON = 5
	RETRYREJECTREASONSTATUSEXPIRED RETRYREJECTREASON = 6
	RETRYREJECTREASONINCORRECTCHATTYPE RETRYREJECTREASON = 7
	RETRYREJECTREASONRECEIPTNOTFOUND RETRYREJECTREASON = 8
	RETRYREJECTREASONDEVICENOTRECIPIENT RETRYREJECTREASON = 9
	RETRYREJECTREASONHOSTEDDEVICECHANGED RETRYREJECTREASON = 10
	RETRYREJECTREASONDEVICENOTINDATABASE RETRYREJECTREASON = 11
	RETRYREJECTREASONDEVICEREVOKED RETRYREJECTREASON = 12
)