type RINGTONEENTRYTYPE int

const (
	RINGTONEENTRYTYPEAPPWIDE RINGTONEENTRYTYPE = 0
	RINGTONEENTRYTYPEONETOONE RINGTONEENTRYTYPE = 1
	RINGTONEENTRYTYPEGROUP RINGTONEENTRYTYPE = 2
	RINGTONEENTRYTYPELIST RINGTONEENTRYTYPE = 3
)