type SEARCHUJCRITERIATYPE int

const (
	SEARCHUJCRITERIATYPETEXTMATCHFILTER SEARCHUJCRITERIATYPE = 1
	SEARCHUJCRITERIATYPEUNREADFILTER SEARCHUJCRITERIATYPE = 2
	SEARCHUJCRITERIATYPEMEDIATYPEFILTER SEARCHUJCRITERIATYPE = 3
	SEARCHUJCRITERIATYPECONTACTFILTER SEARCHUJCRITERIATYPE = 4
	SEARCHUJCRITERIATYPENONCONTACTSFILTER SEARCHUJCRITERIATYPE = 5
	SEARCHUJCRITERIATYPEBUSINESSFILTER SEARCHUJCRITERIATYPE = 6
	SEARCHUJCRITERIATYPEOTHER SEARCHUJCRITERIATYPE = 7
)