type SEARCHUJITEMTYPE int

const (
	SEARCHUJITEMTYPEAISUGGESTION SEARCHUJITEMTYPE = 1
	SEARCHUJITEMTYPECHAT SEARCHUJITEMTYPE = 2
	SEARCHUJITEMTYPECONTACT SEARCHUJITEMTYPE = 3
	SEARCHUJITEMTYPEINVITE SEARCHUJITEMTYPE = 4
	SEARCHUJITEMTYPEMESSAGE SEARCHUJITEMTYPE = 5
	SEARCHUJITEMTYPEGROUPINCOMMON SEARCHUJITEMTYPE = 6
	SEARCHUJITEMTYPEMEDIA SEARCHUJITEMTYPE = 7
	SEARCHUJITEMTYPEBUSINESS SEARCHUJITEMTYPE = 8
	SEARCHUJITEMTYPERECENTSEARCHINDIVIDUALSUGGESTION SEARCHUJITEMTYPE = 9
	SEARCHUJITEMTYPERECENTSEARCHGROUPSUGGESTION SEARCHUJITEMTYPE = 10
	SEARCHUJITEMTYPECONTACTFROMCOMMONGROUP SEARCHUJITEMTYPE = 11
	SEARCHUJITEMTYPEUNKNOWNCONTACT SEARCHUJITEMTYPE = 12
	SEARCHUJITEMTYPECOMMUNITY SEARCHUJITEMTYPE = 13
	SEARCHUJITEMTYPEPUSHNAME SEARCHUJITEMTYPE = 14
)