type SEARCHUJFILTERTYPE int

const (
	SEARCHUJFILTERTYPEPHOTO SEARCHUJFILTERTYPE = 1
	SEARCHUJFILTERTYPEVIDEO SEARCHUJFILTERTYPE = 2
	SEARCHUJFILTERTYPELINK SEARCHUJFILTERTYPE = 3
	SEARCHUJFILTERTYPEGIF SEARCHUJFILTERTYPE = 4
	SEARCHUJFILTERTYPEAUDIO SEARCHUJFILTERTYPE = 5
	SEARCHUJFILTERTYPEDOCUMENT SEARCHUJFILTERTYPE = 6
	SEARCHUJFILTERTYPESTICKER SEARCHUJFILTERTYPE = 7
	SEARCHUJFILTERTYPEPOLL SEARCHUJFILTERTYPE = 8
	SEARCHUJFILTERTYPEOTHER SEARCHUJFILTERTYPE = 9
)