type SELECTEDLAYOUTCONFIGID int

const (
	SELECTEDLAYOUTCONFIGIDONEBYTWO SELECTEDLAYOUTCONFIGID = 1
	SELECTEDLAYOUTCONFIGIDONEANDTWO SELECTEDLAYOUTCONFIGID = 2
	SELECTEDLAYOUTCONFIGIDONEBYTHREE SELECTEDLAYOUTCONFIGID = 3
	SELECTEDLAYOUTCONFIGIDTWOBYTWO SELECTEDLAYOUTCONFIGID = 4
	SELECTEDLAYOUTCONFIGIDTWOONETWO SELECTEDLAYOUTCONFIGID = 5
	SELECTEDLAYOUTCONFIGIDTWOBYTHREE SELECTEDLAYOUTCONFIGID = 6
)