type SETTINGTYPE int

const (
	SETTINGTYPEHYBRIDSTARTUP SETTINGTYPE = 0
	SETTINGTYPEHYBRIDSYSTEMTRAY SETTINGTYPE = 1
	SETTINGTYPELANGUAGE SETTINGTYPE = 2
	SETTINGTYPEREPLACETEXTWITHEMOJI SETTINGTYPE = 3
	SETTINGTYPEBANNERNOTIFICATIONDISPLAYMODE SETTINGTYPE = 4
	SETTINGTYPEUNREADCOUNTERBADGEDISPLAYMODE SETTINGTYPE = 5
	SETTINGTYPEISMESSAGESNOTIFICATIONENABLED SETTINGTYPE = 6
	SETTINGTYPEISCALLSNOTIFICATIONENABLED SETTINGTYPE = 7
	SETTINGTYPEISREACTIONSNOTIFICATIONENABLED SETTINGTYPE = 8
	SETTINGTYPEISSTATUSREACTIONSNOTIFICATIONENABLED SETTINGTYPE = 9
	SETTINGTYPEISTEXTPREVIEWFORNOTIFICATIONENABLED SETTINGTYPE = 10
	SETTINGTYPEDEFAULTNOTIFICATIONTONEID SETTINGTYPE = 11
	SETTINGTYPEGROUPDEFAULTNOTIFICATIONTONEID SETTINGTYPE = 12
	SETTINGTYPEAPPTHEME SETTINGTYPE = 13
	SETTINGTYPEWALLPAPERID SETTINGTYPE = 14
	SETTINGTYPEISDOODLEWALLPAPERENABLED SETTINGTYPE = 15
	SETTINGTYPEFONTSIZE SETTINGTYPE = 16
	SETTINGTYPEISPHOTOSAUTODOWNLOADENABLED SETTINGTYPE = 17
	SETTINGTYPEISAUDIOSAUTODOWNLOADENABLED SETTINGTYPE = 18
	SETTINGTYPEISVIDEOSAUTODOWNLOADENABLED SETTINGTYPE = 19
	SETTINGTYPEISDOCUMENTSAUTODOWNLOADENABLED SETTINGTYPE = 20
	SETTINGTYPEDISABLELINKPREVIEWS SETTINGTYPE = 21
	SETTINGTYPENOTIFICATIONTONEID SETTINGTYPE = 22
	SETTINGTYPEMEDIAUPLOADQUALITY SETTINGTYPE = 23
	SETTINGTYPEISSPELLCHECKENABLED SETTINGTYPE = 24
	SETTINGTYPEISENTERTOSENDENABLED SETTINGTYPE = 25
	SETTINGTYPEISGROUPMESSAGENOTIFICATIONENABLED SETTINGTYPE = 26
	SETTINGTYPEISGROUPREACTIONSNOTIFICATIONENABLED SETTINGTYPE = 27
	SETTINGTYPEISSTATUSNOTIFICATIONENABLED SETTINGTYPE = 28
	SETTINGTYPESTATUSNOTIFICATIONTONEID SETTINGTYPE = 29
	SETTINGTYPESHOULDPLAYSOUNDFORCALLNOTIFICATION SETTINGTYPE = 30
	SETTINGTYPECHATTHEMEID SETTINGTYPE = 31
	SETTINGTYPECOLORSCHEMEID SETTINGTYPE = 32
	SETTINGTYPEISTEXTMESSAGEANIMATIONENABLED SETTINGTYPE = 33
	SETTINGTYPESTOCKWALLPAPERIMAGEID SETTINGTYPE = 34
)