type SETTINGSCLICKENTRYPOINT int

const (
	SETTINGSCLICKENTRYPOINTSETTINGSSCREEN SETTINGSCLICKENTRYPOINT = 0
	SETTINGSCLICKENTRYPOINTSETTINGSSEARCH SETTINGSCLICKENTRYPOINT = 1
	SETTINGSCLICKENTRYPOINTDEEPLINK SETTINGSCLICKENTRYPOINT = 2
	SETTINGSCLICKENTRYPOINTPRIVACYCHECKUP SETTINGSCLICKENTRYPOINT = 3
	SETTINGSCLICKENTRYPOINTMETABSCREEN SETTINGSCLICKENTRYPOINT = 4
	SETTINGSCLICKENTRYPOINTTHREEDOTMENU SETTINGSCLICKENTRYPOINT = 5
)