type SETTING int

const (
	SETTINGALLCONTACTS SETTING = 1
	SETTINGALLCONTACTSEXCEPT SETTING = 2
	SETTINGONLYSHAREWITHCONTACTS SETTING = 3
	SETTINGONLYSHAREWITHCLOSEFRIENDS SETTING = 4
	SETTINGONLYSHAREWITHCUSTOMLIST SETTING = 5
	SETTINGGROUPSTATUS SETTING = 6
)