type SIGNALTYPE int

const (
	SIGNALTYPEMMCLICK SIGNALTYPE = 0
	SIGNALTYPEUSERBLOCK SIGNALTYPE = 1
	SIGNALTYPEUSERREPORT SIGNALTYPE = 2
	SIGNALTYPEFIRSTCUSTOMERMESSAGE SIGNALTYPE = 3
	SIGNALTYPEFIRSTCUSTOMERMESSAGECONTINUATION SIGNALTYPE = 4
	SIGNALTYPEFIRSTBIZREPLY SIGNALTYPE = 5
	SIGNALTYPEFIRSTBIZREPLYCONTINUATION SIGNALTYPE = 6
	SIGNALTYPESECONDCUSTOMERMESSAGE SIGNALTYPE = 7
	SIGNALTYPESECONDCUSTOMERMESSAGECONTINUATION SIGNALTYPE = 8
	SIGNALTYPESECONDBIZREPLY SIGNALTYPE = 9
	SIGNALTYPESECONDBIZREPLYCONTINUATION SIGNALTYPE = 10
	SIGNALTYPETHIRDCUSTOMERMESSAGE SIGNALTYPE = 11
	SIGNALTYPETHIRDCUSTOMERMESSAGECONTINUATION SIGNALTYPE = 12
	SIGNALTYPETHIRDBIZREPLY SIGNALTYPE = 13
	SIGNALTYPEUSERINTERESTED SIGNALTYPE = 14
	SIGNALTYPEUSERNOTINTERESTED SIGNALTYPE = 15
	SIGNALTYPEUSERSTOPOFFERS SIGNALTYPE = 16
	SIGNALTYPEUSERBLOCKREASONNOLONGERNEEDED SIGNALTYPE = 17
	SIGNALTYPEUSERBLOCKREASONNOSIGNUP SIGNALTYPE = 18
	SIGNALTYPEUSERBLOCKREASONSPAM SIGNALTYPE = 19
	SIGNALTYPEUSERBLOCKREASONOFFENSIVEMESSAGES SIGNALTYPE = 20
	SIGNALTYPEUSERBLOCKREASONOTPDIDNOTREQUEST SIGNALTYPE = 21
	SIGNALTYPEUSERBLOCKREASONOTHER SIGNALTYPE = 22
	SIGNALTYPEUSERMUTE SIGNALTYPE = 23
	SIGNALTYPEUSERBLOCKREASONSCAMORFRAUD SIGNALTYPE = 24
	SIGNALTYPEMESSAGE SIGNALTYPE = 25
	SIGNALTYPEUSERARCHIVE SIGNALTYPE = 26
	SIGNALTYPEUSERBLOCKREASONDONTRECOGNIZE SIGNALTYPE = 27
	SIGNALTYPEIABLPV SIGNALTYPE = 28
	SIGNALTYPEIABLPVBODY SIGNALTYPE = 29
)