type SIGNUPENTRYPOINT int

const (
	SIGNUPENTRYPOINTCHATTHREADBUSINESS SIGNUPENTRYPOINT = 0
	SIGNUPENTRYPOINTCHATTHREADOTHER SIGNUPENTRYPOINT = 1
	SIGNUPENTRYPOINTCHANNELS SIGNUPENTRYPOINT = 2
	SIGNUPENTRYPOINTSTATUS SIGNUPENTRYPOINT = 3
	SIGNUPENTRYPOINTFACEBOOK SIGNUPENTRYPOINT = 4
	SIGNUPENTRYPOINTINSTAGRAM SIGNUPENTRYPOINT = 5
	SIGNUPENTRYPOINTEXTERNAL SIGNUPENTRYPOINT = 6
	SIGNUPENTRYPOINTMESSENGER SIGNUPENTRYPOINT = 7
	SIGNUPENTRYPOINTTHREADS SIGNUPENTRYPOINT = 8
)