type SMBUSERACTIONTYPEENUM int

const (
	SMBUSERACTIONTYPEENUMVIEW SMBUSERACTIONTYPEENUM = 0
	SMBUSERACTIONTYPEENUMCLICK SMBUSERACTIONTYPEENUM = 1
	SMBUSERACTIONTYPEENUMENTER SMBUSERACTIONTYPEENUM = 2
	SMBUSERACTIONTYPEENUMSCROLL SMBUSERACTIONTYPEENUM = 3
	SMBUSERACTIONTYPEENUMSCAN SMBUSERACTIONTYPEENUM = 4
	SMBUSERACTIONTYPEENUMAPI SMBUSERACTIONTYPEENUM = 5
	SMBUSERACTIONTYPEENUMEDIT SMBUSERACTIONTYPEENUM = 6
	SMBUSERACTIONTYPEENUMDELETE SMBUSERACTIONTYPEENUM = 7
	SMBUSERACTIONTYPEENUMSEARCH SMBUSERACTIONTYPEENUM = 8
	SMBUSERACTIONTYPEENUMDISMISS SMBUSERACTIONTYPEENUM = 9
	SMBUSERACTIONTYPEENUMVALIDATION SMBUSERACTIONTYPEENUM = 10
	SMBUSERACTIONTYPEENUMREAD SMBUSERACTIONTYPEENUM = 11
	SMBUSERACTIONTYPEENUMWRITE SMBUSERACTIONTYPEENUM = 12
	SMBUSERACTIONTYPEENUMSUPPRESS SMBUSERACTIONTYPEENUM = 13
)