type STANZATYPE int

const (
	STANZATYPEMESSAGE STANZATYPE = 1
	STANZATYPERECEIPT STANZATYPE = 2
	STANZATYPECALL STANZATYPE = 3
	STANZATYPENOTIFICATION STANZATYPE = 4
	STANZATYPEAPPDATA STANZATYPE = 5
	STANZATYPESTATUS STANZATYPE = 6
)