type STATUSTYPE int

const (
	STATUSTYPEIMAGE STATUSTYPE = 1
	STATUSTYPEVIDEO STATUSTYPE = 2
	STATUSTYPEGIF STATUSTYPE = 3
	STATUSTYPEAUDIO STATUSTYPE = 4
	STATUSTYPETEXT STATUSTYPE = 5
	STATUSTYPEMUSICSTANDALONE STATUSTYPE = 6
	STATUSTYPEFUTURE STATUSTYPE = 7
	STATUSTYPEPLACEHOLDER STATUSTYPE = 8
	STATUSTYPEINLINEVIDEO STATUSTYPE = 9
	STATUSTYPELOCATION STATUSTYPE = 10
)