type STATUSPRIVACYTYPE int

const (
	STATUSPRIVACYTYPEALLCONTACTS STATUSPRIVACYTYPE = 1
	STATUSPRIVACYTYPEEXCEPT STATUSPRIVACYTYPE = 2
	STATUSPRIVACYTYPEONLYWITH STATUSPRIVACYTYPE = 3
	STATUSPRIVACYTYPECLOSEFRIENDS STATUSPRIVACYTYPE = 4
	STATUSPRIVACYTYPECUSTOMLIST STATUSPRIVACYTYPE = 5
	STATUSPRIVACYTYPEGROUPSTATUS STATUSPRIVACYTYPE = 6
)