type STATUSVIEWENTRYMETHOD int

const (
	STATUSVIEWENTRYMETHODFORWARDTAP STATUSVIEWENTRYMETHOD = 1
	STATUSVIEWENTRYMETHODBACKTAP STATUSVIEWENTRYMETHOD = 2
	STATUSVIEWENTRYMETHODFORWARDSWIPE STATUSVIEWENTRYMETHOD = 3
	STATUSVIEWENTRYMETHODBACKSWIPE STATUSVIEWENTRYMETHOD = 4
	STATUSVIEWENTRYMETHODDIRECTPOGTAP STATUSVIEWENTRYMETHOD = 5
	STATUSVIEWENTRYMETHODAUTONAVIGATETIMEREND STATUSVIEWENTRYMETHOD = 6
	STATUSVIEWENTRYMETHODSTATUSWIDGET STATUSVIEWENTRYMETHOD = 7
	STATUSVIEWENTRYMETHODCHAININGPILLTAP STATUSVIEWENTRYMETHOD = 8
	STATUSVIEWENTRYMETHODENGAGEMENTCARDCTATAP STATUSVIEWENTRYMETHOD = 9
	STATUSVIEWENTRYMETHODMYSTATUSESSCREEN STATUSVIEWENTRYMETHOD = 10
)