type STATUSPOSTFAILURESTAGE int

const (
	STATUSPOSTFAILURESTAGEUNKNOWN STATUSPOSTFAILURESTAGE = 0
	STATUSPOSTFAILURESTAGEPREKEYSFETCH STATUSPOSTFAILURESTAGE = 1
	STATUSPOSTFAILURESTAGEENCRYPT STATUSPOSTFAILURESTAGE = 2
	STATUSPOSTFAILURESTAGEREADYTOSEND STATUSPOSTFAILURESTAGE = 3
	STATUSPOSTFAILURESTAGEWRITTENWIRE STATUSPOSTFAILURESTAGE = 4
	STATUSPOSTFAILURESTAGEAWAITINGSERVERACK STATUSPOSTFAILURESTAGE = 5
	STATUSPOSTFAILURESTAGESERVERACKRECEIVED STATUSPOSTFAILURESTAGE = 6
)