type STICKERTYPE int

const (
	STICKERTYPEUNKNOWN STICKERTYPE = 0
	STICKERTYPEARROW STICKERTYPE = 1
	STICKERTYPEOVAL STICKERTYPE = 2
	STICKERTYPERECT STICKERTYPE = 3
	STICKERTYPETHINKINGBUBBLE STICKERTYPE = 4
	STICKERTYPESPEECHBUBBLEOVAL STICKERTYPE = 5
	STICKERTYPESPEECHBUBBLERECT STICKERTYPE = 6
	STICKERTYPEDIGITALCLOCK STICKERTYPE = 7
	STICKERTYPEANALOGCLOCK STICKERTYPE = 8
	STICKERTYPELOCATION STICKERTYPE = 9
	STICKERTYPEADDYOURS STICKERTYPE = 10
	STICKERTYPENORMALSTICKER STICKERTYPE = 11
	STICKERTYPEEMOJISTICKER STICKERTYPE = 12
	STICKERTYPEPHOTO STICKERTYPE = 13
	STICKERTYPEMUSIC STICKERTYPE = 14
	STICKERTYPESTATUSAPI STICKERTYPE = 15
	STICKERTYPEQUESTION STICKERTYPE = 16
	STICKERTYPEQUESTIONANSWER STICKERTYPE = 17
	STICKERTYPEREACTIONSTICKER STICKERTYPE = 18
	STICKERTYPENYE2026 STICKERTYPE = 19
)