type STICKERMAKERSOURCETYPE int

const (
	STICKERMAKERSOURCETYPECUTOUTIMAGE STICKERMAKERSOURCETYPE = 1
	STICKERMAKERSOURCETYPEWEBSTICKERMAKER STICKERMAKERSOURCETYPE = 2
	STICKERMAKERSOURCETYPEIOSSTICKERMAKER STICKERMAKERSOURCETYPE = 3
	STICKERMAKERSOURCETYPEANDROIDSTICKERMAKER STICKERMAKERSOURCETYPE = 4
	STICKERMAKERSOURCETYPETRANSPARENTIMAGE STICKERMAKERSOURCETYPE = 5
	STICKERMAKERSOURCETYPEGIF STICKERMAKERSOURCETYPE = 6
)