type STICKERSENDMESSAGETYPE int

const (
	STICKERSENDMESSAGETYPEREGULAR STICKERSENDMESSAGETYPE = 1
	STICKERSENDMESSAGETYPEPAYMENTS STICKERSENDMESSAGETYPE = 2
	STICKERSENDMESSAGETYPEANNOTATION STICKERSENDMESSAGETYPE = 3
)