type STICKERERRORTYPE int

const (
	STICKERERRORTYPEDECOMPRESSION STICKERERRORTYPE = 2
	STICKERERRORTYPESENDERVALIDATION STICKERERRORTYPE = 3
	STICKERERRORTYPERECEIVERVALIDATION STICKERERRORTYPE = 4
)