type STORYOVERLAYTYPES string

const (
	STORYOVERLAYTYPESBLOKSTICKER STORYOVERLAYTYPES = "StoryOverlayBloksSticker"
	STORYOVERLAYTYPESCHANNELSTICKER STORYOVERLAYTYPES = "StoryOverlayChannelSticker"
	STORYOVERLAYTYPESCOUNTDOWNSTICKER STORYOVERLAYTYPES = "XFBStoryOverlayCountdownSticker"
	STORYOVERLAYTYPESEXTERNALSONG STORYOVERLAYTYPES = "StoryOverlayExternalSong"
	STORYOVERLAYTYPESFBNOTESSTICKER STORYOVERLAYTYPES = "StoryOverlayFBNotesSticker"
	STORYOVERLAYTYPESGROUPENTITYSTICKER STORYOVERLAYTYPES = "StoryOverlayGroupEntitySticker"
	STORYOVERLAYTYPESHASHTAGSTICKER STORYOVERLAYTYPES = "StoryOverlayHashtagSticker"
	STORYOVERLAYTYPESINTERACTIVESTICKER STORYOVERLAYTYPES = "StoryOverlayReactionSticker"
	STORYOVERLAYTYPESLINKSTICKER STORYOVERLAYTYPES = "StoryOverlayLinkSticker"
	STORYOVERLAYTYPESLIVEVIDEO STORYOVERLAYTYPES = "StoryOverlayLiveVideo"
	STORYOVERLAYTYPESLOCATIONSTICKER STORYOVERLAYTYPES = "StoryOverlayLocationSticker"
	STORYOVERLAYTYPESPOLLSTICKER STORYOVERLAYTYPES = "StoryOverlayPollSticker"
	STORYOVERLAYTYPESPRODUCTSTICKER STORYOVERLAYTYPES = "StoryOverlayProductSticker"
	STORYOVERLAYTYPESREELSSTICKER STORYOVERLAYTYPES = "StoryOverlayResharedFbShortsSticker"
	STORYOVERLAYTYPESRESHAREDCONTENT STORYOVERLAYTYPES = "StoryOverlayResharedContent"
	STORYOVERLAYTYPESRESHAREDPOST STORYOVERLAYTYPES = "StoryOverlayResharedPost"
	STORYOVERLAYTYPESSLIDERPOLLSTICKER STORYOVERLAYTYPES = "StoryOverlaySliderPollSticker"
	STORYOVERLAYTYPESSUBSCRIBESTICKER STORYOVERLAYTYPES = "StoryOverlaySubscribeSticker"
	STORYOVERLAYTYPESTAGSTICKER STORYOVERLAYTYPES = "StoryOverlayTagSticker"
)