type STREAMSOCKETPROVIDERTYPE int

const (
	STREAMSOCKETPROVIDERTYPEUNKNOWNSOCKET STREAMSOCKETPROVIDERTYPE = 0
	STREAMSOCKETPROVIDERTYPEPLATFORMSOCKET STREAMSOCKETPROVIDERTYPE = 1
	STREAMSOCKETPROVIDERTYPEMNSSOCKET STREAMSOCKETPROVIDERTYPE = 2
	STREAMSOCKETPROVIDERTYPESOCKSPROXY STREAMSOCKETPROVIDERTYPE = 3
)