type STWENTRYPOINT int

const (
	STWENTRYPOINTHIGHLYFORWARDEDMESSAGE STWENTRYPOINT = 0
	STWENTRYPOINTURLLONGPRESS STWENTRYPOINT = 1
	STWENTRYPOINTMEDIAVIEWER STWENTRYPOINT = 2
	STWENTRYPOINTCONTEXTMENU STWENTRYPOINT = 3
)