type SUBFUNNELTYPE int

const (
	SUBFUNNELTYPETEXT SUBFUNNELTYPE = 1
	SUBFUNNELTYPEPTT SUBFUNNELTYPE = 2
	SUBFUNNELTYPEREACTION SUBFUNNELTYPE = 3
	SUBFUNNELTYPESHARECONTENT SUBFUNNELTYPE = 4
	SUBFUNNELTYPEEXPRESSIONTRAY SUBFUNNELTYPE = 5
	SUBFUNNELTYPEMEDIASHARING SUBFUNNELTYPE = 6
	SUBFUNNELTYPEQUOTEDMESSAGE SUBFUNNELTYPE = 7
	SUBFUNNELTYPEFORWARDACTION SUBFUNNELTYPE = 8
)