type THREADCREATIONTIME int

const (
	THREADCREATIONTIMELESSTHAN1DAYAGO THREADCREATIONTIME = 0
	THREADCREATIONTIMELESSTHAN7DAYSAGO THREADCREATIONTIME = 1
	THREADCREATIONTIMELESSTHAN30DAYSAGO THREADCREATIONTIME = 2
	THREADCREATIONTIMEMORETHAN30DAYSAGO THREADCREATIONTIME = 3
)