type THREADACTIONTYPES int

const (
	THREADACTIONTYPESPIN THREADACTIONTYPES = 1
	THREADACTIONTYPESUNPIN THREADACTIONTYPES = 2
	THREADACTIONTYPESDELETE THREADACTIONTYPES = 3
	THREADACTIONTYPESRENAME THREADACTIONTYPES = 4
	THREADACTIONTYPESCLICKNEWCHAT THREADACTIONTYPES = 5
	THREADACTIONTYPESCLICKCHATHISTORY THREADACTIONTYPES = 6
	THREADACTIONTYPESCLICKCONVERSATIONTHREAD THREADACTIONTYPES = 7
	THREADACTIONTYPESTHREADENTER THREADACTIONTYPES = 8
	THREADACTIONTYPESTHREADEXIT THREADACTIONTYPES = 9
	THREADACTIONTYPESTHREADLISTIMPRESSION THREADACTIONTYPES = 10
	THREADACTIONTYPESTHREEDOTMENU THREADACTIONTYPES = 11
	THREADACTIONTYPESFIRSTPROMPTSENT THREADACTIONTYPES = 12
	THREADACTIONTYPESSEARCHRESULTCLICK THREADACTIONTYPES = 13
	THREADACTIONTYPESSEARCHRESULTSHOWN THREADACTIONTYPES = 14
	THREADACTIONTYPESAIHOMEIMPRESSION THREADACTIONTYPES = 15
	THREADACTIONTYPESCLICKCONTINUECHATMODULE THREADACTIONTYPES = 16
)