type TOPBARATTRIBUTIONTYPE int

const (
	TOPBARATTRIBUTIONTYPEMUSIC TOPBARATTRIBUTIONTYPE = 0
	TOPBARATTRIBUTIONTYPECROSSPOSTING TOPBARATTRIBUTIONTYPE = 1
	TOPBARATTRIBUTIONTYPEMENTION TOPBARATTRIBUTIONTYPE = 2
	TOPBARATTRIBUTIONTYPERESHAREDSTATUS TOPBARATTRIBUTIONTYPE = 3
	TOPBARATTRIBUTIONTYPERESHAREDFROMMENTION TOPBARATTRIBUTIONTYPE = 4
	TOPBARATTRIBUTIONTYPECHANNEL TOPBARATTRIBUTIONTYPE = 5
	TOPBARATTRIBUTIONTYPEFB TOPBARATTRIBUTIONTYPE = 6
	TOPBARATTRIBUTIONTYPEIG TOPBARATTRIBUTIONTYPE = 7
	TOPBARATTRIBUTIONTYPESPOTIFY TOPBARATTRIBUTIONTYPE = 8
	TOPBARATTRIBUTIONTYPEE2EE TOPBARATTRIBUTIONTYPE = 9
	TOPBARATTRIBUTIONTYPERL TOPBARATTRIBUTIONTYPE = 10
	TOPBARATTRIBUTIONTYPEGROUPSTATUS TOPBARATTRIBUTIONTYPE = 11
	TOPBARATTRIBUTIONTYPESHARINGAPI TOPBARATTRIBUTIONTYPE = 12
	TOPBARATTRIBUTIONTYPEFORWARDSTATUS TOPBARATTRIBUTIONTYPE = 13
	TOPBARATTRIBUTIONTYPEAICREATED TOPBARATTRIBUTIONTYPE = 14
	TOPBARATTRIBUTIONTYPELAYOUTS TOPBARATTRIBUTIONTYPE = 15
	TOPBARATTRIBUTIONTYPECLOSESHARING TOPBARATTRIBUTIONTYPE = 16
	TOPBARATTRIBUTIONTYPECHANNELSTATUS TOPBARATTRIBUTIONTYPE = 17
	TOPBARATTRIBUTIONTYPERESHAREDFROMCHANNEL TOPBARATTRIBUTIONTYPE = 18
	TOPBARATTRIBUTIONTYPEUSERNAMESTATUS TOPBARATTRIBUTIONTYPE = 19
	TOPBARATTRIBUTIONTYPEAICONTENT TOPBARATTRIBUTIONTYPE = 20
)