type TRIGGERTYPE int

const (
	TRIGGERTYPECHATENTRY TRIGGERTYPE = 1
	TRIGGERTYPESYSTEMMESSAGE TRIGGERTYPE = 2
	TRIGGERTYPEKEEPMESSAGEFIRSTTIME TRIGGERTYPE = 3
	TRIGGERTYPEUSERMESSAGEKEPT TRIGGERTYPE = 4
	TRIGGERTYPEKEPTFOLDERTAPFIRSTTIME TRIGGERTYPE = 5
	TRIGGERTYPEUNKEEPMESSAGEFIRSTTIME TRIGGERTYPE = 6
	TRIGGERTYPEEPHEMERALSETTINGS TRIGGERTYPE = 7
)