type TRUSTSIGNALBUCKETS int

const (
	TRUSTSIGNALBUCKETSB0 TRUSTSIGNALBUCKETS = 1
	TRUSTSIGNALBUCKETSB1 TRUSTSIGNALBUCKETS = 2
	TRUSTSIGNALBUCKETSB2 TRUSTSIGNALBUCKETS = 3
	TRUSTSIGNALBUCKETSB11 TRUSTSIGNALBUCKETS = 4
	TRUSTSIGNALBUCKETSB51 TRUSTSIGNALBUCKETS = 5
	TRUSTSIGNALBUCKETSB101 TRUSTSIGNALBUCKETS = 6
	TRUSTSIGNALBUCKETSB501 TRUSTSIGNALBUCKETS = 7
	TRUSTSIGNALBUCKETSB1K TRUSTSIGNALBUCKETS = 8
	TRUSTSIGNALBUCKETSB10K TRUSTSIGNALBUCKETS = 9
	TRUSTSIGNALBUCKETSB100K TRUSTSIGNALBUCKETS = 10
	TRUSTSIGNALBUCKETSB1M TRUSTSIGNALBUCKETS = 11
)