type TSEXTERNALEVENTSOURCE int

const (
	TSEXTERNALEVENTSOURCECALL TSEXTERNALEVENTSOURCE = 1
	TSEXTERNALEVENTSOURCEVIDEO TSEXTERNALEVENTSOURCE = 2
	TSEXTERNALEVENTSOURCEPTTRECORD TSEXTERNALEVENTSOURCE = 3
	TSEXTERNALEVENTSOURCEPTTPLAY TSEXTERNALEVENTSOURCE = 4
	TSEXTERNALEVENTSOURCEMESSAGESENDBACKGROUND TSEXTERNALEVENTSOURCE = 5
)