type TYPE int

const (
	TYPENONE TYPE = 0
	TYPEOFFER TYPE = 1
	TYPEOFFERRECEIPT TYPE = 2
	TYPEACCEPT TYPE = 3
	TYPEREJECT TYPE = 4
	TYPETERMINATE TYPE = 5
	TYPETRANSPORT TYPE = 6
	TYPEOFFERACK TYPE = 7
	TYPEOFFERNACK TYPE = 8
	TYPERELAYLATENCY TYPE = 9
	TYPERELAYELECTION TYPE = 10
	TYPEINTERRUPTION TYPE = 11
	TYPEMUTE TYPE = 12
	TYPEPREACCEPT TYPE = 13
	TYPEACCEPTRECEIPT TYPE = 14
	TYPEVIDEOSTATE TYPE = 15
	TYPENOTIFY TYPE = 16
	TYPEGROUPINFO TYPE = 17
	TYPEENCREKEY TYPE = 18
	TYPEPEERSTATE TYPE = 19
	TYPEVIDEOSTATEACK TYPE = 20
	TYPEFLOWCONTROL TYPE = 21
	TYPEWEBCLIENT TYPE = 22
	TYPEACCEPTACK TYPE = 23
	TYPEGROUPUPDATE TYPE = 24
	TYPEOFFERNOTICE TYPE = 25
	TYPEMAX TYPE = 26
)