type UPLOADORIGINTYPE int

const (
	UPLOADORIGINTYPEUNKNOWN UPLOADORIGINTYPE = 1
	UPLOADORIGINTYPECHATPERSONAL UPLOADORIGINTYPE = 2
	UPLOADORIGINTYPECHATGROUP UPLOADORIGINTYPE = 3
	UPLOADORIGINTYPESTATUSUSER UPLOADORIGINTYPE = 4
	UPLOADORIGINTYPEPRODUCTCATALOG UPLOADORIGINTYPE = 5
	UPLOADORIGINTYPESTICKERWEB UPLOADORIGINTYPE = 6
	UPLOADORIGINTYPEPAYMENTSKYC UPLOADORIGINTYPE = 7
	UPLOADORIGINTYPEMESSAGEHISTORYSYNC UPLOADORIGINTYPE = 8
	UPLOADORIGINTYPECOMMUNITY UPLOADORIGINTYPE = 9
	UPLOADORIGINTYPECHANNEL UPLOADORIGINTYPE = 10
	UPLOADORIGINTYPEBROADCAST UPLOADORIGINTYPE = 11
	UPLOADORIGINTYPEMULTICHAT UPLOADORIGINTYPE = 12
	UPLOADORIGINTYPEINTEROP UPLOADORIGINTYPE = 13
	UPLOADORIGINTYPEWABACKUP UPLOADORIGINTYPE = 14
)