type UPLOADSOURCETYPE int

const (
	UPLOADSOURCETYPEOTHER UPLOADSOURCETYPE = 1
	UPLOADSOURCETYPECAMERA UPLOADSOURCETYPE = 2
	UPLOADSOURCETYPEGALLERY UPLOADSOURCETYPE = 3
	UPLOADSOURCETYPESHARE UPLOADSOURCETYPE = 4
)