type USERJOURNEYCHATTYPE int

const (
	USERJOURNEYCHATTYPEINDIVIDUAL USERJOURNEYCHATTYPE = 1
	USERJOURNEYCHATTYPEGROUP USERJOURNEYCHATTYPE = 2
	USERJOURNEYCHATTYPEBROADCAST USERJOURNEYCHATTYPE = 3
	USERJOURNEYCHATTYPESTATUS USERJOURNEYCHATTYPE = 4
	USERJOURNEYCHATTYPECHANNEL USERJOURNEYCHATTYPE = 5
	USERJOURNEYCHATTYPEINTEROP USERJOURNEYCHATTYPE = 6
	USERJOURNEYCHATTYPEMULTIPLE USERJOURNEYCHATTYPE = 7
	USERJOURNEYCHATTYPEFLOWS USERJOURNEYCHATTYPE = 8
	USERJOURNEYCHATTYPECATALOG USERJOURNEYCHATTYPE = 9
	USERJOURNEYCHATTYPEMETAAI USERJOURNEYCHATTYPE = 10
)