type USERNAMECREATIONFLOWTYPE int

const (
	USERNAMECREATIONFLOWTYPECREATION USERNAMECREATIONFLOWTYPE = 1
	USERNAMECREATIONFLOWTYPERESERVATION USERNAMECREATIONFLOWTYPE = 2
	USERNAMECREATIONFLOWTYPEACTIVATION USERNAMECREATIONFLOWTYPE = 3
	USERNAMECREATIONFLOWTYPEMANAGEMENT USERNAMECREATIONFLOWTYPE = 4
)