type VIDEOPLAYORIGIN int

const (
	VIDEOPLAYORIGINCONVERSATION VIDEOPLAYORIGIN = 1
	VIDEOPLAYORIGINGALLERYPICKER VIDEOPLAYORIGIN = 2
	VIDEOPLAYORIGINSTARREDMESSAGES VIDEOPLAYORIGIN = 3
	VIDEOPLAYORIGINMEDIAVIEWPAGER VIDEOPLAYORIGIN = 4
	VIDEOPLAYORIGINOTHERORIGIN VIDEOPLAYORIGIN = 5
	VIDEOPLAYORIGINCHANNELS VIDEOPLAYORIGIN = 6
	VIDEOPLAYORIGINSTATUS VIDEOPLAYORIGIN = 7
)