type VIEWERSHEETSTYLE string

const (
	VIEWERSHEETSTYLEPAGETRANSITION VIEWERSHEETSTYLE = "PAGE_TRANSITION"
	VIEWERSHEETSTYLEUSER VIEWERSHEETSTYLE = "USER"
	VIEWERSHEETSTYLEUSERTRANSITION VIEWERSHEETSTYLE = "USER_TRANSITION"
)