type VOSSACTION int

const (
	VOSSACTIONSENDERNUXTYPECIMPRESSION VOSSACTION = 1
	VOSSACTIONSENDERNUXTYPEDIMPRESSION VOSSACTION = 2
	VOSSACTIONSCREENSHOTSENDERNUXTYPEDIMPRESSION VOSSACTION = 3
	VOSSACTIONRECIPIENTOPENNUXTYPECIMPRESSION VOSSACTION = 4
	VOSSACTIONRECIPIENTOPENNUXTYPEDIMPRESSION VOSSACTION = 5
	VOSSACTIONSENDERNUXTYPECLEARNMORETAP VOSSACTION = 6
	VOSSACTIONSENDERNUXTYPEDLEARNMORETAP VOSSACTION = 7
	VOSSACTIONSCREENSHOTSENDERNUXTYPEDLEARNMORETAP VOSSACTION = 8
	VOSSACTIONRECIPIENTOPENNUXTYPECLEARNMORETAP VOSSACTION = 9
	VOSSACTIONRECIPIENTOPENNUXTYPEDLEARNMORETAP VOSSACTION = 10
	VOSSACTIONSCREENSHOTBLOCKED VOSSACTION = 11
	VOSSACTIONSCREENSHOTTAKEN VOSSACTION = 12
	VOSSACTIONSCREENRECORDINGBLOCKED VOSSACTION = 13
	VOSSACTIONSCREENRECORDINGSTARTED VOSSACTION = 14
	VOSSACTIONPLACEHOLDERMESSAGELEARNMORETAP VOSSACTION = 15
)