type WAADACCOUNTELIGIBILITY int

const (
	WAADACCOUNTELIGIBILITYWAONLY WAADACCOUNTELIGIBILITY = 1
	WAADACCOUNTELIGIBILITYFBONLY WAADACCOUNTELIGIBILITY = 2
	WAADACCOUNTELIGIBILITYFBORWA WAADACCOUNTELIGIBILITY = 3
)