type WEBDBNAMETYPE int

const (
	WEBDBNAMETYPEMODELSTORAGE WEBDBNAMETYPE = 1
	WEBDBNAMETYPEFTSSTORAGE WEBDBNAMETYPE = 2
	WEBDBNAMETYPEJOBSSTORAGE WEBDBNAMETYPE = 3
	WEBDBNAMETYPELOADGENSTORAGE WEBDBNAMETYPE = 4
	WEBDBNAMETYPELRUMEDIASTORAGEIDB WEBDBNAMETYPE = 5
	WEBDBNAMETYPEOFFDSTORAGE WEBDBNAMETYPE = 6
	WEBDBNAMETYPEQPLSTORAGE WEBDBNAMETYPE = 7
	WEBDBNAMETYPESIGNALSTORAGE WEBDBNAMETYPE = 8
	WEBDBNAMETYPEWORKERSTORAGE WEBDBNAMETYPE = 9
	WEBDBNAMETYPESW WEBDBNAMETYPE = 10
	WEBDBNAMETYPEWAWC WEBDBNAMETYPE = 11
	WEBDBNAMETYPEWAWCDBENC WEBDBNAMETYPE = 12
	WEBDBNAMETYPESTATUSSTORAGE WEBDBNAMETYPE = 13
)