type WEBCWEBPLATFORMTYPE int

const (
	WEBCWEBPLATFORMTYPEWEB WEBCWEBPLATFORMTYPE = 1
	WEBCWEBPLATFORMTYPEWIN32 WEBCWEBPLATFORMTYPE = 2
	WEBCWEBPLATFORMTYPEDARWIN WEBCWEBPLATFORMTYPE = 3
	WEBCWEBPLATFORMTYPEIOSTABLET WEBCWEBPLATFORMTYPE = 4
	WEBCWEBPLATFORMTYPEANDROIDTABLET WEBCWEBPLATFORMTYPE = 5
	WEBCWEBPLATFORMTYPEWINSTORE WEBCWEBPLATFORMTYPE = 6
	WEBCWEBPLATFORMTYPEMACSTORE WEBCWEBPLATFORMTYPE = 7
	WEBCWEBPLATFORMTYPEDARWINBETA WEBCWEBPLATFORMTYPE = 8
	WEBCWEBPLATFORMTYPEWIN32BETA WEBCWEBPLATFORMTYPE = 9
	WEBCWEBPLATFORMTYPEPWA WEBCWEBPLATFORMTYPE = 10
	WEBCWEBPLATFORMTYPEWINHYBRID WEBCWEBPLATFORMTYPE = 11
)