type WEBCAPPCACHESTATUSCODE int

const (
	WEBCAPPCACHESTATUSCODEUNCACHED WEBCAPPCACHESTATUSCODE = 0
	WEBCAPPCACHESTATUSCODEIDLE WEBCAPPCACHESTATUSCODE = 1
	WEBCAPPCACHESTATUSCODECHECKING WEBCAPPCACHESTATUSCODE = 2
	WEBCAPPCACHESTATUSCODEDOWNLOADING WEBCAPPCACHESTATUSCODE = 3
	WEBCAPPCACHESTATUSCODEUPDATEREADY WEBCAPPCACHESTATUSCODE = 4
	WEBCAPPCACHESTATUSCODEOBSOLETE WEBCAPPCACHESTATUSCODE = 5
)