type WEBCWHATSNEWSURFACETYPE int

const (
	WEBCWHATSNEWSURFACETYPELOADINGCAROUSEL WEBCWHATSNEWSURFACETYPE = 1
	WEBCWHATSNEWSURFACETYPEBANNER WEBCWHATSNEWSURFACETYPE = 2
	WEBCWHATSNEWSURFACETYPEMODAL WEBCWHATSNEWSURFACETYPE = 3
)