type WEBCASSETCACHETYPECODE int

const (
	WEBCASSETCACHETYPECODEUNCACHED WEBCASSETCACHETYPECODE = 0
	WEBCASSETCACHETYPECODEIDB WEBCASSETCACHETYPECODE = 1
	WEBCASSETCACHETYPECODESW WEBCASSETCACHETYPECODE = 2
)