type WEBCWHATSNEWACTIONTYPE int

const (
	WEBCWHATSNEWACTIONTYPEIMPRESSION WEBCWHATSNEWACTIONTYPE = 1
	WEBCWHATSNEWACTIONTYPEDISMISSBUTTON WEBCWHATSNEWACTIONTYPE = 2
	WEBCWHATSNEWACTIONTYPEDISMISSOVERLAY WEBCWHATSNEWACTIONTYPE = 3
	WEBCWHATSNEWACTIONTYPEBANNERCLICK WEBCWHATSNEWACTIONTYPE = 4
	WEBCWHATSNEWACTIONTYPEBANNERDISMISS WEBCWHATSNEWACTIONTYPE = 5
)