type WEBCQUICKACTIONSURFACE int

const (
	WEBCQUICKACTIONSURFACESTATUS WEBCQUICKACTIONSURFACE = 1
	WEBCQUICKACTIONSURFACECHANNELS WEBCQUICKACTIONSURFACE = 2
	WEBCQUICKACTIONSURFACECOMMUNITYNAVIGATION WEBCQUICKACTIONSURFACE = 3
	WEBCQUICKACTIONSURFACECHATS WEBCQUICKACTIONSURFACE = 4
	WEBCQUICKACTIONSURFACESETTINGSME WEBCQUICKACTIONSURFACE = 5
)