type WEBCBUTTERBARACTIONTYPE int

const (
	WEBCBUTTERBARACTIONTYPEIMPRESSION WEBCBUTTERBARACTIONTYPE = 1
	WEBCBUTTERBARACTIONTYPECLICKCTA WEBCBUTTERBARACTIONTYPE = 2
	WEBCBUTTERBARACTIONTYPECLICKDISMISS WEBCBUTTERBARACTIONTYPE = 3
	WEBCBUTTERBARACTIONTYPEAUTODISMISS WEBCBUTTERBARACTIONTYPE = 4
)