type WEBCRMRREASONCODE int

const (
	WEBCRMRREASONCODEOTHER WEBCRMRREASONCODE = 0
	WEBCRMRREASONCODEMSGCLICK WEBCRMRREASONCODE = 1
	WEBCRMRREASONCODESTICKERPANELICON WEBCRMRREASONCODE = 2
	WEBCRMRREASONCODEMEDIAVIEWER WEBCRMRREASONCODE = 3
	WEBCRMRREASONCODEVIDEOSTREAMING WEBCRMRREASONCODE = 4
	WEBCRMRREASONCODESTATUSV3 WEBCRMRREASONCODE = 5
	WEBCRMRREASONCODEMULTISELECTDOWNLOAD WEBCRMRREASONCODE = 6
	WEBCRMRREASONCODEDOCUMENTDOWNLOAD WEBCRMRREASONCODE = 7
	WEBCRMRREASONCODEPIP WEBCRMRREASONCODE = 8
	WEBCRMRREASONCODESTICKERPANELSTICKER WEBCRMRREASONCODE = 9
	WEBCRMRREASONCODESENDTOCHAT WEBCRMRREASONCODE = 10
	WEBCRMRREASONCODEUPLOAD WEBCRMRREASONCODE = 11
	WEBCRMRREASONCODEMSGINIT WEBCRMRREASONCODE = 12
	WEBCRMRREASONCODEMSGUPDATE WEBCRMRREASONCODE = 13
	WEBCRMRREASONCODEMSGDELETE WEBCRMRREASONCODE = 14
	WEBCRMRREASONCODEMSGRENDER WEBCRMRREASONCODE = 15
)