type WEBCSCENARIOTYPE int

const (
	WEBCSCENARIOTYPEINITIALPAIRING WEBCSCENARIOTYPE = 0
	WEBCSCENARIOTYPEOFFLINERESUME WEBCSCENARIOTYPE = 1
	WEBCSCENARIOTYPEIDLE WEBCSCENARIOTYPE = 2
	WEBCSCENARIOTYPERECENTHISTORYSYNC WEBCSCENARIOTYPE = 3
	WEBCSCENARIOTYPECHATNAVIGATION WEBCSCENARIOTYPE = 4
)