type WEBCNAVBARITEMLABEL int

const (
	WEBCNAVBARITEMLABELCHATS WEBCNAVBARITEMLABEL = 1
	WEBCNAVBARITEMLABELCOMMUNITIES WEBCNAVBARITEMLABEL = 2
	WEBCNAVBARITEMLABELNEWSLETTERS WEBCNAVBARITEMLABEL = 3
	WEBCNAVBARITEMLABELSTATUS WEBCNAVBARITEMLABEL = 4
	WEBCNAVBARITEMLABELSTARRED WEBCNAVBARITEMLABEL = 5
	WEBCNAVBARITEMLABELARCHIVED WEBCNAVBARITEMLABEL = 6
	WEBCNAVBARITEMLABELSETTINGSHELP WEBCNAVBARITEMLABEL = 7
	WEBCNAVBARITEMLABELSETTINGS WEBCNAVBARITEMLABEL = 8
	WEBCNAVBARITEMLABELPROFILE WEBCNAVBARITEMLABEL = 9
	WEBCNAVBARITEMLABELADSCREATION WEBCNAVBARITEMLABEL = 10
	WEBCNAVBARITEMLABELBUSINESSTOOLS WEBCNAVBARITEMLABEL = 11
	WEBCNAVBARITEMLABELUPDATES WEBCNAVBARITEMLABEL = 12
)