type WEBCMESSAGEQUERYDIRECTION int

const (
	WEBCMESSAGEQUERYDIRECTIONLOADPREV WEBCMESSAGEQUERYDIRECTION = 0
	WEBCMESSAGEQUERYDIRECTIONLOADNEXT WEBCMESSAGEQUERYDIRECTION = 1
	WEBCMESSAGEQUERYDIRECTIONLOADAROUND WEBCMESSAGEQUERYDIRECTION = 2
)