type WEBTPEVENTTYPE int

const (
	WEBTPEVENTTYPEOPEN WEBTPEVENTTYPE = 1
	WEBTPEVENTTYPECLOSE WEBTPEVENTTYPE = 2
	WEBTPEVENTTYPEDOWNLOADDOCUMENTCLICK WEBTPEVENTTYPE = 3
	WEBTPEVENTTYPEEDITMENUCLICK WEBTPEVENTTYPE = 4
	WEBTPEVENTTYPEERROR WEBTPEVENTTYPE = 5
	WEBTPEVENTTYPETELEMETRY WEBTPEVENTTYPE = 6
	WEBTPEVENTTYPEAPPPERFDATA WEBTPEVENTTYPE = 7
	WEBTPEVENTTYPEPDFSHAREROPEN WEBTPEVENTTYPE = 8
	WEBTPEVENTTYPEPDFSHARERCANCEL WEBTPEVENTTYPE = 9
	WEBTPEVENTTYPEPDFSHARERCONTINUE WEBTPEVENTTYPE = 10
	WEBTPEVENTTYPEPDFSHARERSUCCESS WEBTPEVENTTYPE = 11
	WEBTPEVENTTYPEPDFSHARERERROR WEBTPEVENTTYPE = 12
	WEBTPEVENTTYPEPDFSHARERUNSUPPORTED WEBTPEVENTTYPE = 13
	WEBTPEVENTTYPEPDFRECEIVEROPEN WEBTPEVENTTYPE = 14
	WEBTPEVENTTYPEPDFRECEIVERSUCCESS WEBTPEVENTTYPE = 15
	WEBTPEVENTTYPEPDFRECEIVERERROR WEBTPEVENTTYPE = 16
	WEBTPEVENTTYPEPDFRECEIVERCANCEL WEBTPEVENTTYPE = 17
	WEBTPEVENTTYPEPDFRECEIVERCONTINUE WEBTPEVENTTYPE = 18
	WEBTPEVENTTYPEPDFRECEIVERFILEFORWARDED WEBTPEVENTTYPE = 19
	WEBTPEVENTTYPEPDFSHARERAUTOPROCEEDCHECKBOX WEBTPEVENTTYPE = 20
	WEBTPEVENTTYPEPDFSHARERCONTINUEAUTOPROCEED WEBTPEVENTTYPE = 21
)