type WPBUJSOURCE int

const (
	WPBUJSOURCEAPPWIDE WPBUJSOURCE = 1
	WPBUJSOURCEONETOONE WPBUJSOURCE = 2
	WPBUJSOURCEGROUP WPBUJSOURCE = 3
	WPBUJSOURCELIST WPBUJSOURCE = 4
	WPBUJSOURCESETTINGSBACKUPPROVIDERROW WPBUJSOURCE = 5
	WPBUJSOURCESETTINGSFINISHBACKUPSETUPBANNER WPBUJSOURCE = 6
	WPBUJSOURCESETTINGSFIXENCRYPTIONBANNER WPBUJSOURCE = 7
	WPBUJSOURCESETTINGSENABLECLOUDBACKUPSBANNER WPBUJSOURCE = 8
	WPBUJSOURCECHATLISTFIXENCRYPTIONBANNER WPBUJSOURCE = 9
	WPBUJSOURCEREGISTRATIONRESTORESETUP WPBUJSOURCE = 10
	WPBUJSOURCECHATLISTBACKUPSETUPPROMPT WPBUJSOURCE = 11
)