type WSUAACTIONTARGET int

const (
	WSUAACTIONTARGETOKBUTTON WSUAACTIONTARGET = 1
	WSUAACTIONTARGETNOTNOWBUTTON WSUAACTIONTARGET = 2
	WSUAACTIONTARGETJOINWAITLISTDEEPLINK WSUAACTIONTARGET = 3
	WSUAACTIONTARGETJOINWAITLISTBUTTON WSUAACTIONTARGET = 4
	WSUAACTIONTARGETLEAVEWAITLISTBUTTON WSUAACTIONTARGET = 5
	WSUAACTIONTARGETUNDOBUTTON WSUAACTIONTARGET = 6
	WSUAACTIONTARGETSUBSCRIPTIONSENTRYPOINTLISTITEM WSUAACTIONTARGET = 7
	WSUAACTIONTARGETAPPICON WSUAACTIONTARGET = 8
	WSUAACTIONTARGETAPPTHEME WSUAACTIONTARGET = 9
	WSUAACTIONTARGETEXPLOREBENEFITS WSUAACTIONTARGET = 10
	WSUAACTIONTARGETGETWHATSAPPPLUSBUTTON WSUAACTIONTARGET = 11
	WSUAACTIONTARGETEXPLOREBENEFITSBUTTON WSUAACTIONTARGET = 12
	WSUAACTIONTARGETCALLRINGTONELISTITEM WSUAACTIONTARGET = 13
	WSUAACTIONTARGETVIEWSTICKERPACK WSUAACTIONTARGET = 14
	WSUAACTIONTARGETCHATPIN WSUAACTIONTARGET = 15
	WSUAACTIONTARGETUPSELLCTA WSUAACTIONTARGET = 16
	WSUAACTIONTARGETMANAGEBUTTON WSUAACTIONTARGET = 17
	WSUAACTIONTARGETLEARNMORE WSUAACTIONTARGET = 18
	WSUAACTIONTARGETDISMISSBUTTON WSUAACTIONTARGET = 19
	WSUAACTIONTARGETSUBSCRIPTIONSENTRYPOINT WSUAACTIONTARGET = 20
	WSUAACTIONTARGETCONTINUEBUTTON WSUAACTIONTARGET = 21
	WSUAACTIONTARGETWHATSAPPPLUS WSUAACTIONTARGET = 22
	WSUAACTIONTARGETMETAAI WSUAACTIONTARGET = 23
	WSUAACTIONTARGETLISTTHEME WSUAACTIONTARGET = 24
	WSUAACTIONTARGETLISTALERTTONE WSUAACTIONTARGET = 25
	WSUAACTIONTARGETLISTRINGTONE WSUAACTIONTARGET = 26
	WSUAACTIONTARGETQUICKPROMOTIONDEEPLINK WSUAACTIONTARGET = 27
	WSUAACTIONTARGETADDFULLNAMEBUTTON WSUAACTIONTARGET = 28
	WSUAACTIONTARGETPREMIUMSTICKERPACK WSUAACTIONTARGET = 29
	WSUAACTIONTARGETPREMIUMSTICKER WSUAACTIONTARGET = 30
	WSUAACTIONTARGETMETAONECONSUMER WSUAACTIONTARGET = 31
	WSUAACTIONTARGETGETMOREWITHONESUB WSUAACTIONTARGET = 32
	WSUAACTIONTARGETGETMOREFORLESS WSUAACTIONTARGET = 33
	WSUAACTIONTARGETVIEWALLPLANS WSUAACTIONTARGET = 34
	WSUAACTIONTARGETVIEWALLBENEFITS WSUAACTIONTARGET = 35
	WSUAACTIONTARGETVIEWALLBENEFITSBUTTON WSUAACTIONTARGET = 36
	WSUAACTIONTARGETUPSELLCARD WSUAACTIONTARGET = 37
	WSUAACTIONTARGETMETAONEBUSINESSENTRYPOINT WSUAACTIONTARGET = 38
	WSUAACTIONTARGETGETMETAONEBUSINESS WSUAACTIONTARGET = 39
)