message ValidatedResult {
  optional bytes validatedMimeType = 1;
  optional bytes videoStreamType = 2;
  optional bytes videoCalculatedFps = 3;
  optional bytes videoNominalFps = 4;
  optional bytes videoWidth = 5;
  optional bytes videoHeight = 6;
  optional bytes videoDuration = 7;
  optional bytes videoAvgBitsPerSecond = 8;
  optional bytes audioStreamType = 9;
  optional bytes audioSamplingRate = 10;
  optional bytes audioNumberOfChannels = 11;
  optional bytes audioAvgBitsPerSecond = 12;
}