message UnrenderedMessagesTableSchemaProto {
  optional bytes type = 1;
  optional bytes ts = 2;
  optional bytes externalId = 3;
  optional bytes msgId = 4;
  optional bytes author = 5;
  optional bytes ack = 6;
  optional bytes resendCount = 7;
  optional bytes ephemeralSetting = 8;
  optional bytes messageDeleteForMeTs = 9;
  optional bytes rowId = 10;
  optional bytes thread = 11;
  optional bytes mediaId = 12;
  optional bytes msgContent = 13;
  optional bytes threadJid = 14;
  optional bytes reportingMeta = 15;
  optional bytes invitedParticipantUserJid = 16;
  optional bytes groupName = 17;
  optional bytes quote = 18;
  optional bytes xmaMessageType = 19;
  optional bytes sortOrderMs = 20;
}