message MessagesTableSchemaProto {
  optional bytes type = 1;
  optional bytes ts = 2;
  optional bytes externalId = 3;
  optional bytes msgId = 4;
  optional bytes author = 5;
  optional bytes ack = 6;
  optional bytes resendCount = 7;
  optional MsgContentProto msgContent = 8;
  optional bytes altIndex = 9;
  optional bytes forwardingScore = 10;
  optional DbQuotedMsgProto quote = 11;
  optional bytes messageExpirationTs = 12;
  optional bytes ephemeralSetting = 13;
  optional bytes revokedExternalId = 14;
  optional bytes isForwarded = 15;
  optional bytes originalTs = 17;
  optional bytes sortOrderMs = 18;
  optional ReportingMetaProto reportingMeta = 19;
  optional bytes messageDeleteTs = 20;
  optional bytes ephemeralCounterStarted = 21;
  optional bytes quoteExternalId = 22;
  optional bytes unsendMsgContentDeleteTs = 23;
  optional bytes rowId = 24;
  optional bytes thread = 25;
  optional bytes mediaId = 26;
  optional bytes ephemeralMsgDisappeared = 27;
  optional bytes threadJid = 28;
  optional bytes xmaId = 29;
  optional bytes specialTextSize = 30;
  optional bytes xmaMessageType = 31;
  optional bytes isExpiredXmaMsg = 32;
  optional bytes ravenEphemeralType = 33;
  optional bytes ravenEphemeralMediaState = 34;
  optional bytes editCount = 35;
  optional bytes groupId = 36;
  optional bytes groupIndex = 37;
  optional bytes groupSize = 38;
  optional bytes receiverFetchId = 39;
  optional bytes source = 40;
  optional bytes quoteExpirationTs = 41;
  optional bytes applicationErrorCode = 42;
  optional bytes hdType = 43;
  optional bytes pollStanzaId = 44;
  optional bytes collapsibleId = 45;
  optional bytes isCollapsed = 46;
}