message MediaTableSchemaProto {
  optional bytes mediaType = 1;
  optional bytes plaintextHash = 2;
  optional bytes size = 3;
  optional MediaEntriesProto mediaEntries = 4;
  optional bytes ts = 5;
  optional VideoMsgContentProto validatedVideoInfo = 6;
  optional ImageMsgContentProto validatedImageInfo = 7;
  optional AudioMsgContentProto validatedAudioInfo = 8;
  optional bytes hashedPlaintextHash = 9;
  optional bytes mediaId = 10;
  optional bytes msgIds = 11;
  optional bytes objectId = 12;
  optional bytes fbid = 13;
  optional DocumentFileMsgContentProto validatedDocumentFileInfo = 14;
  optional ValidatedResult validatedResult = 15;
  optional bytes accessibilitySummaryText = 16;
  optional bytes isVideoGif = 17;
}