message XMATableSchemaProto {
  optional bytes associatedMessageId = 1;
  optional bytes author = 2;
  optional CTAProto ctas = 3;
  optional CTAProto defaultCTA = 4;
  optional bytes defaultPreviewMediaId = 5;
  optional bytes externalId = 6;
  optional bytes faviconMediaId = 7;
  optional bytes headerMediaId = 8;
  optional bytes headerTitle = 9;
  optional bytes isTombstoned = 10;
  optional bytes maxSubtitleNumOfLines = 11;
  optional bytes maxTitleNumOfLines = 12;
  optional bytes msgId = 13;
  optional bytes overlayDescription = 14;
  optional bytes overlayIconGlyph = 15;
  optional bytes overlayTitle = 16;
  optional bytes previewMediaIds = 17;
  optional bytes subtitleText = 18;
  optional bytes targetExpiringAtSec = 19;
  optional bytes targetId = 20;
  optional bytes targetType = 21;
  optional bytes targetUsername = 22;
  optional bytes threadJid = 23;
  optional bytes titleText = 24;
  optional bytes xmaId = 25;
  optional bytes xmaLayoutType = 26;
  optional bytes defaultPreviewMediaPlaintextHash = 27;
  optional bytes faviconPlaintextHash = 28;
  optional bytes headerMediaPlaintextHash = 29;
}