message MiTransportAdminMessage {
  optional ChatThemeChanged chatThemeChanged = 1;
  optional NicknameChanged nicknameChanged = 2;
  optional GroupParticipantChanged groupParticipantChanged = 3;
  optional GroupAdminChanged groupAdminChanged = 4;
  optional GroupNameChanged groupNameChanged = 5;
  optional GroupMembershipAddModeChanged groupMembershipAddModeChanged = 6;
  optional MessagePinned messagePinned = 7;
  optional GroupImageChanged groupImageChanged = 8;
  optional QuickReactionChanged quickReactionChanged = 9;
  optional LinkCta linkCta = 10;
  optional IconChanged iconChanged = 11;
  optional DisappearingSettingChanged disappearingSettingChanged = 12;
  optional LimitSharingChanged limitSharingChanged = 13;
  optional XmatDisappearingSetting xmatDisappearingSetting = 14;
  optional XmatFriendRequestConfirmedEncrypted xmatFriendRequestConfirmedEncrypted = 15;
  optional XmatInstantGameEncryptedDynamicCustomUpdate xmatInstantGameEncryptedDynamicCustomUpdate = 16;
  optional XmatLinkCTA xmatLinkCta = 17;
  optional XmatMagicWords xmatMagicWords = 18;
  optional XmatMessagingLimitSharing xmatMessagingLimitSharing = 19;
  optional XmatMessengerQRCodeScanned xmatMessengerQrCodeScanned = 20;
  optional XmatMessengerSharedAlbumAddition xmatMessengerSharedAlbumAddition = 21;
  optional XmatMessengerSharedAlbumContentRemoval xmatMessengerSharedAlbumContentRemoval = 22;
  optional XmatMessengerSharedAlbumDeletion xmatMessengerSharedAlbumDeletion = 23;
  optional XmatMessengerSharedAlbumRename xmatMessengerSharedAlbumRename = 24;
  optional XmatMessengerSharedAlbum xmatMessengerSharedAlbum = 25;
  optional XmatThemeColor xmatThemeColor = 26;
  optional XmatThreadIcon xmatThreadIcon = 27;
  optional XmatThreadNickname xmatThreadNickname = 28;
  optional XmatThreadQuickReaction xmatThreadQuickReaction = 29;
  optional XmatUpdatePayments xmatUpdatePayments = 30;
  optional XmatPinMessageV2 xmatPinMessageV2 = 31;
  optional XmatUnpinMessageV2 xmatUnpinMessageV2 = 32;
  optional XmatGenAITaskAdd xmatGenaiTaskAdd = 33;
  optional bytes skipBumpThread = 34;
  optional bytes skipSnippetUpdate = 35;
  optional bytes readonlyMetadataDataclass = 36;
  optional XmatAddParticipants xmatAddParticipants = 37;
  optional XmatRemoveParticipant xmatRemoveParticipant = 38;
  optional XmatChangeThreadAdmins xmatChangeThreadAdmins = 39;
  optional XmatChangeThreadName xmatChangeThreadName = 40;
  optional XmatGroupThreadCreated xmatGroupThreadCreated = 41;
  optional XmatSetParticipantUpdateMode xmatSetParticipantUpdateMode = 42;
  optional XmatMessengerMessageReminderSet xmatMessengerMessageReminderSet = 43;
  optional XmatMessengerMessageReminderTriggered xmatMessengerMessageReminderTriggered = 44;
}