message Content {
  optional CommonSticker commonSticker = 1;
  optional ScreenshotAction screenshotAction = 3;
  optional bytes extendedContentMessage = 4;
  optional RavenMessage ravenMessage = 5;
  optional RavenActionNotifMessage ravenActionNotifMessage = 6;
  optional ExtendedContentMessageWithSear extendedMessageContentWithSear = 7;
  optional ImageGalleryMessage imageGalleryMessage = 8;
  optional PaymentsTransactionMessage paymentsTransactionMessage = 10;
  optional BumpExistingMessage bumpExistingMessage = 11;
  optional NoteReplyMessage noteReplyMessage = 13;
  optional RavenMessage ravenMessageMsgr = 14;
  optional NetworkVerificationMessage networkVerificationMessage = 15;
}