message ExtendedContentMessage {
  optional bytes associatedMessage = 1;
  optional bytes targetType = 2;
  optional bytes targetUsername = 3;
  optional bytes targetId = 4;
  optional bytes targetExpiringAtSec = 5;
  optional bytes xmaLayoutType = 6;
  optional CTA ctas = 7;
  optional bytes previews = 8;
  optional bytes titleText = 9;
  optional bytes subtitleText = 10;
  optional bytes maxTitleNumOfLines = 11;
  optional bytes maxSubtitleNumOfLines = 12;
  optional bytes favicon = 13;
  optional bytes headerImage = 14;
  optional bytes headerTitle = 15;
  optional bytes overlayIconGlyph = 16;
  optional bytes overlayTitle = 17;
  optional bytes overlayDescription = 18;
  optional bytes sentWithMessageId = 19;
  optional bytes messageText = 20;
  optional bytes headerSubtitle = 21;
  optional bytes xmaDataclass = 22;
  optional bytes contentRef = 23;
  optional bytes mentionedJid = 24;
  optional bytes commands = 25;
  optional bytes mentions = 26;
  optional bytes xmaDataclassType = 27;
  optional bytes signedXmaDataclassValidation = 28;
  optional bytes featureSharedSessionId = 29;
}