message Content {
  optional bytes messageText = 1;
  optional ImageMessage imageMessage = 2;
  optional ContactMessage contactMessage = 3;
  optional LocationMessage locationMessage = 4;
  optional ExtendedTextMessage extendedTextMessage = 5;
  optional StatusTextMesage statusTextMessage = 6;
  optional DocumentMessage documentMessage = 7;
  optional AudioMessage audioMessage = 8;
  optional VideoMessage videoMessage = 9;
  optional ContactsArrayMessage contactsArrayMessage = 10;
  optional LiveLocationMessage liveLocationMessage = 11;
  optional StickerMessage stickerMessage = 12;
  optional GroupInviteMessage groupInviteMessage = 13;
  optional ViewOnceMessage viewOnceMessage = 14;
  optional ReactionMessage reactionMessage = 16;
  optional PollCreationMessage pollCreationMessage = 17;
  optional PollUpdateMessage pollUpdateMessage = 18;
  optional EditMessage editMessage = 19;
}