message ContextInfo {
  optional bytes stanzaId = 1;
  optional bytes participant = 2;
  optional Message quotedMessage = 3;
  optional bytes remoteJid = 4;
  optional bytes mentionedJid = 15;
  optional bytes conversionSource = 18;
  optional bytes conversionData = 19;
  optional bytes conversionDelaySeconds = 20;
  optional bytes forwardingScore = 21;
  optional bytes isForwarded = 22;
  optional AdReplyInfo quotedAd = 23;
  optional bytes placeholderKey = 24;
  optional bytes expiration = 25;
  optional bytes ephemeralSettingTimestamp = 26;
  optional bytes ephemeralSharedSecret = 27;
  optional ExternalAdReplyInfo externalAdReply = 28;
  optional bytes entryPointConversionSource = 29;
  optional bytes entryPointConversionApp = 30;
  optional bytes entryPointConversionDelaySeconds = 31;
  optional DisappearingMode disappearingMode = 32;
  optional ActionLink actionLink = 33;
  optional bytes groupSubject = 34;
  optional bytes parentGroupJid = 35;
  optional bytes trustBannerType = 37;
  optional bytes trustBannerAction = 38;
  optional bytes isSampled = 39;
  optional GroupMention groupMentions = 40;
  optional UTMInfo utm = 41;
  optional ForwardedNewsletterMessageInfo forwardedNewsletterMessageInfo = 43;
  optional BusinessMessageForwardInfo businessMessageForwardInfo = 44;
  optional bytes smbClientCampaignId = 45;
  optional bytes smbServerCampaignId = 46;
  optional DataSharingContext dataSharingContext = 47;
  optional bytes alwaysShowAdAttribution = 48;
  optional FeatureEligibilities featureEligibilities = 49;
  optional bytes entryPointConversionExternalSource = 50;
  optional bytes entryPointConversionExternalMedium = 51;
  optional bytes ctwaSignals = 54;
  optional bytes ctwaPayload = 55;
  optional bytes forwardedAiBotMessageInfo = 56;
  optional bytes statusAttributionType = 57;
  optional UrlTrackingMap urlTrackingMap = 58;
  optional bytes pairedMediaType = 59;
  optional bytes rankingVersion = 60;
  optional MemberLabel memberLabel = 62;
  optional bytes isQuestion = 63;
  optional bytes statusSourceType = 64;
  optional bytes statusAttributions = 65;
  optional bytes isGroupStatus = 66;
  optional bytes forwardOrigin = 67;
  optional QuestionReplyQuotedMessage questionReplyQuotedMessage = 68;
  optional StatusAudienceMetadata statusAudienceMetadata = 69;
  optional bytes nonJidMentions = 70;
  optional bytes quotedType = 71;
  optional bytes botMessageSharingInfo = 72;
  optional bytes isSpoiler = 73;
  optional MediaDomainInfo mediaDomainInfo = 74;
  optional PartiallySelectedContent partiallySelectedContent = 75;
  optional bytes afterReadDuration = 76;
}