message ExternalAdReplyInfo {
  optional bytes title = 1;
  optional bytes body = 2;
  optional bytes mediaType = 3;
  optional bytes thumbnailUrl = 4;
  optional bytes mediaUrl = 5;
  optional bytes thumbnail = 6;
  optional bytes sourceType = 7;
  optional bytes sourceId = 8;
  optional bytes sourceUrl = 9;
  optional bytes containsAutoReply = 10;
  optional bytes renderLargerThumbnail = 11;
  optional bytes showAdAttribution = 12;
  optional bytes ctwaClid = 13;
  optional bytes ref = 14;
  optional bytes clickToWhatsappCall = 15;
  optional bytes adContextPreviewDismissed = 16;
  optional bytes sourceApp = 17;
  optional bytes automatedGreetingMessageShown = 18;
  optional bytes greetingMessageBody = 19;
  optional bytes ctaPayload = 20;
  optional bytes disableNudge = 21;
  optional bytes originalImageUrl = 22;
  optional bytes automatedGreetingMessageCtaType = 23;
  optional bytes wtwaAdFormat = 24;
  optional bytes adType = 25;
  optional bytes wtwaWebsiteUrl = 26;
  optional bytes adPreviewUrl = 27;
  optional bytes containsCtwaFlowsAutoReply = 28;
  optional bytes agmThumbnailStrategy = 29;
  optional bytes agmTitleStrategy = 30;
  optional bytes agmSubtitleStrategy = 31;
  optional bytes agmHeaderInteractionStrategy = 32;
}