message BotMetadata {
  optional bytes personaId = 2;
  optional BotPluginMetadata pluginMetadata = 3;
  optional BotSuggestedPromptMetadata suggestedPromptMetadata = 4;
  optional bytes invokerJid = 5;
  optional BotSessionMetadata sessionMetadata = 6;
  optional BotMemuMetadata memuMetadata = 7;
  optional bytes timezone = 8;
  optional BotReminderMetadata reminderMetadata = 9;
  optional BotModelMetadata modelMetadata = 10;
  optional bytes messageDisclaimerText = 11;
  optional BotProgressIndicatorMetadata progressIndicatorMetadata = 12;
  optional BotCapabilityMetadata capabilityMetadata = 13;
  optional BotImagineMetadata imagineMetadata = 14;
  optional BotMemoryMetadata memoryMetadata = 15;
  optional BotRenderingMetadata renderingMetadata = 16;
  optional BotMetricsMetadata botMetricsMetadata = 17;
  optional BotLinkedAccountsMetadata botLinkedAccountsMetadata = 18;
  optional BotSourcesMetadata richResponseSourcesMetadata = 19;
  optional bytes aiConversationContext = 20;
  optional BotPromotionMessageMetadata botPromotionMessageMetadata = 21;
  optional BotModeSelectionMetadata botModeSelectionMetadata = 22;
  optional BotQuotaMetadata botQuotaMetadata = 23;
  optional BotAgeCollectionMetadata botAgeCollectionMetadata = 24;
  optional bytes conversationStarterPromptId = 25;
  optional bytes botResponseId = 26;
  optional BotSignatureVerificationMetadata verificationMetadata = 27;
  optional BotUnifiedResponseMutation unifiedResponseMutation = 28;
  optional BotMessageOriginMetadata botMessageOriginMetadata = 29;
  optional InThreadSurveyMetadata inThreadSurveyMetadata = 30;
  optional AIThreadInfo botThreadInfo = 31;
  optional AIRegenerateMetadata regenerateMetadata = 32;
  optional SessionTransparencyMetadata sessionTransparencyMetadata = 33;
  optional BotDocumentMessageMetadata botDocumentMessageMetadata = 34;
  optional BotGroupMetadata botGroupMetadata = 35;
  optional BotRenderingConfigMetadata botRenderingConfigMetadata = 36;
  optional BotInfrastructureDiagnostics botInfrastructureDiagnostics = 37;
  optional AIMediaCollectionMetadata aiMediaCollectionMetadata = 38;
  optional BotCommandMetadata commandMetadata = 39;
  optional BotResolvedToolCallMetadata resolvedToolCallMetadata = 40;
  optional AISubscriptionUpsellMetadata subscriptionUpsellMetadata = 41;
  optional BotPttPromptMetadata pttPromptMetadata = 42;
  optional BotHistoryShareMetadata botHistoryShareMetadata = 43;
  optional bytes internalMetadata = 999;
}