message MsgOpaqueData {
  optional bytes body = 1;
  optional bytes caption = 3;
  optional bytes lng = 5;
  optional bytes isLive = 6;
  optional bytes lat = 7;
  optional bytes paymentAmount1000 = 8;
  optional bytes paymentNoteMsgBody = 9;
  optional bytes matchedText = 11;
  optional bytes title = 12;
  optional bytes description = 13;
  optional bytes futureproofBuffer = 14;
  optional bytes clientUrl = 15;
  optional bytes loc = 16;
  optional bytes pollName = 17;
  optional PollOption pollOptions = 18;
  optional bytes pollSelectableOptionsCount = 20;
  optional bytes messageSecret = 21;
  optional bytes senderTimestampMs = 22;
  optional bytes pollUpdateParentKey = 23;
  optional PollEncValue encPollVote = 24;
  optional bytes encReactionTargetMessageKey = 25;
  optional bytes encReactionEncPayload = 26;
  optional bytes encReactionEncIv = 27;
  optional bytes isSentCagPollCreation = 28;
  optional bytes botMessageSecret = 29;
  optional bytes targetMessageKey = 30;
  optional bytes encPayload = 31;
  optional bytes encIv = 32;
  optional bytes eventName = 33;
  optional bytes isEventCanceled = 34;
  optional bytes eventDescription = 35;
  optional bytes eventJoinLink = 36;
  optional bytes eventStartTime = 37;
  optional EventLocation eventLocation = 38;
  optional bytes eventEndTime = 40;
  optional PollVotesSnapshot pollVotesSnapshot = 41;
  optional bytes pollContentType = 42;
  optional bytes plainProtobufBytes = 43;
  optional bytes eventIsScheduledCall = 44;
  optional bytes eventExtraGuestsAllowed = 45;
  optional bytes pollType = 46;
  optional bytes correctOptionIndex = 47;
  optional bytes quarantineExtractedText = 48;
  optional bytes pollEndTime = 49;
  optional bytes pollHideVoterNames = 50;
  optional bytes originalSelfAuthor = 51;
  optional bytes pollAllowAddOption = 52;
  optional bytes sharableEventInviteId = 53;
  optional bytes sharableEventInviteTitle = 54;
  optional bytes sharableEventInviteStartTime = 55;
  optional bytes sharableEventInviteEndTime = 56;
  optional bytes sharableEventInviteCaption = 57;
  optional bytes sharableEventInviteIsCanceled = 58;
  optional bytes sharableEventInviteJpegThumbnail = 59;
  optional bytes sharableEventInviteCallLink = 60;
}