message VideoMessage {
  optional bytes url = 1;
  optional bytes mimetype = 2;
  optional bytes fileSha256 = 3;
  optional bytes fileLength = 4;
  optional bytes seconds = 5;
  optional bytes mediaKey = 6;
  optional bytes caption = 7;
  optional bytes gifPlayback = 8;
  optional bytes height = 9;
  optional bytes width = 10;
  optional bytes fileEncSha256 = 11;
  optional InteractiveAnnotation interactiveAnnotations = 12;
  optional bytes directPath = 13;
  optional bytes mediaKeyTimestamp = 14;
  optional bytes jpegThumbnail = 16;
  optional ContextInfo contextInfo = 17;
  optional bytes streamingSidecar = 18;
  optional bytes gifAttribution = 19;
  optional bytes viewOnce = 20;
  optional bytes thumbnailDirectPath = 21;
  optional bytes thumbnailSha256 = 22;
  optional bytes thumbnailEncSha256 = 23;
  optional bytes staticUrl = 24;
  optional InteractiveAnnotation annotations = 25;
  optional bytes accessibilityLabel = 26;
  optional ProcessedVideo processedVideos = 27;
  optional bytes externalShareFullVideoDurationInSeconds = 28;
  optional bytes motionPhotoPresentationOffsetMs = 29;
  optional bytes metadataUrl = 30;
  optional bytes videoSourceType = 31;
}