message GlobalSettings {
  optional WallpaperSettings lightThemeWallpaper = 1;
  optional bytes mediaVisibility = 2;
  optional WallpaperSettings darkThemeWallpaper = 3;
  optional AutoDownloadSettings autoDownloadWiFi = 4;
  optional AutoDownloadSettings autoDownloadCellular = 5;
  optional AutoDownloadSettings autoDownloadRoaming = 6;
  optional bytes showIndividualNotificationsPreview = 7;
  optional bytes showGroupNotificationsPreview = 8;
  optional bytes disappearingModeDuration = 9;
  optional bytes disappearingModeTimestamp = 10;
  optional AvatarUserSettings avatarUserSettings = 11;
  optional bytes fontSize = 12;
  optional bytes securityNotifications = 13;
  optional bytes autoUnarchiveChats = 14;
  optional bytes videoQualityMode = 15;
  optional bytes photoQualityMode = 16;
  optional NotificationSettings individualNotificationSettings = 17;
  optional NotificationSettings groupNotificationSettings = 18;
  optional bytes chatLockSettings = 19;
  optional bytes chatDbLidMigrationTimestamp = 20;
}