message CallLogRecord {
  optional bytes callResult = 1;
  optional bytes isDndMode = 2;
  optional bytes silenceReason = 3;
  optional bytes duration = 4;
  optional bytes startTime = 5;
  optional bytes isIncoming = 6;
  optional bytes isVideo = 7;
  optional bytes isCallLink = 8;
  optional bytes callLinkToken = 9;
  optional bytes scheduledCallId = 10;
  optional bytes callId = 11;
  optional bytes callCreatorJid = 12;
  optional bytes groupJid = 13;
  optional ParticipantInfo participants = 14;
  optional bytes callType = 15;
}