export enum BOOTSTRAPAPPSTATEDATASTAGECODE {
  REQUEST_BUILT = 1,
  RESPONSE_RECEIVED = 2,
  RESPONSE_PARSED_VALID = 3,
  MISSING_KEYS_REQUESTED = 4,
  MISSING_KEYS_RECEIVED = 5,
  MUTATIONS_DECRYPTED = 6,
  ABOUT_TO_APPLY_MUTATIONS = 7,
  APPLIED_MUTATIONS = 8,
  PUSHNAME_APPLIED = 9,
  PUSHNAME_INVALID = 10,
  ENTERED_RETRY_MODE = 11,
}