export enum CHANNELDIRECTORYENTRYPOINT {
  SUGGESTED_CHANNELS = 1,
  FIND_CHANNELS_MENU = 2,
  DEEP_LINK = 3,
  WAITLIST_NOTIFICATION = 4,
  NUX_BANNER = 5,
  FIND_CHANNELS_BUTTON = 6,
  UPDATES_TAB_SEARCH = 7,
  EXPLORE_SECTION_HEADER_BUTTON = 8,
  UPDATES_TAB_SEARCH_NULL_STATE = 9,
}