export enum CLIENTMESSAGESENDSTAGE {
  CLIENT_RENDERED = 1,
  CLIENT_SAVED = 2,
  CLIENT_WRITTEN_WIRE = 3,
  CLIENT_QUEUED = 4,
  CLIENT_WAITING_TO_ENCRYPT = 5,
  CLIENT_READY_TO_SEND = 6,
  CLIENT_ENCRYPT = 7,
  CLIENT_PREKEYS_FETCH = 8,
}