export enum COMPANIONINVITEORIGINTYPE {
  UNKNOWN = 0,
  CHATLIST_SEARCH = 1,
  CONTACT_PICKER_LIST = 2,
  CONTACT_PICKER_SEARCH = 3,
  GROUPS_CREATE_PARTICIPANT_SELECTOR = 4,
  GROUPS_ADD_PARTICIPANT_SELECTOR = 5,
  CONTACT_EDIT_DRAWER = 6,
}