export enum CONNECTIONSEQUENCESTEPTYPE {
  PUSH_OVERRIDES = 1,
  PRIMARY = 2,
  PUSH_FALLBACKS = 4,
  HOST_FALLBACK = 5,
  NO_DNS = 6,
  SOFTLAYER = 7,
  PRIMARY_HTTP = 8,
  SOFTLAYER_HTTP = 9,
  HOST_FALLBACK_HTTP = 10,
  NO_DNS_HTTP = 11,
}