export enum CONSUMERBIZACTIONTARGETENUM {
  SEARCH_RESULT_ITEM = 0,
  PROFILE_BUTTON = 1,
  SHARE_BUTTON = 2,
  BACK_BUTTON = 3,
  CONTACT_CARD = 4,
  HEADER_SUBTITLE = 5,
  FMX_AFFILIATION_ROW = 6,
  AFFILIATION_SECTION = 7,
  CONTACT_BIZ_CTA = 8,
  BOTTOM_SHEET_OK = 9,
  BLOCKED_COMPOSER_LEARN_MORE = 10,
  BLOCKED_COMPOSER = 11,
}