export enum CONSUMERBIZSURFACEENUM {
  SEARCH_RESULTS = 0,
  BUSINESS_PROFILE = 1,
  CONTACT_CARD = 2,
  SHARE_DIALOG = 3,
  CHAT_HEADER = 4,
  FMX_CARD = 5,
  BLOCKED_COMPOSER = 6,
  OFFBOARDED_BOTTOM_SHEET = 7,
  CHAT_THREAD = 8,
}