export enum DEVICEJIDBROADCASTJIDDEVICEJIDGROUPJIDINTEROPDEVICEJIDINTEROPDEVICEJIDDEVICEJIDSTATUSJID {
  TYPE_NAME = "DeviceJid|BroadcastJid|DeviceJid|GroupJid|InteropDeviceJid|InteropDeviceJid|DeviceJid|StatusJid",
}