export enum DISAPPEARINGMODEENTRYPOINTTYPE {
  ACCOUNT_SETTINGS = 1,
  SYSTEM_MESSAGE = 2,
  INDIVIDUAL_CHAT_DISAPPEARING_MESSAGES_SETTING = 3,
  GROUP_CHAT_DISAPPEARING_MESSAGES_SETTING = 4,
  DEEP_LINK = 5,
  STORAGE_SETTINGS = 6,
  PRIVACY_SETTINGS = 7,
}