export enum DOWNLOADQUALITYTYPE {
  NORMAL_QUALITY = 1,
  MID_QUALITY = 2,
  INELIGIBLE_IMAGE_TOO_SMALL = 3,
  INELIGIBLE_PARTIAL_HASHES_NOT_FOUND = 4,
  ERROR_DETERMINING_ELIGIBILITY = 5,
  NOT_DOWNLOADED_ENOUGH_BYTES_TO_DETERMINE_ELIGIBILITY = 6,
}