export enum ENUMASPRESENTEDBIMONTHLYDAILYFORTNIGHTLYHALFYEARLYMONTHLYONETIMEQUARTERLYUNKNOWNWEEKLYYEARLY {
  ASPRESENTED = "ASPRESENTED",
  BIMONTHLY = "BIMONTHLY",
  DAILY = "DAILY",
  FORTNIGHTLY = "FORTNIGHTLY",
  HALFYEARLY = "HALFYEARLY",
  MONTHLY = "MONTHLY",
  ONETIME = "ONETIME",
  QUARTERLY = "QUARTERLY",
  UNKNOWN = "UNKNOWN",
  WEEKLY = "WEEKLY",
  YEARLY = "YEARLY",
}