export enum ENUMCITYCOUNTRYCUSTOMLOCATIONNEIGHBORHOODREGIONZIP {
  CITY = "CITY",
  COUNTRY = "COUNTRY",
  CUSTOM_LOCATION = "CUSTOM_LOCATION",
  NEIGHBORHOOD = "NEIGHBORHOOD",
  REGION = "REGION",
  ZIP = "ZIP",
}