export enum ENUMCALLPERMISSIONREQUESTCATALOGMESSAGEMENUOPTIONSORDERDETAILSORDERSTATUSOTPPAYMENTINFOPAYMENTKEYINFOPAYMENTMETHODPAYMENTSTATUSSPLITPAYMENTVIDEOCALLVOICECALL {
   = "",
  CALL_PERMISSION_REQUEST = "call_permission_request",
  CATALOG_MESSAGE = "catalog_message",
  MENU_OPTIONS = "menu_options",
  ORDER_DETAILS = "order_details",
  ORDER_STATUS = "order_status",
  OTP = "otp",
  PAYMENT_INFO = "payment_info",
  PAYMENT_KEY_INFO = "payment_key_info",
  PAYMENT_METHOD = "payment_method",
  PAYMENT_STATUS = "payment_status",
  SPLIT_PAYMENT = "split_payment",
  VIDEO_CALL = "video_call",
  VOICE_CALL = "voice_call",
}