export enum ENUMELIGIBLEFORPARODYPENDINGACKNOWLEDGEMENTISPARODYANDACKNOWLEDGEDNOTELIGIBLEFORPARODYUNSETORUNRECOGNIZEDENUMVALUE {
  ELIGIBLE_FOR_PARODY_PENDING_ACKNOWLEDGEMENT = "eligible_for_parody_pending_acknowledgement",
  IS_PARODY_AND_ACKNOWLEDGED = "is_parody_and_acknowledged",
  NOT_ELIGIBLE_FOR_PARODY = "not_eligible_for_parody",
  UNSET_OR_UNRECOGNIZED_ENUM_VALUE = "unset_or_unrecognized_enum_value",
}