export enum EPHEMERALSETTINGENTRYPOINTTYPE {
  CHAT_INFO = 1,
  SYSTEM_MESSAGE = 2,
  CHAT_OVERFLOW = 3,
  CHAT_PICKER = 4,
  EPHEMERAL_NUX = 5,
  CHAT_PICKER_DISAPPEARING_MODE_TIMER = 6,
  CHAT_PICKER_STORAGE_SETTING = 7,
}