export enum EXPIRYREASON {
  USER_LEAVE = 1,
  DEVICE_UNPAIR = 2,
  IDENTITY_CHANGE = 3,
  AUDIENCE_CHANGE = 4,
  PERIODIC_ROTATION = 5,
  KEY_CORRUPTION = 6,
  PEER_COMPANION_UNPAIR = 7,
  OTHER_DEVICE_UNPAIR = 8,
}