export enum IMAGINEACTIONTARGET {
  NONE = 0,
  IMAGINE_EDIT = 1,
  IMAGINE_ME = 2,
  IMAGINE_FLASH = 3,
  IMAGINE = 4,
  MEDIA_INPUT = 5,
  MEDIA_SHARING_EDIT = 6,
  MEDIA_SHARING_STYLES = 7,
  MEDIA_SHARING_INTENTS = 8,
  MEDIA_SHARING_FILTERS = 9,
}