export enum IMAGESEARCHFAILEDERRORTYPE {
  NON_200_RESPONSE = 0,
  NON_302_RESPONSE = 1,
  NULL_RESPONSE_BODY = 2,
  DECODE_OR_PARSE_ERROR = 3,
  NO_REDIRECT_URL = 4,
  INVALID_URL = 5,
  CONSENT_FORM_IN_URL = 6,
  NETWORK_ERROR = 7,
  UNKNOWN_ERROR = 8,
}