export enum LISTTYPE {
  NONE = 0,
  UNREAD = 1,
  GROUP = 2,
  FAVORITE = 3,
  PREDEFINED = 4,
  CUSTOM = 5,
  COMMUNITY = 6,
  BUSINESS_AI = 7,
  DRAFTS = 8,
  CAMPAIGN_REPLIES = 9,
  SERVER_ASSIGNED = 10,
}