export enum LWICTWAADSTATUSTYPE {
  ACTIVE = 1,
  SCHEDULED = 2,
  PAUSED = 3,
  NOT_DELIVERING = 4,
  REJECTED = 5,
  FINISHED = 6,
  IN_REVIEW = 7,
  COMPLETED = 8,
  EXTENDABLE = 9,
  UNABLE_TO_CREATE = 10,
  LIMITED_DELIVERY = 11,
}