export enum LWIENTRYPOINTIMPRESSIONACTION {
  LWI_ACTION_DISMISS = 1,
  LWI_ACTION_RECOMMENDATION_FETCH_START = 2,
  LWI_ACTION_RECOMMENDATION_FETCH_RESPONSE = 3,
  LWI_ACTION_RECOMMENDATION_FETCH_ERROR = 4,
  LWI_ACTION_IMPRESSION = 5,
  LWI_ACTION_SUPPRESSED_BY_CAP = 6,
}