export enum LWIADCREATIONACCOUNTCONSENTFLOW {
  SKIP_CONSENT_WITH_EXISTING_FB_CONSENT = 1,
  SKIP_CONSENT_WITHOUT_FB_WEBLOGIN_OPTION = 2,
  SKIP_CONSENT_WITH_FB_WEBLOGIN_OPTION = 3,
  SKIP_CONSENT_WITH_SUGGEST_FB_CONSENT = 4,
  ACCEPT_CONSENT_WITH_SUGGEST_FB_CONSENT = 5,
  ACCEPT_CONSENT_WITH_REQUIRE_FB_CONSENT = 6,
  RELOAD_BLOKS_SCREEN_ON_SUCCESS_FB_WEB_SSO = 7,
}