export enum MDCHATASSIGNMENTSECONDARYACTIONTYPE {
  ACTION_SYSTEM_MESSAGE_ADDED_TO_CHAT_HISTORY = 0,
  ACTION_SYSTEM_MESSAGE_CREATION_ERROR = 1,
  ACTION_SYSTEM_MESSAGE_RENDERED = 2,
  ACTION_CHAT_STATUS_TICKER_SHOWN = 3,
  ACTION_TOOLTIP_SHOWN = 4,
}