export enum PRIVACYSETTINGSVALUETYPE {
  NOBODY = 1,
  ONLY_SHARE_WITH = 2,
  MY_CONTACTS = 3,
  MY_CONTACTS_EXCEPT = 4,
  EVERYONE = 5,
  KNOWN = 6,
  CLOSE_FRIENDS = 7,
  CUSTOM_LIST = 8,
  GROUP_STATUS = 9,
}