export enum PSGROUPSAFETYCHECKEXITDIALOGACTIONS {
  GROUP_EXIT_DIALOG_DISMISS = 0,
  GROUP_EXIT_DIALOG_EXIT = 1,
  GROUP_EXIT_DIALOG_EXIT_AND_REPORT = 2,
  COMMUNITY_EXIT_DIALOG_DISMISS = 3,
  COMMUNITY_EXIT_DIALOG_EXIT = 4,
  COMMUNITY_EXIT_DIALOG_EXIT_AND_DELETE = 5,
}