export enum REPORTINGTOKENVALIDATIONFAILUREREASON {
  MISSING_MESSAGE_SECRET = 0,
  EMPTY_REPORTING_TOKEN_CONTENT = 1,
  MISMATCH_REPORTING_TOKEN = 2,
  UNSUPPORTED_VERSION = 3,
  GROUP_HISTORY_MESSAGE_MISSING_FROM_PUBLIC_STANZA = 4,
}