export enum SMBLISTSURFACETYPE {
  BIZ_TOOLS = 1,
  MANAGE_LISTS = 2,
  NEW_LIST = 3,
  INBOX = 4,
  INBOX_CHAT_ROW_MORE = 5,
  INBOX_CHAT_BOTTOM_SHEET = 6,
  INBOX_CHAT_BOTTOM_SHEET_ADD_TO_LIST = 7,
  CHOOSE_LIST_SHEET = 8,
}