export enum SMBPERCUSTOMERDATASHARINGCONTROLACTION {
  SYSTEM_MESSAGE_INSERTED = 0,
  CONSENT_SCREEN_VIEW = 1,
  CONSENT_SCREEN_CONFIRM = 2,
  CONSENT_SCREEN_CANCEL = 3,
  CONTACT_TOGGLE_CHANGED = 4,
}