export enum STATUSVIEWACTIONTYPE {
  ATTRIBUTION_TAPPED = 0,
  ATTRIBUTION_LIST_OPENED = 1,
  ATTRIBUTION_LIST_ITEM_TAPPED = 2,
  QUESTION_STICKER_CLICK = 3,
  QUESTION_ANSWER_SEND = 4,
  REACTION_STICKER_CLICK = 5,
  RESHARE_BUTTON_TAP = 6,
  CLOSE_SHARING_EMOJI_CLICK = 7,
  URL_CLICK = 8,
}