export enum STORYOVERLAYBLOKSLINKSTICKERSTYLES {
  IG_ADD_TO_YOURS_STICKER_CROSSPOST = "IG_ADD_TO_YOURS_STICKER_CROSSPOST",
  IG_FEED_URL = "IG_FEED_URL",
  IG_LINK_STICKER_CROSSPOST = "IG_LINK_STICKER_CROSSPOST",
  IG_MULTI_OPTION_POLL_CROSSPOST = "IG_MULTI_OPTION_POLL_CROSSPOST",
  IG_REEL_URL = "IG_REEL_URL",
  IG_TEXT_POST_SHARE_CROSSPOST = "IG_TEXT_POST_SHARE_CROSSPOST",
  URL_ONLY = "URL_ONLY",
}