export enum UPDATETABSEARCHEVENTTYPE {
  SEARCH_TAP = 1,
  SEARCH = 5,
  SERP_LOADED = 6,
  SEARCH_RESULT_SCROLL = 7,
  SEARCH_SUBMIT = 8,
  ITEM_TAP = 9,
  ITEM_REMOVE = 10,
  FOLLOW = 11,
  UNFOLLOW = 12,
}