export enum WACALLINGHISTORYGROUPCALLRECORDSAVECONDITIONCHECKSTATUS {
  INVALID = 0,
  NOT_GROUP_CALL = 1,
  NOT_START_FROM_VIDEO_CALL = 2,
  HAS_AV_SWITCH = 3,
  SELF_CAMERA_OFF = 4,
  PEER_CAMERA_OFF = 5,
  SELF_HAS_NETWORK_TRANSITION = 6,
  PEER_HAS_NETWORK_TRANSITION = 7,
  CALL_TOO_SHORT = 8,
  PASS = 100,
}