export enum WAFFLELIFECYCLETRACESOURCETYPE {
  NOT_APPLICABLE = 0,
  SYNCD = 1,
  NOTIFICATION_LINKED = 2,
  NOTIFICATION_UNLINKED = 3,
  NOTIFICATION_RESYNC = 4,
  NONCE_REQUEST = 5,
  NONCE_RESPONSE = 6,
  REFRESH_TOKEN = 7,
  ERROR_RETRY = 8,
  PRIMARY_NONCE_REQUEST = 9,
  PRIMARY_NONCE_RESPONSE = 10,
}