export enum WAFFLELIFECYCLEERRORCODETYPE {
  NOT_APPLICABLE = 0,
  TIMEOUT = 1,
  RATE_OVERLIMIT = 2,
  NOT_AUTHORIZED = 3,
  INVALID_PASSWORD = 4,
  WF_NOT_FOUND = 5,
  WF_STATE_MISMATCH = 6,
  WF_SUSPENDED = 7,
  UNKNOWN = 8,
}