export enum WEBCBUTTERBARBBTYPE {
  OFFLINE = 1,
  RESUME_CONNECTING = 2,
  RESUME_LOADING_MSGS_PROGRESS = 3,
  UPDATE_DUE_TO_SOFT_MIN = 4,
  UWP_UPSELL = 5,
  NOTIFICATION = 6,
  OFFLINE_NOTIFICATION = 7,
  NOTIFICATION_DISABLED = 8,
  NOTIFICATION_AWARENESS = 9,
}