export enum WEBCWEBPLATFORMTYPE {
  WEB = 1,
  WIN32 = 2,
  DARWIN = 3,
  IOS_TABLET = 4,
  ANDROID_TABLET = 5,
  WINSTORE = 6,
  MACSTORE = 7,
  DARWIN_BETA = 8,
  WIN32_BETA = 9,
  PWA = 10,
  WIN_HYBRID = 11,
}